using System.Collections.Generic;
using MHW_Generator.Models;
using MHW_Template;
using MHW_Template.Struct_Generation;

namespace MHW_Generator.PlData {
    public class PlItemParam : IMultiStruct {
        public MultiStruct Generate() { // .plip
            var structs = new List<MhwMultiStructData.StructData> {
                new MhwMultiStructData.StructData("Header", new List<MhwMultiStructData.Entry> {
                    new MhwMultiStructData.Entry("PLI", typeof(char), true, typeof(string), arrayCount: 4),
                    new MhwMultiStructData.Entry("Magic 1", typeof(uint), true)
                }, 1),

                new MhwMultiStructData.StructData("Item Params (1)", new List<MhwMultiStructData.Entry> {
                    new MhwMultiStructData.Entry("Powder Radius", typeof(float)),
                    new MhwMultiStructData.Entry("Potion Power", typeof(uint)),
                    new MhwMultiStructData.Entry("Unk2", typeof(float)),
                    new MhwMultiStructData.Entry("Unk3", typeof(float)),
                    new MhwMultiStructData.Entry("Unk4", typeof(float)),
                    new MhwMultiStructData.Entry("Mega Potion Power", typeof(uint)),
                    new MhwMultiStructData.Entry("Unk5", typeof(float)),
                    new MhwMultiStructData.Entry("Unk6", typeof(float)),
                    new MhwMultiStructData.Entry("Unk7", typeof(float)),
                    new MhwMultiStructData.Entry("Nutrients Power", typeof(byte)),
                    new MhwMultiStructData.Entry("Mega Nutrients Power", typeof(byte)),
                    new MhwMultiStructData.Entry("Unk9", typeof(byte)),
                    new MhwMultiStructData.Entry("Mega Dash Juice Stamina Power", typeof(float)),
                    new MhwMultiStructData.Entry("Dash Juice Stamina Power", typeof(float)),
                    new MhwMultiStructData.Entry("Both Dash Juice Duration", typeof(ushort)),
                    new MhwMultiStructData.Entry("Both Dash Juice Power", typeof(byte)),
                    new MhwMultiStructData.Entry("Immunizer Power", typeof(float)),
                    new MhwMultiStructData.Entry("Immunizer Duration", typeof(ushort)),
                    new MhwMultiStructData.Entry("Astera Jerky Power", typeof(float)),
                    new MhwMultiStructData.Entry("Astera Jerky Duration", typeof(ushort)),
                    new MhwMultiStructData.Entry("Herbal Medicine Power", typeof(ushort)),
                    new MhwMultiStructData.Entry("Sushifish Scale Power", typeof(uint)),
                    new MhwMultiStructData.Entry("Great Sushifish Scale Power", typeof(uint)),
                    new MhwMultiStructData.Entry("Great Sushifish Scale Duration", typeof(float)),
                    new MhwMultiStructData.Entry("Cool Drink Duration", typeof(ushort)),
                    new MhwMultiStructData.Entry("Hot Drink Duration", typeof(ushort)),
                    new MhwMultiStructData.Entry("Might Seed Duration", typeof(ushort)),
                    new MhwMultiStructData.Entry("Might Seed Power", typeof(ushort)),
                    new MhwMultiStructData.Entry("Might Pill Duration", typeof(ushort)),
                    new MhwMultiStructData.Entry("Might Pill Power", typeof(ushort)),
                    new MhwMultiStructData.Entry("Adamant Seed Duration", typeof(ushort)),
                    new MhwMultiStructData.Entry("Adamant Seed Power", typeof(ushort)),
                    new MhwMultiStructData.Entry("Adamant Pill Duration", typeof(ushort)),
                    new MhwMultiStructData.Entry("Adamant Pill Power", typeof(float)),
                    new MhwMultiStructData.Entry("Demondrug Power", typeof(byte)),
                    new MhwMultiStructData.Entry("Mega Demondrug Power", typeof(byte)),
                    new MhwMultiStructData.Entry("Armorskin Power", typeof(byte)),
                    new MhwMultiStructData.Entry("Mega Armorskin Power", typeof(byte)),
                    new MhwMultiStructData.Entry("Unk16", typeof(ushort)),
                    new MhwMultiStructData.Entry("Lifepowder Power", typeof(ushort)),
                    new MhwMultiStructData.Entry("Dust of Life Power", typeof(ushort)),
                    new MhwMultiStructData.Entry("Herbal Powder Power", typeof(ushort)),
                    new MhwMultiStructData.Entry("Demon Powder Power", typeof(ushort)),
                    new MhwMultiStructData.Entry("Demon Powder Duration", typeof(ushort)),
                    new MhwMultiStructData.Entry("Hardshell Powder Power", typeof(ushort)),
                    new MhwMultiStructData.Entry("Hardshell Powder Duration", typeof(ushort)),
                    new MhwMultiStructData.Entry("Demon Ammo Power", typeof(ushort)),
                    new MhwMultiStructData.Entry("Demon Ammo Duration", typeof(ushort)),
                    new MhwMultiStructData.Entry("Armor Ammo Power", typeof(ushort)),
                    new MhwMultiStructData.Entry("Armor Ammo Duration", typeof(ushort)),
                    new MhwMultiStructData.Entry("Ration Power", typeof(ushort)),
                    new MhwMultiStructData.Entry("Well Done Steak Multiplier", typeof(uint)),
                    new MhwMultiStructData.Entry("Well Done Steak Stamina Bonus", typeof(float)),
                    new MhwMultiStructData.Entry("Unk23", typeof(float)),
                    new MhwMultiStructData.Entry("Unk24", typeof(float)),
                    new MhwMultiStructData.Entry("Burnt Meat Stamina Recovery", typeof(ushort)),
                    new MhwMultiStructData.Entry("Unk26", typeof(short)),
                    new MhwMultiStructData.Entry("Unk27", typeof(byte)),
                    new MhwMultiStructData.Entry("Unk28", typeof(float)),
                    new MhwMultiStructData.Entry("Unk29", typeof(float)),
                    new MhwMultiStructData.Entry("Unk30", typeof(float)),
                    new MhwMultiStructData.Entry("Unk31", typeof(float)),
                    new MhwMultiStructData.Entry("Unk32", typeof(float)),
                    new MhwMultiStructData.Entry("Unk33", typeof(float)),
                    new MhwMultiStructData.Entry("Unk34", typeof(float)),
                    new MhwMultiStructData.Entry("Unk35", typeof(float)),
                    new MhwMultiStructData.Entry("Unk36", typeof(float)),
                    new MhwMultiStructData.Entry("Unk37", typeof(float)),
                    new MhwMultiStructData.Entry("Unk38", typeof(float)),
                    new MhwMultiStructData.Entry("Whetstone Sharpness Restored", typeof(uint)),
                    new MhwMultiStructData.Entry("Whetstone Cycles", typeof(uint)),
                    new MhwMultiStructData.Entry("Whetfish Scale Sharpness Restored", typeof(uint)),
                    new MhwMultiStructData.Entry("Whetfish Scale Cycles", typeof(byte)),
                    new MhwMultiStructData.Entry("Whetfish Scale Plus Cycles", typeof(byte)),
                    new MhwMultiStructData.Entry("Whetfish Scale Consume %", typeof(byte)),
                    new MhwMultiStructData.Entry("Powertalon Power", typeof(byte)),
                    new MhwMultiStructData.Entry("Powercharm Power", typeof(byte)),
                    new MhwMultiStructData.Entry("Armortalon Power", typeof(byte)),
                    new MhwMultiStructData.Entry("Armorcharm Power", typeof(byte)),
                    new MhwMultiStructData.Entry("Unk49", typeof(byte)),
                    new MhwMultiStructData.Entry("Unk50", typeof(float)),
                    new MhwMultiStructData.Entry("Unk51", typeof(float)),
                    new MhwMultiStructData.Entry("Unk52", typeof(float)),
                    new MhwMultiStructData.Entry("Unk53", typeof(float)),
                    new MhwMultiStructData.Entry("Unk54", typeof(float)),
                    new MhwMultiStructData.Entry("Unk55", typeof(float)),
                    new MhwMultiStructData.Entry("Unk56", typeof(float)),
                    new MhwMultiStructData.Entry("Unk57", typeof(float)),
                    new MhwMultiStructData.Entry("Unk58", typeof(float)),
                    new MhwMultiStructData.Entry("Unk59", typeof(float)),
                    new MhwMultiStructData.Entry("Unk60", typeof(float)),
                    new MhwMultiStructData.Entry("Unk61", typeof(float)),
                    new MhwMultiStructData.Entry("Unk62", typeof(float)),
                    new MhwMultiStructData.Entry("Unk63", typeof(float)),
                    new MhwMultiStructData.Entry("Unk64", typeof(float)),
                    new MhwMultiStructData.Entry("Unk65", typeof(float)),
                    new MhwMultiStructData.Entry("Unk66", typeof(float)),
                    new MhwMultiStructData.Entry("Unk67", typeof(float)),
                    new MhwMultiStructData.Entry("Unk68", typeof(float)),
                    new MhwMultiStructData.Entry("Unk69", typeof(float)),
                    new MhwMultiStructData.Entry("Unk70", typeof(float)),
                    new MhwMultiStructData.Entry("Unk71", typeof(float)),
                    new MhwMultiStructData.Entry("Unk72", typeof(float)),
                    new MhwMultiStructData.Entry("Unk73", typeof(float)),
                    new MhwMultiStructData.Entry("Unk74", typeof(float)),
                    new MhwMultiStructData.Entry("Unk75", typeof(float)),
                    new MhwMultiStructData.Entry("Unk76", typeof(float)),
                    new MhwMultiStructData.Entry("Unk77", typeof(float)),
                    new MhwMultiStructData.Entry("Unk78", typeof(float)),
                    new MhwMultiStructData.Entry("Unk79", typeof(float)),
                    new MhwMultiStructData.Entry("Unk80", typeof(float)),
                    new MhwMultiStructData.Entry("Unk81", typeof(float)),
                    new MhwMultiStructData.Entry("Unk82", typeof(float)),
                    new MhwMultiStructData.Entry("Unk83", typeof(float)),
                    new MhwMultiStructData.Entry("Unk84", typeof(float)),
                    new MhwMultiStructData.Entry("Unk85", typeof(float)),
                    new MhwMultiStructData.Entry("Unk86", typeof(float)),
                    new MhwMultiStructData.Entry("Unk87", typeof(float)),
                    new MhwMultiStructData.Entry("Unk88", typeof(float)),
                    new MhwMultiStructData.Entry("Unk89", typeof(float)),
                    new MhwMultiStructData.Entry("Unk90", typeof(float)),
                    new MhwMultiStructData.Entry("Unk91", typeof(float)),
                    new MhwMultiStructData.Entry("Unk92", typeof(float)),
                    new MhwMultiStructData.Entry("Unk93", typeof(float)),
                    new MhwMultiStructData.Entry("Unk94", typeof(float)),
                    new MhwMultiStructData.Entry("Unk95", typeof(float)),
                    new MhwMultiStructData.Entry("Unk96", typeof(float)),
                    new MhwMultiStructData.Entry("Unk97", typeof(float)),
                    new MhwMultiStructData.Entry("Unk98", typeof(float)),
                    new MhwMultiStructData.Entry("Unk99", typeof(float)),
                    new MhwMultiStructData.Entry("Unk100", typeof(float)),
                    new MhwMultiStructData.Entry("Unk101", typeof(float)),
                    new MhwMultiStructData.Entry("Unk102", typeof(float)),
                    new MhwMultiStructData.Entry("Unk103", typeof(float)),
                    new MhwMultiStructData.Entry("Unk104", typeof(float)),
                    new MhwMultiStructData.Entry("Unk105", typeof(float)),
                    new MhwMultiStructData.Entry("Deathcream: Fishing rumble starts here.", typeof(byte))
                }, 1, showVertically: true),

                new MhwMultiStructData.StructData("The Rest", new List<MhwMultiStructData.Entry> {
                    new MhwMultiStructData.Entry("The rest of the file as bytes.", typeof(void), true, subStruct: new MhwMultiStructData.StructData("End Junk", new List<MhwMultiStructData.Entry> {
                        new MhwMultiStructData.Entry("Unk", typeof(byte), true)
                    }, customSaveLoad: true))
                }, 1)
            };

            return new MultiStruct("MHW_Editor.PlData", "PlItemParam", new MhwMultiStructData(structs, "plip", EncryptionKeys.FILE_EXT_KEY_LOOKUP[".plip"]));
        }
    }
}