using MHW_Template;

namespace MHW_Editor.Weapons {
    // Unique Id Formula: "{Id}"
    public struct ShellTable {
        public byte Normal_1_Mag_Cnt; // Offset: 0
        public byte Normal_1_Rec_Amnt; // Offset: 1
        public byte Normal_1_Rel_Spd; // Offset: 2
        public byte Normal_2_Mag_Cnt; // Offset: 3
        public byte Normal_2_Rec_Amnt; // Offset: 4
        public byte Normal_2_Rel_Spd; // Offset: 5
        public byte Normal_3_Mag_Cnt; // Offset: 6
        public byte Normal_3_Rec_Amnt; // Offset: 7
        public byte Normal_3_Rel_Spd; // Offset: 8
        public byte Pierce_1_Mag_Cnt; // Offset: 9
        public byte Pierce_1_Rec_Amnt; // Offset: 10
        public byte Pierce_1_Rel_Spd; // Offset: 11
        public byte Pierce_2_Mag_Cnt; // Offset: 12
        public byte Pierce_2_Rec_Amnt; // Offset: 13
        public byte Pierce_2_Rel_Spd; // Offset: 14
        public byte Pierce_3_Mag_Cnt; // Offset: 15
        public byte Pierce_3_Rec_Amnt; // Offset: 16
        public byte Pierce_3_Rel_Spd; // Offset: 17
        public byte Spread_1_Mag_Cnt; // Offset: 18
        public byte Spread_1_Rec_Amnt; // Offset: 19
        public byte Spread_1_Rel_Spd; // Offset: 20
        public byte Spread_2_Mag_Cnt; // Offset: 21
        public byte Spread_2_Rec_Amnt; // Offset: 22
        public byte Spread_2_Rel_Spd; // Offset: 23
        public byte Spread_3_Mag_Cnt; // Offset: 24
        public byte Spread_3_Rec_Amnt; // Offset: 25
        public byte Spread_3_Rel_Spd; // Offset: 26
        public byte Cluster_1_Mag_Cnt; // Offset: 27
        public byte Cluster_1_Rec_Amnt; // Offset: 28
        public byte Cluster_1_Rel_Spd; // Offset: 29
        public byte Cluster_2_Mag_Cnt; // Offset: 30
        public byte Cluster_2_Rec_Amnt; // Offset: 31
        public byte Cluster_2_Rel_Spd; // Offset: 32
        public byte Cluster_3_Mag_Cnt; // Offset: 33
        public byte Cluster_3_Rec_Amnt; // Offset: 34
        public byte Cluster_3_Rel_Spd; // Offset: 35
        public byte Wyvern_Mag_Cnt; // Offset: 36
        public byte Wyvern_Rec_Amnt; // Offset: 37
        public byte Wyvern_Rel_Spd; // Offset: 38
        public byte Sticky_1_Mag_Cnt; // Offset: 39
        public byte Sticky_1_Rec_Amnt; // Offset: 40
        public byte Sticky_1_Rel_Spd; // Offset: 41
        public byte Sticky_2_Mag_Cnt; // Offset: 42
        public byte Sticky_2_Rec_Amnt; // Offset: 43
        public byte Sticky_2_Rel_Spd; // Offset: 44
        public byte Sticky_3_Mag_Cnt; // Offset: 45
        public byte Sticky_3_Rec_Amnt; // Offset: 46
        public byte Sticky_3_Rel_Spd; // Offset: 47
        public byte Slicing_Mag_Cnt; // Offset: 48
        public byte Slicing_Rec_Amnt; // Offset: 49
        public byte Slicing_Rel_Spd; // Offset: 50
        public byte Flaming_Mag_Cnt; // Offset: 51
        public byte Flaming_Rec_Amnt; // Offset: 52
        public byte Flaming_Rel_Spd; // Offset: 53
        public byte Water_Mag_Cnt; // Offset: 54
        public byte Water_Rec_Amnt; // Offset: 55
        public byte Water_Rel_Spd; // Offset: 56
        public byte Freeze_Mag_Cnt; // Offset: 57
        public byte Freeze_Rec_Amnt; // Offset: 58
        public byte Freeze_Rel_Spd; // Offset: 59
        public byte Thunder_Mag_Cnt; // Offset: 60
        public byte Thunder_Rec_Amnt; // Offset: 61
        public byte Thunder_Rel_Spd; // Offset: 62
        public byte Dragon_Mag_Cnt; // Offset: 63
        public byte Dragon_Rec_Amnt; // Offset: 64
        public byte Dragon_Rel_Spd; // Offset: 65
        public byte Poison_1_Mag_Cnt; // Offset: 66
        public byte Poison_1_Rec_Amnt; // Offset: 67
        public byte Poison_1_Rel_Spd; // Offset: 68
        public byte Poison_2_Mag_Cnt; // Offset: 69
        public byte Poison_2_Rec_Amnt; // Offset: 70
        public byte Poison_2_Rel_Spd; // Offset: 71
        public byte Paralysis_1_Mag_Cnt; // Offset: 72
        public byte Paralysis_1_Rec_Amnt; // Offset: 73
        public byte Paralysis_1_Rel_Spd; // Offset: 74
        public byte Paralysis_2_Mag_Cnt; // Offset: 75
        public byte Paralysis_2_Rec_Amnt; // Offset: 76
        public byte Paralysis_2_Rel_Spd; // Offset: 77
        public byte Sleep_1_Mag_Cnt; // Offset: 78
        public byte Sleep_1_Rec_Amnt; // Offset: 79
        public byte Sleep_1_Rel_Spd; // Offset: 80
        public byte Sleep_2_Mag_Cnt; // Offset: 81
        public byte Sleep_2_Rec_Amnt; // Offset: 82
        public byte Sleep_2_Rel_Spd; // Offset: 83
        public byte Exhaust_1_Mag_Cnt; // Offset: 84
        public byte Exhaust_1_Rec_Amnt; // Offset: 85
        public byte Exhaust_1_Rel_Spd; // Offset: 86
        public byte Exhaust_2_Mag_Cnt; // Offset: 87
        public byte Exhaust_2_Rec_Amnt; // Offset: 88
        public byte Exhaust_2_Rel_Spd; // Offset: 89
        public byte Recover_1_Mag_Cnt; // Offset: 90
        public byte Recover_1_Rec_Amnt; // Offset: 91
        public byte Recover_1_Rel_Spd; // Offset: 92
        public byte Recover_2_Mag_Cnt; // Offset: 93
        public byte Recover_2_Rec_Amnt; // Offset: 94
        public byte Recover_2_Rel_Spd; // Offset: 95
        public byte Demon_Mag_Cnt; // Offset: 96
        public byte Demon_Rec_Amnt; // Offset: 97
        public byte Demon_Rel_Spd; // Offset: 98
        public byte Armor_Mag_Cnt; // Offset: 99
        public byte Armor_Rec_Amnt; // Offset: 100
        public byte Armor_Rel_Spd; // Offset: 101
        public byte Tranq_Mag_Cnt; // Offset: 108
        public byte Tranq_Rec_Amnt; // Offset: 109
        public byte Tranq_Rel_Spd; // Offset: 110
    }
}