using System.Collections.Generic;
using MHW_Generator.Models;
using MHW_Template;

namespace MHW_Generator.Weapons {
    public class ShellParam : IMultiStruct {
        public MultiStruct Generate() { // .shlp
            var i = 0;

            var structs = new List<MhwMultiStructData.StructData> {
                new MhwMultiStructData.StructData("Shlp", new List<MhwMultiStructData.StructData.Entry> {
                    new MhwMultiStructData.StructData.Entry("Magic 1", typeof(uint), true),
                    new MhwMultiStructData.StructData.Entry("SLP", typeof(char), true, typeof(string), arrayCount: 4),
                    new MhwMultiStructData.StructData.Entry("Magic 2", typeof(uint), true)
                }, 1),
                new MhwMultiStructData.StructData("Assets", new List<MhwMultiStructData.StructData.Entry> {
                    new MhwMultiStructData.StructData.Entry("Header", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Path", typeof(string), isNullTerminatedString: true, condition: "if (|ref|Header_raw != 0)")
                }, 25),
                new MhwMultiStructData.StructData("Shlp (1)", new List<MhwMultiStructData.StructData.Entry> {
                    new MhwMultiStructData.StructData.Entry("Particles: Projectile Header", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Particles: Projectile", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Particles: Muzzle Header", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Particles: Muzzle", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Unk 1", typeof(int)),
                    new MhwMultiStructData.StructData.Entry("Obj Collision Header", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Obj Collision", typeof(string), isNullTerminatedString: true, condition: "if (|ref|Obj_Collision_Header_raw != 0)"),
                    new MhwMultiStructData.StructData.Entry("Obj Collision Index", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Timeline List Header", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Timeline List", typeof(string), isNullTerminatedString: true, condition: "if (|ref|Timeline_List_Header_raw != 0)"),
                    new MhwMultiStructData.StructData.Entry("Unk 2", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Unk 3", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Unk 4", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Unk 5", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Unk 6", typeof(uint))
                }, 1, showVertically: true),
                new MhwMultiStructData.StructData("Number of Linked Shell Params Holder", new List<MhwMultiStructData.StructData.Entry> {
                    new MhwMultiStructData.StructData.Entry("Number of Linked Shell Params", typeof(uint), true)
                }, 1, true),
                new MhwMultiStructData.StructData("Linked Shell Params", new List<MhwMultiStructData.StructData.Entry> {
                    new MhwMultiStructData.StructData.Entry("Header", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Path", typeof(string), isNullTerminatedString: true),
                    new MhwMultiStructData.StructData.Entry("Unk 1", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Flags", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Unk 3", typeof(uint))
                }, canAddRows: true),
                new MhwMultiStructData.StructData("Shlp (2)", new List<MhwMultiStructData.StructData.Entry> {
                    new MhwMultiStructData.StructData.Entry("Particles: Ground Decal Header", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Particles: Ground Decal", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Particles: Wall Decal Header", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Particles: Wall Decal", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Particles: Obj Hit Header", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Particles: Obj Hit", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(byte)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(byte)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(byte)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(byte)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(byte)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(byte)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(byte)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(byte)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(byte)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(byte)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(byte)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(byte)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(byte)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(byte)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(int)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Particles: Gun Fire Header", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Particles: Gun Fire", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Wwise Container Header", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Wwise Container", typeof(string), isNullTerminatedString: true, condition: "if (|ref|Wwise_Container_Header_raw != 0)"),
                    new MhwMultiStructData.StructData.Entry("Sound: Gun Fire Header", typeof(int)),
                    new MhwMultiStructData.StructData.Entry("Sound: Gun Fire", typeof(int)),
                    new MhwMultiStructData.StructData.Entry("Sound: Bullet Travel Header", typeof(int)),
                    new MhwMultiStructData.StructData.Entry("Sound: Bullet Travel", typeof(int)),
                    new MhwMultiStructData.StructData.Entry("Sound: Explode Header", typeof(int)),
                    new MhwMultiStructData.StructData.Entry("Sound: Explode", typeof(int)),
                    new MhwMultiStructData.StructData.Entry("Sound: Hit Wall or Ground Header", typeof(int)),
                    new MhwMultiStructData.StructData.Entry("Sound: Hit Wall or Ground", typeof(int)),
                    new MhwMultiStructData.StructData.Entry("Sound: Hit Obj Hit Header", typeof(int)),
                    new MhwMultiStructData.StructData.Entry("Sound: Hit Obj Hit", typeof(int)),
                    new MhwMultiStructData.StructData.Entry("Sound: Condition Header 1", typeof(int)),
                    new MhwMultiStructData.StructData.Entry("Sound: Condition 1", typeof(int)),
                    new MhwMultiStructData.StructData.Entry("Sound: Slinger Condition Header 1", typeof(int)),
                    new MhwMultiStructData.StructData.Entry("Sound: Slinger Condition 1", typeof(int)),
                    new MhwMultiStructData.StructData.Entry("Sound: Slinger Condition Header 2", typeof(int)),
                    new MhwMultiStructData.StructData.Entry("Sound: Slinger Condition 2", typeof(int)),
                    new MhwMultiStructData.StructData.Entry("Sound: Condition Header 2", typeof(int)),
                    new MhwMultiStructData.StructData.Entry("Sound: Condition 2", typeof(int)),
                    new MhwMultiStructData.StructData.Entry("Sound: Condition Header 3", typeof(int)),
                    new MhwMultiStructData.StructData.Entry("Sound: Condition 3", typeof(int)),
                    new MhwMultiStructData.StructData.Entry("Sound: Condition Header 4", typeof(int)),
                    new MhwMultiStructData.StructData.Entry("Sound: Condition 4", typeof(int)),
                    new MhwMultiStructData.StructData.Entry("Sound: Condition Header 5", typeof(int)),
                    new MhwMultiStructData.StructData.Entry("Sound: Condition 5", typeof(int)),
                    new MhwMultiStructData.StructData.Entry("Header", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Projectile: Entity Collider", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Projectile: Model Lifespan", typeof(float)),
                    new MhwMultiStructData.StructData.Entry("Projectile: Distance Range", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(byte)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(byte)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(byte)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(byte)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Projectile: Spawn Pos Y", typeof(float)),
                    new MhwMultiStructData.StructData.Entry("Projectile: Spawn Pos X", typeof(float)),
                    new MhwMultiStructData.StructData.Entry("Projectile: Velocity", typeof(float)),
                    new MhwMultiStructData.StructData.Entry("Projectile: Falloff", typeof(float)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(float)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(float)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(float)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(float)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(float)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(float)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(float)),
                    new MhwMultiStructData.StructData.Entry("Projectile: Hitbox Range", typeof(float)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Insta-Kill Trigger", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(ushort)),
                    new MhwMultiStructData.StructData.Entry("Entity: Collide 1", typeof(float)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(float)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(float)),
                    new MhwMultiStructData.StructData.Entry("Entity: Collide 2", typeof(byte)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(byte)),
                    new MhwMultiStructData.StructData.Entry("Entity: Spawn Location", typeof(byte)),
                    new MhwMultiStructData.StructData.Entry("Entity: Range", typeof(byte)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(byte)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(byte)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(ushort)),
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(uint))
                }, 1, showVertically: true),
                new MhwMultiStructData.StructData("Number of Modifiers Holder", new List<MhwMultiStructData.StructData.Entry> {
                    new MhwMultiStructData.StructData.Entry("Number of Modifiers", typeof(uint), true)
                }, 1, true),
                new MhwMultiStructData.StructData("Modifiers", new List<MhwMultiStructData.StructData.Entry> {
                    new MhwMultiStructData.StructData.Entry("Header", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Value 1 (if 412627386)", typeof(sbyte), condition: "if (|ref|Header_raw == 412627386)"),
                    new MhwMultiStructData.StructData.Entry("Value 2 (if 412627386)", typeof(sbyte), condition: "if (|ref|Header_raw == 412627386)"),
                    new MhwMultiStructData.StructData.Entry("Value 3 (if 412627386)", typeof(sbyte), condition: "if (|ref|Header_raw == 412627386)"),
                    new MhwMultiStructData.StructData.Entry("Value 4 (if 412627386)", typeof(sbyte), condition: "if (|ref|Header_raw == 412627386)"),
                    new MhwMultiStructData.StructData.Entry("Value (if 3289971)", typeof(int), condition: "if (|ref|Header_raw == 3289971)"),
                    new MhwMultiStructData.StructData.Entry("Value (if 79120377)", typeof(float), condition: "if (|ref|Header_raw == 79120377)"),
                    new MhwMultiStructData.StructData.Entry("Value (if 306780182)", typeof(sbyte), condition: "if (|ref|Header_raw == 306780182)"),
                    new MhwMultiStructData.StructData.Entry("Value X (if 1335056316)", typeof(float), condition: "if (|ref|Header_raw == 1335056316)"),
                    new MhwMultiStructData.StructData.Entry("Value Y (if 1335056316)", typeof(float), condition: "if (|ref|Header_raw == 1335056316)"),
                    new MhwMultiStructData.StructData.Entry("Value Z (if 1335056316)", typeof(float), condition: "if (|ref|Header_raw == 1335056316)"),
                    new MhwMultiStructData.StructData.Entry("Value Unk (if 1335056316)", typeof(float), condition: "if (|ref|Header_raw == 1335056316)"),
                    new MhwMultiStructData.StructData.Entry("Name", typeof(string), isNullTerminatedString: true),
                    new MhwMultiStructData.StructData.Entry("Unk 1", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("DataType", typeof(string), isNullTerminatedString: true),
                    new MhwMultiStructData.StructData.Entry("Unk 2", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Unk 3", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Unk 4", typeof(uint)),
                    new MhwMultiStructData.StructData.Entry("Unk 5", typeof(byte))
                }, canAddRows: true),
                new MhwMultiStructData.StructData("Unknown", new List<MhwMultiStructData.StructData.Entry> {
                    new MhwMultiStructData.StructData.Entry($"Unk {++i}", typeof(uint))
                }, 1)
            };

            return new MultiStruct("MHW_Editor.Weapons", "ShellParam", new MhwMultiStructData(structs, EncryptionKeys.FILE_EXT_KEY_LOOKUP[".shlp"]));
        }
    }
}