using System.Collections.Generic;
using MHW_Generator.Models;
using MHW_Template;
using MHW_Template.Struct_Generation.Multi;

namespace MHW_Generator.Weapons {
    public class Wp12Param : IMultiStruct {
        public static readonly List<MhwMultiStructData.StructData> baseStructs;

        static Wp12Param() {
            var p1 = new MhwMultiStructData.StructData("W12p Params (1)", new List<MhwMultiStructData.Entry> {
                new MhwMultiStructData.Entry("Weapon", typeof(char), true, typeof(string), arrayCount: 4),
                new MhwMultiStructData.Entry("Unk 1", typeof(uint)),
                new MhwMultiStructData.Entry("Unk 2", typeof(uint))
            }, 1);

            var unk1 = new MhwMultiStructData.StructData("Unk Struct 1", new List<MhwMultiStructData.Entry> {
                new MhwMultiStructData.Entry("Unk 1", typeof(float)),
                new MhwMultiStructData.Entry("Unk 2", typeof(float)),
                new MhwMultiStructData.Entry("Unk 3", typeof(byte)),
                new MhwMultiStructData.Entry("Unk 4", typeof(float)),
                new MhwMultiStructData.Entry("Unk 5", typeof(float))
            }, 20);

            var p2 = new MhwMultiStructData.StructData("W12p Params (2)", new List<MhwMultiStructData.Entry> {
                new MhwMultiStructData.Entry("Unk1", typeof(float)),
                new MhwMultiStructData.Entry("Unk2", typeof(float)),
                new MhwMultiStructData.Entry("Unk3", typeof(float)),
                new MhwMultiStructData.Entry("Unk4", typeof(float)),
                new MhwMultiStructData.Entry("Unk5", typeof(float)),
                new MhwMultiStructData.Entry("Unk6", typeof(float)),
                new MhwMultiStructData.Entry("Unk7", typeof(float)),
                new MhwMultiStructData.Entry("Unk8", typeof(float)),
                new MhwMultiStructData.Entry("Unk9", typeof(float)),
                new MhwMultiStructData.Entry("Unk10", typeof(float)),
                new MhwMultiStructData.Entry("Unk11", typeof(float)),
                new MhwMultiStructData.Entry("Unk12", typeof(float)),
                new MhwMultiStructData.Entry("Unk13", typeof(float)),
                new MhwMultiStructData.Entry("Unk14", typeof(float)),
                new MhwMultiStructData.Entry("Unk15", typeof(float)),
                new MhwMultiStructData.Entry("Unk16", typeof(uint)),
                new MhwMultiStructData.Entry("Unk17", typeof(float)),
                new MhwMultiStructData.Entry("Unk18", typeof(float)),
                new MhwMultiStructData.Entry("Unk19", typeof(float)),
                new MhwMultiStructData.Entry("Unk20", typeof(float)),
                new MhwMultiStructData.Entry("Unk21", typeof(byte)),
                new MhwMultiStructData.Entry("Unk22", typeof(float))
            }, 1, showVertically: true);

            var guardAnglesMaybe = new MhwMultiStructData.StructData("Guard Angles?", new List<MhwMultiStructData.Entry> {
                new MhwMultiStructData.Entry("Guard Angle (Both Sides)", typeof(float)),
                new MhwMultiStructData.Entry("Knockback Threshold Small", typeof(byte)),
                new MhwMultiStructData.Entry("Knockback Threshold Medium", typeof(byte)),
                new MhwMultiStructData.Entry("Knockback Threshold Large", typeof(byte))
            }, 2);

            var p3 = new MhwMultiStructData.StructData("W12p Params (3)", new List<MhwMultiStructData.Entry> {
                new MhwMultiStructData.Entry("Unk33", typeof(float)),
                new MhwMultiStructData.Entry("Unk34", typeof(float)),
                new MhwMultiStructData.Entry("Unk35", typeof(float)),
                new MhwMultiStructData.Entry("Unk36", typeof(float)),
                new MhwMultiStructData.Entry("Unk37", typeof(float)),
                new MhwMultiStructData.Entry("Unk38", typeof(float)),
                new MhwMultiStructData.Entry("Unk39", typeof(float)),
                new MhwMultiStructData.Entry("Unk40", typeof(float)),
                new MhwMultiStructData.Entry("Unk41", typeof(float)),
                new MhwMultiStructData.Entry("Unk42", typeof(float)),
                new MhwMultiStructData.Entry("Unk43", typeof(float)),
                new MhwMultiStructData.Entry("Unk44", typeof(float)),
                new MhwMultiStructData.Entry("Unk45", typeof(float)),
                new MhwMultiStructData.Entry("Unk46", typeof(float)),
                new MhwMultiStructData.Entry("Unk47", typeof(float)),
                new MhwMultiStructData.Entry("Unk48", typeof(float)),
                new MhwMultiStructData.Entry("Unk49", typeof(float)),
                new MhwMultiStructData.Entry("Unk50", typeof(float)),
                new MhwMultiStructData.Entry("Unk51", typeof(float)),
                new MhwMultiStructData.Entry("Unk52", typeof(float)),
                new MhwMultiStructData.Entry("Unk53", typeof(float)),
                new MhwMultiStructData.Entry("Unk54", typeof(float)),
                new MhwMultiStructData.Entry("Unk55", typeof(float)),
                new MhwMultiStructData.Entry("Unk56", typeof(float)),
                new MhwMultiStructData.Entry("Unk57", typeof(float)),
                new MhwMultiStructData.Entry("Unk58", typeof(float)),
                new MhwMultiStructData.Entry("Unk59", typeof(float)),
                new MhwMultiStructData.Entry("Unk60", typeof(float)),
                new MhwMultiStructData.Entry("Unk61", typeof(float)),
                new MhwMultiStructData.Entry("Unk62", typeof(float)),
                new MhwMultiStructData.Entry("Unk63", typeof(float)),
                new MhwMultiStructData.Entry("Unk64", typeof(float)),
                new MhwMultiStructData.Entry("Unk65", typeof(float)),
                new MhwMultiStructData.Entry("Unk66", typeof(float)),
                new MhwMultiStructData.Entry("Unk67", typeof(float)),
                new MhwMultiStructData.Entry("Unk68", typeof(float)),
                new MhwMultiStructData.Entry("Unk69", typeof(float)),
                new MhwMultiStructData.Entry("Unk70", typeof(float)),
                new MhwMultiStructData.Entry("Unk71", typeof(float)),
                new MhwMultiStructData.Entry("Unk72", typeof(float)),
                new MhwMultiStructData.Entry("Unk73", typeof(float)),
                new MhwMultiStructData.Entry("Unk74", typeof(float)),
                new MhwMultiStructData.Entry("Unk75", typeof(float)),
                new MhwMultiStructData.Entry("Unk76", typeof(float)),
                new MhwMultiStructData.Entry("Unk77", typeof(byte)),
                new MhwMultiStructData.Entry("Unk78", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk79", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk80", typeof(float)),
                new MhwMultiStructData.Entry("Unk81", typeof(float)),
                new MhwMultiStructData.Entry("Unk82", typeof(float)),
                new MhwMultiStructData.Entry("Unk83", typeof(byte)),
                new MhwMultiStructData.Entry("Unk84", typeof(int))
            }, 1, showVertically: true);

            var unk2 = new MhwMultiStructData.StructData("Unk Struct 2", new List<MhwMultiStructData.Entry> {
                new MhwMultiStructData.Entry("Unk1", typeof(float)),
                new MhwMultiStructData.Entry("Unk2", typeof(float)),
                new MhwMultiStructData.Entry("Unk3", typeof(float)),
                new MhwMultiStructData.Entry("Unk4", typeof(float)),
                new MhwMultiStructData.Entry("Unk5", typeof(float)),
                new MhwMultiStructData.Entry("Unk6", typeof(float)),
                new MhwMultiStructData.Entry("Unk7", typeof(float)),
                new MhwMultiStructData.Entry("Unk8", typeof(float)),
                new MhwMultiStructData.Entry("Unk9", typeof(float)),
                new MhwMultiStructData.Entry("Unk10", typeof(float)),
                new MhwMultiStructData.Entry("Unk11", typeof(float)),
                new MhwMultiStructData.Entry("Unk12", typeof(float)),
                new MhwMultiStructData.Entry("Unk13", typeof(float)),
                new MhwMultiStructData.Entry("Unk14", typeof(byte)),
                new MhwMultiStructData.Entry("End", typeof(int))
            }, 8);

            var p4 = new MhwMultiStructData.StructData("W12p Params (4)", new List<MhwMultiStructData.Entry> {
                new MhwMultiStructData.Entry("Unk85", typeof(float)),
                new MhwMultiStructData.Entry("Unk86", typeof(float)),
                new MhwMultiStructData.Entry("Unk87", typeof(float)),
                new MhwMultiStructData.Entry("Unk88", typeof(float)),
                new MhwMultiStructData.Entry("Unk89", typeof(float)),
                new MhwMultiStructData.Entry("Unk90", typeof(float)),
                new MhwMultiStructData.Entry("Unk91", typeof(float)),
                new MhwMultiStructData.Entry("Unk92", typeof(float)),
                new MhwMultiStructData.Entry("Unk93", typeof(float)),
                new MhwMultiStructData.Entry("Unk94", typeof(float)),
                new MhwMultiStructData.Entry("Unk95", typeof(float)),
                new MhwMultiStructData.Entry("Unk96", typeof(float)),
                new MhwMultiStructData.Entry("Unk97", typeof(float)),
                new MhwMultiStructData.Entry("Unk98", typeof(float)),
                new MhwMultiStructData.Entry("Unk99", typeof(float)),
                new MhwMultiStructData.Entry("Unk100", typeof(float)),
                new MhwMultiStructData.Entry("Unk101", typeof(float)),
                new MhwMultiStructData.Entry("Unk102", typeof(float)),
                new MhwMultiStructData.Entry("Unk103", typeof(float)),
                new MhwMultiStructData.Entry("Unk104", typeof(float)),
                new MhwMultiStructData.Entry("Unk105", typeof(float)),
                new MhwMultiStructData.Entry("Unk106___s___", typeof(uint)),
                new MhwMultiStructData.Entry("Unk107", typeof(float)),
                new MhwMultiStructData.Entry("Unk108__", typeof(uint)),
                new MhwMultiStructData.Entry("Unk109", typeof(float)),
                new MhwMultiStructData.Entry("Unk110__", typeof(uint)),
                new MhwMultiStructData.Entry("Unk111", typeof(float)),
                new MhwMultiStructData.Entry("Unk112__", typeof(uint)),
                new MhwMultiStructData.Entry("Unk113___e___", typeof(float)),
                new MhwMultiStructData.Entry("Unk114", typeof(float)),
                new MhwMultiStructData.Entry("Unk115", typeof(float)),
                new MhwMultiStructData.Entry("Unk116", typeof(float)),
                new MhwMultiStructData.Entry("Unk117", typeof(float)),
                new MhwMultiStructData.Entry("Unk118", typeof(float)),
                new MhwMultiStructData.Entry("Unk119", typeof(float)),
                new MhwMultiStructData.Entry("Unk120", typeof(float)),
                new MhwMultiStructData.Entry("Unk121", typeof(float)),
                new MhwMultiStructData.Entry("Unk122", typeof(float)),
                new MhwMultiStructData.Entry("Unk123", typeof(float)),
                new MhwMultiStructData.Entry("Unk124", typeof(float)),
                new MhwMultiStructData.Entry("Unk125", typeof(float)),
                new MhwMultiStructData.Entry("Unk126", typeof(float)),
                new MhwMultiStructData.Entry("Unk127___s___", typeof(float)),
                new MhwMultiStructData.Entry("Unk128", typeof(float)),
                new MhwMultiStructData.Entry("Unk129", typeof(float)),
                new MhwMultiStructData.Entry("Unk130", typeof(float)),
                new MhwMultiStructData.Entry("Unk131", typeof(float)),
                new MhwMultiStructData.Entry("Unk132", typeof(float)),
                new MhwMultiStructData.Entry("Unk133", typeof(float)),
                new MhwMultiStructData.Entry("Unk134", typeof(float)),
                new MhwMultiStructData.Entry("Unk135", typeof(float)),
                new MhwMultiStructData.Entry("Unk136__", typeof(float)),
                new MhwMultiStructData.Entry("Unk137", typeof(float)),
                new MhwMultiStructData.Entry("Unk138", typeof(float)),
                new MhwMultiStructData.Entry("Unk139", typeof(float)),
                new MhwMultiStructData.Entry("Unk140", typeof(float)),
                new MhwMultiStructData.Entry("Unk141", typeof(float)),
                new MhwMultiStructData.Entry("Unk142", typeof(float)),
                new MhwMultiStructData.Entry("Unk143", typeof(float)),
                new MhwMultiStructData.Entry("Unk144", typeof(float)),
                new MhwMultiStructData.Entry("Unk145", typeof(float)),
                new MhwMultiStructData.Entry("Unk146___e___", typeof(float)),
                new MhwMultiStructData.Entry("Unk147", typeof(float)),
                new MhwMultiStructData.Entry("Unk148", typeof(float)),
                new MhwMultiStructData.Entry("Unk149", typeof(float)),
                new MhwMultiStructData.Entry("Unk150", typeof(float)),
                new MhwMultiStructData.Entry("Unk151", typeof(float)),
                new MhwMultiStructData.Entry("Unk152", typeof(float)),
                new MhwMultiStructData.Entry("Unk153", typeof(float)),
                new MhwMultiStructData.Entry("Unk154", typeof(float)),
                new MhwMultiStructData.Entry("Unk155", typeof(float)),
                new MhwMultiStructData.Entry("Unk156", typeof(float)),
                new MhwMultiStructData.Entry("Unk157", typeof(float)),
                new MhwMultiStructData.Entry("Unk158", typeof(float)),
                new MhwMultiStructData.Entry("Unk159", typeof(float)),
                new MhwMultiStructData.Entry("Unk160", typeof(float)),
                new MhwMultiStructData.Entry("Unk161", typeof(float)),
                new MhwMultiStructData.Entry("Unk162", typeof(float)),
                new MhwMultiStructData.Entry("Unk163", typeof(float)),
                new MhwMultiStructData.Entry("Unk164", typeof(float)),
                new MhwMultiStructData.Entry("Unk165", typeof(float)),
                new MhwMultiStructData.Entry("Unk166", typeof(float)),
                new MhwMultiStructData.Entry("Unk167", typeof(float)),
                new MhwMultiStructData.Entry("Unk168", typeof(float)),
                new MhwMultiStructData.Entry("Unk169", typeof(float)),
                new MhwMultiStructData.Entry("Unk170", typeof(float)),
                new MhwMultiStructData.Entry("Unk171", typeof(float)),
                new MhwMultiStructData.Entry("Unk172", typeof(float)),
                new MhwMultiStructData.Entry("Unk173", typeof(float)),
                new MhwMultiStructData.Entry("Unk174", typeof(float)),
                new MhwMultiStructData.Entry("Unk175", typeof(float)),
                new MhwMultiStructData.Entry("Unk176", typeof(float)),
                new MhwMultiStructData.Entry("Unk177", typeof(float)),
                new MhwMultiStructData.Entry("Unk178", typeof(float)),
                new MhwMultiStructData.Entry("Unk179", typeof(float)),
                new MhwMultiStructData.Entry("Unk180___s___", typeof(byte)),
                new MhwMultiStructData.Entry("Unk180", typeof(byte)),
                new MhwMultiStructData.Entry("Unk181", typeof(byte)),
                new MhwMultiStructData.Entry("Unk181.1", typeof(byte)),
                new MhwMultiStructData.Entry("Unk182", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk183", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk184", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk185", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk186", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk187", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk188", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk189", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk190", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk191__", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk192", typeof(byte)),
                new MhwMultiStructData.Entry("Unk192.1", typeof(byte)),
                new MhwMultiStructData.Entry("Unk193", typeof(byte)),
                new MhwMultiStructData.Entry("Unk193.1", typeof(byte)),
                new MhwMultiStructData.Entry("Unk194", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk195", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk196", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk197", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk198", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk199", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk200", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk201", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk202", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk203___e___", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk204", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk205", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk206", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk207", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk208", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk209", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk210", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk211", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk212", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk213", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk214", typeof(byte)),
                new MhwMultiStructData.Entry("Unk215", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk216", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk217", typeof(float)),
                new MhwMultiStructData.Entry("Unk218", typeof(ushort)),
                new MhwMultiStructData.Entry("Unk219", typeof(float)),
                new MhwMultiStructData.Entry("Unk220", typeof(float)),
                new MhwMultiStructData.Entry("Unk221", typeof(float)),
                new MhwMultiStructData.Entry("Unk222", typeof(float)),
                new MhwMultiStructData.Entry("Unk223", typeof(float)),
                new MhwMultiStructData.Entry("Unk224", typeof(float)),
                new MhwMultiStructData.Entry("Unk225", typeof(float)),
                new MhwMultiStructData.Entry("Unk226", typeof(float)),
                new MhwMultiStructData.Entry("Unk227", typeof(float)),
                new MhwMultiStructData.Entry("Unk228", typeof(float)),
                new MhwMultiStructData.Entry("Unk229", typeof(float)),
                new MhwMultiStructData.Entry("Unk230", typeof(float)),
                new MhwMultiStructData.Entry("Unk231", typeof(float)),
                new MhwMultiStructData.Entry("Unk232", typeof(float)),
                new MhwMultiStructData.Entry("Unk233", typeof(byte)),
                new MhwMultiStructData.Entry("Unk234", typeof(float)),
                new MhwMultiStructData.Entry("Unk235", typeof(byte)),
                new MhwMultiStructData.Entry("Unk236", typeof(byte)),
                new MhwMultiStructData.Entry("Unk237", typeof(byte)),
                new MhwMultiStructData.Entry("Unk238", typeof(float)),
                new MhwMultiStructData.Entry("Unk239", typeof(float)),
                new MhwMultiStructData.Entry("Unk240", typeof(uint)),
                new MhwMultiStructData.Entry("Unk241", typeof(short))
            }, 1, showVertically: true);

            var unk3 = new MhwMultiStructData.StructData("Unk Struct 3", new List<MhwMultiStructData.Entry> {
                new MhwMultiStructData.Entry("Unk1", typeof(float)),
                new MhwMultiStructData.Entry("Unk2", typeof(float)),
                new MhwMultiStructData.Entry("Unk3", typeof(float)),
                new MhwMultiStructData.Entry("Unk4", typeof(float)),
                new MhwMultiStructData.Entry("Unk5", typeof(float))
            }, 16);

            var unk4 = new MhwMultiStructData.StructData("Unk Struct 4", new List<MhwMultiStructData.Entry> {
                new MhwMultiStructData.Entry("Unk1", typeof(float)),
                new MhwMultiStructData.Entry("Unk2", typeof(uint)),
                new MhwMultiStructData.Entry("Unk3", typeof(float)),
                new MhwMultiStructData.Entry("Unk4", typeof(float)),
                new MhwMultiStructData.Entry("Unk5", typeof(float)),
                new MhwMultiStructData.Entry("Unk6", typeof(float))
            }, 4);

            var p5 = new MhwMultiStructData.StructData("W12p Params (5)", new List<MhwMultiStructData.Entry> {
                new MhwMultiStructData.Entry("Unk242", typeof(float)),
                new MhwMultiStructData.Entry("Unk243", typeof(float)),
                new MhwMultiStructData.Entry("Unk244", typeof(float)),
                new MhwMultiStructData.Entry("Unk245", typeof(float)),
                new MhwMultiStructData.Entry("Unk246", typeof(float)),
                new MhwMultiStructData.Entry("Unk247", typeof(float)),
                new MhwMultiStructData.Entry("Unk248", typeof(float)),
                new MhwMultiStructData.Entry("Unk249", typeof(float)),
                new MhwMultiStructData.Entry("Unk250", typeof(float)),
                new MhwMultiStructData.Entry("Unk251", typeof(float)),
                new MhwMultiStructData.Entry("Unk252", typeof(float)),
                new MhwMultiStructData.Entry("Unk253", typeof(float)),
                new MhwMultiStructData.Entry("Unk254", typeof(float)),
                new MhwMultiStructData.Entry("Unk255", typeof(float)),
                new MhwMultiStructData.Entry("Unk256", typeof(float)),
                new MhwMultiStructData.Entry("Unk257", typeof(float)),
                new MhwMultiStructData.Entry("Unk258", typeof(float)),
                new MhwMultiStructData.Entry("Unk259", typeof(float)),
                new MhwMultiStructData.Entry("Unk260", typeof(float)),
                new MhwMultiStructData.Entry("Unk261", typeof(float)),
                new MhwMultiStructData.Entry("Unk262", typeof(float)),
                new MhwMultiStructData.Entry("Unk263", typeof(float)),
                new MhwMultiStructData.Entry("Unk264", typeof(float)),
                new MhwMultiStructData.Entry("Unk265", typeof(float)),
                new MhwMultiStructData.Entry("Unk266", typeof(float)),
                new MhwMultiStructData.Entry("Unk267", typeof(float)),
                new MhwMultiStructData.Entry("Unk268", typeof(float)),
                new MhwMultiStructData.Entry("Unk269", typeof(float)),
                new MhwMultiStructData.Entry("Unk270", typeof(float)),
                new MhwMultiStructData.Entry("Unk271", typeof(float)),
                new MhwMultiStructData.Entry("Unk272", typeof(float)),
                new MhwMultiStructData.Entry("Unk273", typeof(float)),
                new MhwMultiStructData.Entry("Unk274", typeof(float)),
                new MhwMultiStructData.Entry("Unk275", typeof(float)),
                new MhwMultiStructData.Entry("Close_range_Up_active_range_1", typeof(float)),
                new MhwMultiStructData.Entry("Close_range_Up_active_range_2", typeof(float)),
                new MhwMultiStructData.Entry("Close_range_Up_active_range_3", typeof(float)),
                new MhwMultiStructData.Entry("Close_range_Up_active_range_4", typeof(float)),
                new MhwMultiStructData.Entry("Close_range_Up_Modifier_1", typeof(float)),
                new MhwMultiStructData.Entry("Close_range_Up_Modifier_2", typeof(float)),
                new MhwMultiStructData.Entry("Close_range_Up_Modifier_3", typeof(float)),
                new MhwMultiStructData.Entry("Close_range_Up_Modifier_4", typeof(float)),
                new MhwMultiStructData.Entry("Ranged_Attack_Up_active_distance_1", typeof(float)),
                new MhwMultiStructData.Entry("Ranged_Attack_Up_active_distance_2", typeof(float)),
                new MhwMultiStructData.Entry("Ranged_Attack_Up_active_distance_3", typeof(float)),
                new MhwMultiStructData.Entry("Ranged_Attack_Up_active_distance_4", typeof(float)),
                new MhwMultiStructData.Entry("Ranged_Attack_Up_Modifier_1", typeof(float)),
                new MhwMultiStructData.Entry("Ranged_Attack_Up_Modifier_2", typeof(float)),
                new MhwMultiStructData.Entry("Ranged_Attack_Up_Modifier_3", typeof(float)),
                new MhwMultiStructData.Entry("Ranged_Attack_Up_Modifier_4", typeof(float)),
                new MhwMultiStructData.Entry("Guard Angle (Both Sides)", typeof(float))
            }, 1, showVertically: true);

            var countHolder = new MhwMultiStructData.StructData("Number of Shield Mods Struct", new List<MhwMultiStructData.Entry> {
                new MhwMultiStructData.Entry("Number of Shield Mods", typeof(uint)).Out(out var count)
            }, 1, true);

            var shieldMods = new MhwMultiStructData.StructData("Shield Mods", new List<MhwMultiStructData.Entry> {
                new MhwMultiStructData.Entry("Small", typeof(byte)),
                new MhwMultiStructData.Entry("Medium", typeof(byte)),
                new MhwMultiStructData.Entry("Large", typeof(byte))
            }, canAddRows: true, _010Link: new MhwMultiStructData.ArrayLink(countHolder, count));

            var p6 = new MhwMultiStructData.StructData("W12p Params (6)", new List<MhwMultiStructData.Entry> {
                new MhwMultiStructData.Entry("Unk277", typeof(float)),
                new MhwMultiStructData.Entry("Unk278", typeof(float)),
                new MhwMultiStructData.Entry("Unk279", typeof(float)),
                new MhwMultiStructData.Entry("Unk280", typeof(float)),
                new MhwMultiStructData.Entry("Unk281", typeof(float)),
                new MhwMultiStructData.Entry("Unk282", typeof(float)),
                new MhwMultiStructData.Entry("Unk283", typeof(float)),
                new MhwMultiStructData.Entry("Unk284", typeof(float)),
                new MhwMultiStructData.Entry("Unk285", typeof(float)),
                new MhwMultiStructData.Entry("Unk286", typeof(float))
            }, 1, showVertically: true);

            var unk5 = new MhwMultiStructData.StructData("Unk Struct 5", new List<MhwMultiStructData.Entry> {
                new MhwMultiStructData.Entry("Unk1", typeof(float)),
                new MhwMultiStructData.Entry("Unk2", typeof(float)),
                new MhwMultiStructData.Entry("Unk3", typeof(float)),
                new MhwMultiStructData.Entry("Unk4", typeof(float))
            }, 50);

            baseStructs = new List<MhwMultiStructData.StructData> {
                p1,
                unk1,
                p2,
                guardAnglesMaybe,
                p3,
                unk2,
                p4,
                unk3,
                unk4,
                p5,
                countHolder,
                shieldMods,
                p6,
                unk5
            };
        }

        public MultiStruct Generate() { // .w12p
            var structs = new List<MhwMultiStructData.StructData>();
            structs.AddRange(baseStructs);
            structs.AddRange(new List<MhwMultiStructData.StructData> {
                new MhwMultiStructData.StructData("W12p Params (7)", new List<MhwMultiStructData.Entry> {
                    new MhwMultiStructData.Entry("Unk287", typeof(float)),
                    new MhwMultiStructData.Entry("Unk288", typeof(float)),
                    new MhwMultiStructData.Entry("Unk289", typeof(float)),
                    new MhwMultiStructData.Entry("Unk290", typeof(float)),
                    new MhwMultiStructData.Entry("Unk291", typeof(float)),
                    new MhwMultiStructData.Entry("Unk292", typeof(float))
                }, 1, showVertically: true)
            });

            return new MultiStruct("MHW_Editor.Weapons", "Wp12Param", new MhwMultiStructData(structs, "w12p", EncryptionKeys.FILE_EXT_KEY_LOOKUP[".w12p"]));
        }
    }
}