using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace MHW_Template {
    [SuppressMessage("ReSharper", "StringLiteralTypo")]
    public static class Global {
        public const string CURRENT_GAME_VERSION = "14.0X.XX";
        public static readonly Dictionary<string, string> LANGUAGE_NAME_LOOKUP = new Dictionary<string, string> {
            {"ara", "العربية"},
            {"chS", "简体中文"},
            {"chT", "繁體中文"},
            {"eng", "English"},
            {"fre", "Français"},
            {"ger", "Deutsch"},
            {"ita", "Italiano"},
            {"jpn", "日本語"},
            {"kor", "한국어"},
            {"pol", "Polski"},
            {"ptB", "Português do Brasil"},
            {"rus", "Русский"},
            {"spa", "Español"}
        };
        public static readonly List<string> LANGUAGES = new List<string>(LANGUAGE_NAME_LOOKUP.Keys);
        public static readonly List<string> WEAPONS = new List<string> {
            "bow",
            "c_axe",
            "g_lance",
            "hammer",
            "hbg",
            "l_sword",
            "lance",
            "lbg",
            "rod",
            "s_axe",
            "sword",
            "tachi",
            "w_sword",
            "whistle"
        };
        public static readonly string[] FILE_TYPES = {
            "*.aeq",
            "*.am_dat",
            "*.arm_up",
            "*.ask",
            "*.asp",
            "*.bbtbl",
            "*.ch_dat",
            "*.col",
            "*.cus_otr",
            "*.cus_ou",
            "*.cus_pa",
            "*.cus_par",
            "*.dglt",
            "*.diot",
            "*.dtt_agr",
            "*.dtt_clawc",
            "*.dtt_dif",
            "*.dtt_eda",
            "*.dtt_epg",
            "*.dtt_rsz",
            "*.dtt_sta",
            "*.ecp",
            "*.em104exp",
            "*.em104glt",
            "*.em104iot",
            "*.em104lb",
            "*.em104lbr",
            "*.em104wcd",
            "*.em104wud",
            "*.em117glt",
            "*.em117iot",
            "*.emst",
            "*.em_ss",
            "*.eq_crt",
            "*.eq_cus",
            "*.gcod",
            "*.gip",
            "*.gun_rd",
            "*.gun_sd",
            "*.imk",
            "*.itlist",
            "*.itlot",
            "*.itm",
            "*.kire",
            "*.lbm_base",
            "*.lbm_skill",
            "*.mbd",
            "*.mkex",
            "*.mkit",
            "*.msk",
            "*.mske",
            "*.new_lb",
            "*.new_lbr",
            "*.odr",
            "*.owp_dat",
            "*.oam_dat",
            "*.plfe",
            "*.plip",
            "*.plit",
            "*.plp",
            "*.plsp",
            "*.ransz",
            "*.rem",
            "*.rfur",
            "*.rod_inse",
            "*.sed",
            "*.sgpa",
            "*.shl_tbl",
            "*.skl_dat",
            "*.skl_pt_dat",
            "*.shlp",
            "*.slt",
            "*.srl",
            "*.stmp",
            "*.supp",
            "*.swer",
            "*.swpc",
            "*.swpi",
            "*.swpn",
            "*.trdr",
            "*.trsr",
            "*.w00p",
            "*.w01p",
            "*.w02p",
            "*.w03p",
            "*.w04p",
            "*.w05p",
            "*.w06p",
            "*.w07p",
            "*.w08p",
            "*.w09p",
            "*.w10p",
            "*.w11p",
            "*.w12p",
            "*.w13p",
            "*.wep_glan",
            "*.wep_saxe",
            "*.wep_wsd",
            "*.wep_wsl",
            "*.wp_dat",
            "*.wp_dat_g",
            // Special cases. Leave at the end so they';re obscured from the UI.
            "Block_26.bin"
        };
        public const string ASSETS_ROOT        = @"..\..\..\Assets";
        public const string GENERATED_ROOT     = @"..\..\..\Generated";
        public const string STRUCT_OUTPUT_ROOT = @"..\..\..\Structs";
        public const string _010_OUTPUT_ROOT   = @"..\..\..\010 Templates";
        public const string CHUNK_HASHING_ROOT = @"V:\MHW\IB\For Hashing";
        public const string CHUNK_ROOT         = @"V:\MHW\IB\chunk_combined";
        public const string COMMON_TEXT_ROOT   = CHUNK_ROOT + @"\common\text";
    }
}