namespace MHW_Editor.Gems {
    public static class Skills {
        public const ushort NONE = 0;
        public const ushort POISON_RESISTANCE = 1;
        public const ushort PARALYSIS_RESISTANCE = 2;
        public const ushort SLEEP_RESISTANCE = 3;
        public const ushort STUN_RESISTANCE = 4;
        public const ushort MUCK_RESISTANCE = 5;
        public const ushort BLAST_RESISTANCE = 6;
        public const ushort BLEEDING_RESISTANCE = 7;
        public const ushort IRON_SKIN = 8;
        public const ushort EAR_PLUGS = 11;
        public const ushort WIND_PROOF = 12;
        public const ushort TREMOR_RESISTANCE = 13;
        public const ushort DUNG_MASTER = 14;
        public const ushort EFFLUVIAL_EXPERT = 16;
        public const ushort HEAT_GUARD = 17;
        public const ushort ATTACK_BOOST = 19;
        public const ushort DEFENSE_BOOST = 20;
        public const ushort HEALTH_BOOST = 21;
        public const ushort RECOVERY_UP = 22;
        public const ushort RECOVERY_SPEED = 23;
        public const ushort FIRE_RESISTANCE = 24;
        public const ushort WATER_RESISTANCE = 25;
        public const ushort ICE_RESISTANCE = 26;
        public const ushort THUNDER_RESISTANCE = 27;
        public const ushort DRAGON_RESISTANCE = 28;
        public const ushort BLIGHT_RESISTANCE = 29;
        public const ushort FIRE_ATTACK = 30;
        public const ushort WATER_ATTACK = 31;
        public const ushort ICE_ATTACK = 32;
        public const ushort THUNDER_ATTACK = 33;
        public const ushort DRAGON_ATTACK = 34;
        public const ushort POISON_ATTACK = 35;
        public const ushort PARALYSIS_ATTACK = 36;
        public const ushort SLEEP_ATTACK = 37;
        public const ushort BLAST_ATTACK = 38;
        public const ushort NORMAL_SHOTS = 39;
        public const ushort PIERCING_SHOTS = 40;
        public const ushort SPREAD_POWERSHOTS = 41;
        public const ushort FREE_ELEM_AMMO_UP = 47;
        public const ushort CRITICAL_EYE = 48;
        public const ushort CRITICAL_BOOST = 49;
        public const ushort WEAKNESS_EXPLOIT = 50;
        public const ushort FOCUS = 52;
        public const ushort POWER_PROLONGER = 53;
        public const ushort HANDICRAFT = 54;
        public const ushort CRITICAL_DRAW = 55;
        public const ushort PART_BREAKER = 56;
        public const ushort SLUGGER = 57;
        public const ushort STAMINA_THIEF = 58;
        public const ushort MASTER_MOUNTER = 59;
        public const ushort AIRBORNE = 60;
        public const ushort LATENT_POWER = 61;
        public const ushort AGITATOR = 62;
        public const ushort PEAK_PERFORMANCE = 63;
        public const ushort HEROICS = 64;
        public const ushort FORTIFY = 65;
        public const ushort RESENTMENT = 66;
        public const ushort RESUSCITATE = 67;
        public const ushort HORN_MAESTRO = 68;
        public const ushort CAPACITY_BOOST = 69;
        public const ushort SPECIAL_AMMO_BOOST = 70;
        public const ushort ARTILLERY = 71;
        public const ushort HEAVY_ARTILLERY = 72;
        public const ushort MARATHON_RUNNER = 73;
        public const ushort CONSTITUTION = 74;
        public const ushort LEAP_OF_FAITH = 75;
        public const ushort STAMINA_SURGE = 76;
        public const ushort HUNGER_RESISTANCE = 77;
        public const ushort EVADE_WINDOW = 78;
        public const ushort EVADE_EXTENDER = 79;
        public const ushort GUARD = 80;
        public const ushort QUICK_SHEATH = 81;
        public const ushort WIDE_RANGE = 82;
        public const ushort ITEM_PROLONGER = 83;
        public const ushort FREE_MEAL = 84;
        public const ushort SPEED_EATING = 85;
        public const ushort SPEED_SHARPENING = 86;
        public const ushort BOMBARDIER = 88;
        public const ushort MUSHROOMANCER = 90;
        public const ushort MASTER_FISHER = 91;
        public const ushort BBQ_MASTER = 92;
        public const ushort PRO_TRANSPORTER = 93;
        public const ushort MASTER_GATHERER = 94;
        public const ushort HONEY_HUNTER = 95;
        public const ushort CARVING_PRO = 96;
        public const ushort DIVINE_BLESSING = 97;
        public const ushort PALICO_RALLY = 98;
        public const ushort BOTANIST = 99;
        public const ushort GEOLOGIST = 100;
        public const ushort MAXIMUM_MIGHT = 101;
        public const ushort SLINGER_CAPACITY = 102;
        public const ushort STEALTH = 103;
        public const ushort FLINCH_FREE = 104;
        public const ushort SCOUTFLY_RANGE_UP = 105;
        public const ushort SPEED_CRAWLER = 106;
        public const ushort JUMP_MASTER = 107;
        public const ushort SPOREPUFF_EXPERT = 108;
        public const ushort AQUATIC_EXPERT = 109;
        public const ushort CLIFFHANGER = 111;
        public const ushort BLINDSIDER = 112;
        public const ushort SCHOLAR = 114;
        public const ushort ENTOMOLOGIST = 115;
        public const ushort EFFLUVIA_RESISTANCE = 116;
        public const ushort SCENTHOUND = 117;
        public const ushort FORAGERS_LUCK = 118;
        public const ushort DETECTOR = 119;
        public const ushort TOOL_SPECIALIST = 120;
        public const ushort AFFINITY_SLIDING = 122;
        public const ushort ELDERSEAL_BOOST = 123;
        public const ushort INTIMIDATOR = 124;
        public const ushort ANJANATH_POWER = 125;
        public const ushort NERGIGANTE_HUNGER = 126;
        public const ushort VAAL_HAZAK_VITALITY = 127;
        public const ushort RATHALOS_POWER = 128;
        public const ushort DIABLOS_POWER = 129;
        public const ushort KIRIN_BLESSING = 130;
        public const ushort PINK_RATHIAN_MASTERY = 131;
        public const ushort ANJANATH_WILL = 132;
        public const ushort RATHALOS_MASTERY = 135;
        public const ushort DIABLOS_MASTERY = 136;
        public const ushort KIRIN_FAVOR = 137;
        public const ushort URAGAAN_PROTECTION = 138;
        public const ushort BAZELGEUSE_PROTECTION = 142;
        public const ushort TEOSTRA_TECHNIQUE = 143;
        public const ushort KUSHALA_DAORA_FLIGHT = 144;
        public const ushort XENO_JIIVA_DIVINITY = 145;
        public const ushort ZORAH_MAGDAROS_MASTERY = 147;
        public const ushort HERO_S_PROTECTION = 148;
        public const ushort GUILD_GUIDANCE = 149;
        public const ushort COMMISSION_GUIDANCE = 150;
        public const ushort LEGIANA_BLESSING = 151;
        public const ushort LEGIANA_FAVOR = 152;
        public const ushort ODOGARON_POWER = 153;
        public const ushort ODOGARON_MASTERY = 154;
        public const ushort BOW_CHARGE_PLUS = 155;
        public const ushort MIND_S_EYE_BALLISTICS = 156;
        public const ushort GUARD_UP = 157;
        public const ushort PROTECTIVE_POLISH = 158;
        public const ushort NON_ELEMENTAL_BOOST = 159;
        public const ushort GUTS = 160;
        public const ushort HASTEN_RECOVERY = 161;
        public const ushort RAZOR_SHARP_SPARE_SHOT = 162;
        public const ushort LUNASTRA_FAVOR = 163;

        public static string GetName(ushort skill) {
            switch (skill) {
                case POISON_RESISTANCE: return "Poison Resistance";
                case PARALYSIS_RESISTANCE: return "Paralysis Resistance";
                case SLEEP_RESISTANCE: return "Sleep Resistance";
                case STUN_RESISTANCE: return "Stun Resistance";
                case MUCK_RESISTANCE: return "Muck resistance";
                case BLAST_RESISTANCE: return "Blast Resistance";
                case BLEEDING_RESISTANCE: return "Bleeding Resistance";
                case IRON_SKIN: return "Iron Skin";
                case EAR_PLUGS: return "Ear Plugs";
                case WIND_PROOF: return "Wind Proof";
                case TREMOR_RESISTANCE: return "Tremor Resistance";
                case DUNG_MASTER: return "Dung Master";
                case EFFLUVIAL_EXPERT: return "Effluvial Expert";
                case HEAT_GUARD: return "Heat Guard";
                case ATTACK_BOOST: return "Attack Boost";
                case DEFENSE_BOOST: return "Defense Boost";
                case HEALTH_BOOST: return "Health Boost";
                case RECOVERY_UP: return "Recovery Up";
                case RECOVERY_SPEED: return "Recovery Speed";
                case FIRE_RESISTANCE: return "Fire Resistance";
                case WATER_RESISTANCE: return "Water Resistance";
                case ICE_RESISTANCE: return "Ice resistance";
                case THUNDER_RESISTANCE: return "Thunder Resistance";
                case DRAGON_RESISTANCE: return "Dragon Resistance";
                case BLIGHT_RESISTANCE: return "Blight Resistance";
                case FIRE_ATTACK: return "Fire Attack";
                case WATER_ATTACK: return "Water Attack";
                case ICE_ATTACK: return "Ice Attack";
                case THUNDER_ATTACK: return "Thunder Attack";
                case DRAGON_ATTACK: return "Dragon Attack";
                case POISON_ATTACK: return "Poison Attack";
                case PARALYSIS_ATTACK: return "Paralysis Attack";
                case SLEEP_ATTACK: return "Sleep Attack";
                case BLAST_ATTACK: return "Blast Attack";
                case NORMAL_SHOTS: return "Normal Shots";
                case PIERCING_SHOTS: return "Piercing Shots";
                case SPREAD_POWERSHOTS: return "Spread/Powershots";
                case FREE_ELEM_AMMO_UP: return "Free Elem/Ammo Up";
                case CRITICAL_EYE: return "Critical Eye";
                case CRITICAL_BOOST: return "Critical Boost";
                case WEAKNESS_EXPLOIT: return "Weakness Exploit";
                case FOCUS: return "Focus";
                case POWER_PROLONGER: return "Power Prolonger";
                case HANDICRAFT: return "Handicraft";
                case CRITICAL_DRAW: return "Critical Draw";
                case PART_BREAKER: return "Part Breaker";
                case SLUGGER: return "Slugger";
                case STAMINA_THIEF: return "Stamina Thief";
                case MASTER_MOUNTER: return "Master Mounter";
                case AIRBORNE: return "Airborne";
                case LATENT_POWER: return "Latent Power";
                case AGITATOR: return "Agitator";
                case PEAK_PERFORMANCE: return "Peak Performance";
                case HEROICS: return "Heroics";
                case FORTIFY: return "Fortify";
                case RESENTMENT: return "Resentment";
                case RESUSCITATE: return "Resuscitate";
                case HORN_MAESTRO: return "Horn Maestro";
                case CAPACITY_BOOST: return "Capacity Boost";
                case SPECIAL_AMMO_BOOST: return "Special Ammo Boost";
                case ARTILLERY: return "Artillery";
                case HEAVY_ARTILLERY: return "Heavy Artillery";
                case MARATHON_RUNNER: return "Marathon Runner";
                case CONSTITUTION: return "Constitution";
                case LEAP_OF_FAITH: return "Leap Of Faith";
                case STAMINA_SURGE: return "Stamina Surge";
                case HUNGER_RESISTANCE: return "Hunger Resistance";
                case EVADE_WINDOW: return "Evade Window";
                case EVADE_EXTENDER: return "Evade Extender";
                case GUARD: return "Guard";
                case QUICK_SHEATH: return "Quick Sheath";
                case WIDE_RANGE: return "Wide Range";
                case ITEM_PROLONGER: return "Item Prolonger";
                case FREE_MEAL: return "Free Meal";
                case SPEED_EATING: return "Speed Eating";
                case SPEED_SHARPENING: return "Speed Sharpening";
                case BOMBARDIER: return "Bombardier";
                case MUSHROOMANCER: return "Mushroomancer";
                case MASTER_FISHER: return "Master Fisher";
                case BBQ_MASTER: return "BBQ Master";
                case PRO_TRANSPORTER: return "Pro Transporter";
                case MASTER_GATHERER: return "Master Gatherer";
                case HONEY_HUNTER: return "Honey Hunter";
                case CARVING_PRO: return "Carving Pro";
                case DIVINE_BLESSING: return "Divine Blessing";
                case PALICO_RALLY: return "Palico Rally";
                case BOTANIST: return "Botanist";
                case GEOLOGIST: return "Geologist";
                case MAXIMUM_MIGHT: return "Maximum Might";
                case SLINGER_CAPACITY: return "Slinger Capacity";
                case STEALTH: return "Stealth";
                case FLINCH_FREE: return "Flinch Free";
                case SCOUTFLY_RANGE_UP: return "Scoutfly Range Up";
                case SPEED_CRAWLER: return "Speed Crawler";
                case JUMP_MASTER: return "Jump Master";
                case SPOREPUFF_EXPERT: return "Sporepuff Expert";
                case AQUATIC_EXPERT: return "Aquatic Expert";
                case CLIFFHANGER: return "Cliffhanger";
                case BLINDSIDER: return "Blindsider";
                case SCHOLAR: return "Scholar";
                case ENTOMOLOGIST: return "Entomologist";
                case EFFLUVIA_RESISTANCE: return "Effluvia Resistance";
                case SCENTHOUND: return "Scenthound";
                case FORAGERS_LUCK: return "Foragers Luck";
                case DETECTOR: return "Detector";
                case TOOL_SPECIALIST: return "Tool Specialist";
                case AFFINITY_SLIDING: return "Affinity Sliding";
                case ELDERSEAL_BOOST: return "Elderseal Boost";
                case INTIMIDATOR: return "Intimidator";
                case ANJANATH_POWER: return "Anjanath Power";
                case NERGIGANTE_HUNGER: return "Nergigante Hunger";
                case VAAL_HAZAK_VITALITY: return "Vaal Hazak Vitality";
                case RATHALOS_POWER: return "Rathalos Power";
                case DIABLOS_POWER: return "Diablos Power";
                case KIRIN_BLESSING: return "Kirin Blessing";
                case PINK_RATHIAN_MASTERY: return "Pink Rathian Mastery";
                case ANJANATH_WILL: return "Anjanath Will";
                case RATHALOS_MASTERY: return "Rathalos Mastery";
                case DIABLOS_MASTERY: return "Diablos Mastery";
                case KIRIN_FAVOR: return "Kirin Favor";
                case URAGAAN_PROTECTION: return "Uragaan Protection";
                case BAZELGEUSE_PROTECTION: return "Bazelgeuse Protection";
                case TEOSTRA_TECHNIQUE: return "Teostra Technique";
                case KUSHALA_DAORA_FLIGHT: return "Kushala Daora Flight";
                case XENO_JIIVA_DIVINITY: return "Xeno'Jiiva Divinity";
                case ZORAH_MAGDAROS_MASTERY: return "Zorah Magdaros Mastery";
                case HERO_S_PROTECTION: return "Hero's Protection";
                case GUILD_GUIDANCE: return "Guild Guidance";
                case COMMISSION_GUIDANCE: return "Commission Guidance";
                case LEGIANA_BLESSING: return "Legiana Blessing";
                case LEGIANA_FAVOR: return "Legiana Favor";
                case ODOGARON_POWER: return "Odogaron Power";
                case ODOGARON_MASTERY: return "Odogaron Mastery";
                case BOW_CHARGE_PLUS: return "Bow Charge Plus";
                case MIND_S_EYE_BALLISTICS: return "Mind's Eye / Ballistics";
                case GUARD_UP: return "Guard Up";
                case PROTECTIVE_POLISH: return "Protective Polish";
                case NON_ELEMENTAL_BOOST: return "Non-Elemental Boost";
                case GUTS: return "Guts";
                case HASTEN_RECOVERY: return "Hasten Recovery";
                case RAZOR_SHARP_SPARE_SHOT: return "Razor Sharp/Spare Shot";
                case LUNASTRA_FAVOR: return "Lunastra Favor";
                // If we have nothing set for the value, just convert the value into a string.
                default: return skill.ToString();
            }
        }

        public static ushort ToUShort(string value) {
            switch (value) {
                case "Poison Resistance": return POISON_RESISTANCE;
                case "Paralysis Resistance": return PARALYSIS_RESISTANCE;
                case "Sleep Resistance": return SLEEP_RESISTANCE;
                case "Stun Resistance": return STUN_RESISTANCE;
                case "Muck resistance": return MUCK_RESISTANCE;
                case "Blast Resistance": return BLAST_RESISTANCE;
                case "Bleeding Resistance": return BLEEDING_RESISTANCE;
                case "Iron Skin": return IRON_SKIN;
                case "Ear Plugs": return EAR_PLUGS;
                case "Wind Proof": return WIND_PROOF;
                case "Tremor Resistance": return TREMOR_RESISTANCE;
                case "Dung Master": return DUNG_MASTER;
                case "Effluvial Expert": return EFFLUVIAL_EXPERT;
                case "Heat Guard": return HEAT_GUARD;
                case "Attack Boost": return ATTACK_BOOST;
                case "Defense Boost": return DEFENSE_BOOST;
                case "Health Boost": return HEALTH_BOOST;
                case "Recovery Up": return RECOVERY_UP;
                case "Recovery Speed": return RECOVERY_SPEED;
                case "Fire Resistance": return FIRE_RESISTANCE;
                case "Water Resistance": return WATER_RESISTANCE;
                case "Ice resistance": return ICE_RESISTANCE;
                case "Thunder Resistance": return THUNDER_RESISTANCE;
                case "Dragon Resistance": return DRAGON_RESISTANCE;
                case "Blight Resistance": return BLIGHT_RESISTANCE;
                case "Fire Attack": return FIRE_ATTACK;
                case "Water Attack": return WATER_ATTACK;
                case "Ice Attack": return ICE_ATTACK;
                case "Thunder Attack": return THUNDER_ATTACK;
                case "Dragon Attack": return DRAGON_ATTACK;
                case "Poison Attack": return POISON_ATTACK;
                case "Paralysis Attack": return PARALYSIS_ATTACK;
                case "Sleep Attack": return SLEEP_ATTACK;
                case "Blast Attack": return BLAST_ATTACK;
                case "Normal Shots": return NORMAL_SHOTS;
                case "Piercing Shots": return PIERCING_SHOTS;
                case "Spread/Powershots": return SPREAD_POWERSHOTS;
                case "Free Elem/Ammo Up": return FREE_ELEM_AMMO_UP;
                case "Critical Eye": return CRITICAL_EYE;
                case "Critical Boost": return CRITICAL_BOOST;
                case "Weakness Exploit": return WEAKNESS_EXPLOIT;
                case "Focus": return FOCUS;
                case "Power Prolonger": return POWER_PROLONGER;
                case "Handicraft": return HANDICRAFT;
                case "Critical Draw": return CRITICAL_DRAW;
                case "Part Breaker": return PART_BREAKER;
                case "Slugger": return SLUGGER;
                case "Stamina Thief": return STAMINA_THIEF;
                case "Master Mounter": return MASTER_MOUNTER;
                case "Airborne": return AIRBORNE;
                case "Latent Power": return LATENT_POWER;
                case "Agitator": return AGITATOR;
                case "Peak Performance": return PEAK_PERFORMANCE;
                case "Heroics": return HEROICS;
                case "Fortify": return FORTIFY;
                case "Resentment": return RESENTMENT;
                case "Resuscitate": return RESUSCITATE;
                case "Horn Maestro": return HORN_MAESTRO;
                case "Capacity Boost": return CAPACITY_BOOST;
                case "Special Ammo Boost": return SPECIAL_AMMO_BOOST;
                case "Artillery": return ARTILLERY;
                case "Heavy Artillery": return HEAVY_ARTILLERY;
                case "Marathon Runner": return MARATHON_RUNNER;
                case "Constitution": return CONSTITUTION;
                case "Leap Of Faith": return LEAP_OF_FAITH;
                case "Stamina Surge": return STAMINA_SURGE;
                case "Hunger Resistance": return HUNGER_RESISTANCE;
                case "Evade Window": return EVADE_WINDOW;
                case "Evade Extender": return EVADE_EXTENDER;
                case "Guard": return GUARD;
                case "Quick Sheath": return QUICK_SHEATH;
                case "Wide Range": return WIDE_RANGE;
                case "Item Prolonger": return ITEM_PROLONGER;
                case "Free Meal": return FREE_MEAL;
                case "Speed Eating": return SPEED_EATING;
                case "Speed Sharpening": return SPEED_SHARPENING;
                case "Bombardier": return BOMBARDIER;
                case "Mushroomancer": return MUSHROOMANCER;
                case "Master Fisher": return MASTER_FISHER;
                case "BBQ Master": return BBQ_MASTER;
                case "Pro Transporter": return PRO_TRANSPORTER;
                case "Master Gatherer": return MASTER_GATHERER;
                case "Honey Hunter": return HONEY_HUNTER;
                case "Carving Pro": return CARVING_PRO;
                case "Divine Blessing": return DIVINE_BLESSING;
                case "Palico Rally": return PALICO_RALLY;
                case "Botanist": return BOTANIST;
                case "Geologist": return GEOLOGIST;
                case "Maximum Might": return MAXIMUM_MIGHT;
                case "Slinger Capacity": return SLINGER_CAPACITY;
                case "Stealth": return STEALTH;
                case "Flinch Free": return FLINCH_FREE;
                case "Scoutfly Range Up": return SCOUTFLY_RANGE_UP;
                case "Speed Crawler": return SPEED_CRAWLER;
                case "Jump Master": return JUMP_MASTER;
                case "Sporepuff Expert": return SPOREPUFF_EXPERT;
                case "Aquatic Expert": return AQUATIC_EXPERT;
                case "Cliffhanger": return CLIFFHANGER;
                case "Blindsider": return BLINDSIDER;
                case "Scholar": return SCHOLAR;
                case "Entomologist": return ENTOMOLOGIST;
                case "Effluvia Resistance": return EFFLUVIA_RESISTANCE;
                case "Scenthound": return SCENTHOUND;
                case "Foragers Luck": return FORAGERS_LUCK;
                case "Detector": return DETECTOR;
                case "Tool Specialist": return TOOL_SPECIALIST;
                case "Affinity Sliding": return AFFINITY_SLIDING;
                case "Elderseal Boost": return ELDERSEAL_BOOST;
                case "Intimidator": return INTIMIDATOR;
                case "Anjanath Power": return ANJANATH_POWER;
                case "Nergigante Hunger": return NERGIGANTE_HUNGER;
                case "Vaal Hazak Vitality": return VAAL_HAZAK_VITALITY;
                case "Rathalos Power": return RATHALOS_POWER;
                case "Diablos Power": return DIABLOS_POWER;
                case "Kirin Blessing": return KIRIN_BLESSING;
                case "Pink Rathian Mastery": return PINK_RATHIAN_MASTERY;
                case "Anjanath Will": return ANJANATH_WILL;
                case "Rathalos Mastery": return RATHALOS_MASTERY;
                case "Diablos Mastery": return DIABLOS_MASTERY;
                case "Kirin Favor": return KIRIN_FAVOR;
                case "Uragaan Protection": return URAGAAN_PROTECTION;
                case "Bazelgeuse Protection": return BAZELGEUSE_PROTECTION;
                case "Teostra Technique": return TEOSTRA_TECHNIQUE;
                case "Kushala Daora Flight": return KUSHALA_DAORA_FLIGHT;
                case "Xeno'Jiiva Divinity": return XENO_JIIVA_DIVINITY;
                case "Zorah Magdaros Mastery": return ZORAH_MAGDAROS_MASTERY;
                case "Hero's Protection": return HERO_S_PROTECTION;
                case "Guild Guidance": return GUILD_GUIDANCE;
                case "Commission Guidance": return COMMISSION_GUIDANCE;
                case "Legiana Blessing": return LEGIANA_BLESSING;
                case "Legiana Favor": return LEGIANA_FAVOR;
                case "Odogaron Power": return ODOGARON_POWER;
                case "Odogaron Mastery": return ODOGARON_MASTERY;
                case "Bow Charge Plus": return BOW_CHARGE_PLUS;
                case "Mind's Eye / Ballistics": return MIND_S_EYE_BALLISTICS;
                case "Guard Up": return GUARD_UP;
                case "Protective Polish": return PROTECTIVE_POLISH;
                case "Non-Elemental Boost": return NON_ELEMENTAL_BOOST;
                case "Guts": return GUTS;
                case "Hasten Recovery": return HASTEN_RECOVERY;
                case "Razor Sharp/Spare Shot": return RAZOR_SHARP_SPARE_SHOT;
                case "Lunastra Favor": return LUNASTRA_FAVOR;
                // We don't know the value of the string. In this case the string should be a ushort so just return it.
                default: return ushort.Parse(value);
            }
        }
    }
}