using MHW_Template;

namespace MHW_Editor.PlData {
    // Struct Size: "560"
    // Initial Offset: "0"
    // Unique Id Formula: "0"
    public struct PlMantleParam {
        public float Unk_Unk1; // Offset: 8
        public float Unk_Unk2; // Offset: 12
        public float Unk_Unk3; // Offset: 16
        public float Unk_Unk4; // Offset: 20
        public float Unk_Unk5; // Offset: 24
        public uint Unk_Unk6; // Offset: 28
        public float Unk_Unk7; // Offset: 32
        public float Unk_Unk8; // Offset: 36
        public float Unk_Unk9; // Offset: 40
        public float Ghillie_Mantle_Cooldown; // Offset: 44
        public float Ghillie_Mantle_Duration; // Offset: 48
        public float Ghillie_Mantle_Unk1; // Offset: 52
        public float Ghillie_Mantle_Unk2; // Offset: 56
        public float Temporal_Mantle_Cooldown; // Offset: 60
        public float Temporal_Mantle_Duration; // Offset: 64
        public float Temporal_Mantle_Unk1; // Offset: 68
        public float Temporal_Mantle_Unk2; // Offset: 72
        public float Temporal_Mantle_Unk3; // Offset: 76
        public float Temporal_Mantle_Unk4; // Offset: 80
        public float Temporal_Mantle_Unk5; // Offset: 84
        public float Temporal_Mantle_Unk6; // Offset: 88
        public float Temporal_Mantle_Unk7; // Offset: 92
        public float Temporal_Mantle_Unk8; // Offset: 96
        public float Temporal_Mantle_Unk9; // Offset: 100
        public float Temporal_Mantle_Unk10; // Offset: 104
        public float Temporal_Mantle_Unk11; // Offset: 108
        public float Temporal_Mantle_Unk12; // Offset: 112
        public float Temporal_Mantle_Duration_Decrease_Per_Hit; // Offset: 116
        public float Health_Booster_Cooldown; // Offset: 120
        public float Health_Booster_Duration; // Offset: 124
        public float Health_Booster_Upgraded_Duration; // Offset: 128
        public float Rocksteady_Mantle_Cooldown; // Offset: 132
        public float Rocksteady_Mantle_Duration; // Offset: 136
        public float Rocksteady_Mantle_Unk1; // Offset: 140
        public float Rocksteady_Mantle_Damage_Resist; // Offset: 144
        public float Rocksteady_Mantle_Unk2; // Offset: 148
        public float Challenger_Mantle_Cooldown; // Offset: 152
        public float Challenger_Mantle_Duration; // Offset: 156
        public float Challenger_Mantle_Unk1; // Offset: 160
        public float Challenger_Mantle_Unk2; // Offset: 164
        public float Vitality_Mantle_Cooldown; // Offset: 168
        public float Vitality_Mantle_Duration; // Offset: 172
        public float Vitality_Mantle_Mantle_Health; // Offset: 176
        public float Fireproof_Mantle_Cooldown; // Offset: 180
        public float Fireproof_Mantle_Duration; // Offset: 184
        public float Fireproof_Mantle_Damage_Reduction_; // Offset: 188
        public float Waterproof_Mantle_Cooldown; // Offset: 192
        public float Waterproof_Mantle_Duration; // Offset: 196
        public float Waterproof_Mantle_Damage_Reduction_; // Offset: 200
        public float Iceproof_Mantle_Cooldown; // Offset: 204
        public float Iceproof_Mantle_Duration; // Offset: 208
        public float Iceproof_Mantle_Damage_Reduction_; // Offset: 212
        public float Thunderproof_Mantle_Cooldown; // Offset: 216
        public float Thunderproof_Mantle_Duration; // Offset: 220
        public float Thunderproof_Mantle_Damage_Reduction_; // Offset: 224
        public float Dragonproof_Mantle_Cooldown; // Offset: 228
        public float Dragonproof_Mantle_Duration; // Offset: 232
        public float Dragonproof_Mantle_Damage_Reduction_; // Offset: 236
        public float Dragonproof_Mantle_Dragon_Damage_Multiplier; // Offset: 240
        public float Cleanser_Booster_Cooldown; // Offset: 244
        public float Cleanser_Booster_Duration; // Offset: 248
        public float Cleanser_Booster_Upgraded_Duration; // Offset: 252
        public float Cleanser_Booster_Unk1; // Offset: 256
        public float Cleanser_Booster_Unk2; // Offset: 260
        public float Cleanser_Booster_Unk3; // Offset: 264
        public float Cleanser_Booster_Unk4; // Offset: 268
        public float Glider_Mantle_Cooldown; // Offset: 272
        public float Glider_Mantle_Duration; // Offset: 276
        public float Glider_Mantle_Mount_Multiplier; // Offset: 280
        public float Evasion_Mantle_Cooldown; // Offset: 284
        public float Evasion_Mantle_Duration; // Offset: 288
        public float Evasion_Mantle_Attack_Boost_Duration; // Offset: 292
        public float Evasion_Mantle_Evasion_Multiplier; // Offset: 296
        public float Evasion_Mantle_Unk1; // Offset: 300
        public byte Evasion_Mantle_Unk2; // Offset: 304
        public ushort Evasion_Mantle_Unk3; // Offset: 305
        public ushort Evasion_Mantle_Unk4; // Offset: 307
        public float Evasion_Mantle_Unk5; // Offset: 309
        public ushort Evasion_Mantle_Unk6; // Offset: 313
        public float Impact_Mantle_Cooldown; // Offset: 315
        public float Impact_Mantle_Duration; // Offset: 319
        public float Impact_Mantle_Unk1; // Offset: 323
        public float Impact_Mantle_Unk2; // Offset: 327
        public float Impact_Mantle_Unk3; // Offset: 331
        public float Impact_Mantle_Stun_Weak; // Offset: 335
        public float Impact_Mantle_Stun_Medium; // Offset: 339
        public float Impact_Mantle_Stun_Strong; // Offset: 343
        public float Impact_Mantle_Stun_Extreme; // Offset: 347
        public float Impact_Mantle_Stun_Multiplier; // Offset: 351
        public float Impact_Mantle_Unk4; // Offset: 355
        public float Impact_Mantle_Unk5; // Offset: 359
        public float Impact_Mantle_Unk6; // Offset: 363
        public float Impact_Mantle_Unk7; // Offset: 367
        public float Impact_Mantle_Unk8; // Offset: 371
        public float Impact_Mantle_Unk9; // Offset: 375
        public float Impact_Mantle_Unk10; // Offset: 379
        public float Impact_Mantle_Unk11; // Offset: 383
        public float Apothecary_Mantle_Cooldown; // Offset: 387
        public float Apothecary_Mantle_Duration; // Offset: 391
        public float Apothecary_Mantle_Status_Multiplier_Poison; // Offset: 395
        public float Apothecary_Mantle_Status_Multiplier_Para; // Offset: 399
        public float Apothecary_Mantle_Status_Multiplier_Sleep; // Offset: 403
        public float Apothecary_Mantle_Status_Multiplier_Blast; // Offset: 407
        public float Immunity_Mantle_Cooldown; // Offset: 411
        public float Immunity_Mantle_Duration; // Offset: 415
        public float Affinity_Booster_Cooldown; // Offset: 419
        public float Affinity_Booster_Duration; // Offset: 423
        public float Affinity_Booster_Buff_Duration; // Offset: 427
        public int Affinity_Booster_Buff_Affinity; // Offset: 431
        public float Bandit_Mantle_Cooldown; // Offset: 435
        public float Bandit_Mantle_Duration; // Offset: 439
        public float Bandit_Mantle_Hits_to_Drop_Shiny; // Offset: 443
        public sbyte Bandit_Mantle_Unk1; // Offset: 447
        public sbyte Bandit_Mantle_Unk2; // Offset: 448
        public sbyte Bandit_Mantle_Unk3; // Offset: 449
        public sbyte Bandit_Mantle_Unk4; // Offset: 450
        public sbyte Bandit_Mantle_Unk5; // Offset: 451
        public sbyte Bandit_Mantle_Unk6; // Offset: 452
        public sbyte Bandit_Mantle_Unk7; // Offset: 453
        public sbyte Bandit_Mantle_Unk8; // Offset: 454
        public float Assassin_s_Hood_Cooldown; // Offset: 455
        public float Assassin_s_Hood_Duration; // Offset: 459
        public float Assassin_s_Hood_Sneak_Attack_Multiplier; // Offset: 463
        public float Assassin_s_Hood_Speed_Multiplier_1; // Offset: 467
        public float Assassin_s_Hood_Unk1; // Offset: 471
        public float Assassin_s_Hood_Speed_Multiplier_2; // Offset: 475
        public float Assassin_s_Hood_Speed_Multiplier_3; // Offset: 479
        public float Assassin_s_Hood_Speed_Multiplier_4; // Offset: 483
        public float Assassin_s_Hood_Speed_Multiplier_5; // Offset: 487
        public float Assassin_s_Hood_Unk2; // Offset: 491
        public float Assassin_s_Hood_Unk3; // Offset: 495
        public float Assassin_s_Hood_Unk4; // Offset: 499
        public float Assassin_s_Hood_Unk5; // Offset: 503
        public float Assassin_s_Hood_Unk6; // Offset: 507
        public float Assassin_s_Hood_Unk7; // Offset: 511
        public float Assassin_s_Hood_Unk8; // Offset: 515
        public float Assassin_s_Hood_Unk9; // Offset: 519
        public float Assassin_s_Hood_Unk10; // Offset: 523
        public float Assassin_s_Hood_Unk11; // Offset: 527
        public float Assassin_s_Hood_Unk12; // Offset: 531
        public float Assassin_s_Hood_Unk13; // Offset: 535
        public float Assassin_s_Hood_Unk14; // Offset: 539
        public float Assassin_s_Hood_Unk15; // Offset: 543
        public float Assassin_s_Hood_Unk16; // Offset: 547
    }
}