using MHW_Template;

namespace MHW_Editor.PlData {
    // Struct Size: "20640"
    // Unique Id Formula: "0"
    public struct PlPlayerParam {
        public float Unk1; // Offset: 8
        public float Unk2; // Offset: 12
        public float Unk3; // Offset: 16
        public float Unk4; // Offset: 20
        public float Unk5; // Offset: 24
        public float Unk6; // Offset: 28
        public float Unk7; // Offset: 32
        public float Unk8; // Offset: 36
        public float Unk9; // Offset: 40
        public float Unk10; // Offset: 44
        public float Unk11; // Offset: 48
        public float Unk12; // Offset: 52
        public float Unk13; // Offset: 56
        public float Unk14; // Offset: 60
        public float Unk15; // Offset: 64
        public float Unk16; // Offset: 68
        public float Unk17; // Offset: 72
        public float Unk18; // Offset: 76
        public float Unk19; // Offset: 80
        public float Unk20; // Offset: 84
        public float Unk21; // Offset: 88
        public float Unk22; // Offset: 92
        public float Unk23; // Offset: 96
        public float Unk24; // Offset: 100
        public float Unk25; // Offset: 104
        public float Unk26; // Offset: 108
        public float Unk27; // Offset: 112
        public float Unk28; // Offset: 116
        public float Unk29; // Offset: 120
        public float Unk30; // Offset: 124
        public float Unk31; // Offset: 128
        public float Unk32; // Offset: 132
        public float Unk33; // Offset: 136
        public float Unk34; // Offset: 140
        public float Unk35; // Offset: 144
        public float Unk36; // Offset: 148
        public uint Unk37; // Offset: 152
        public uint Unk38; // Offset: 156
        public float Unk39; // Offset: 160
        public float Unk40; // Offset: 164
        public float Unk41; // Offset: 168
        public float Unk42; // Offset: 172
        public float Unk43; // Offset: 176
        public float Unk44; // Offset: 180
        public float Unk45; // Offset: 184
        public float Unk46; // Offset: 188
        public float Unk47; // Offset: 192
        public float Unk48; // Offset: 196
        public float Unk49; // Offset: 200
        public float Unk50; // Offset: 204
        public float Unk51; // Offset: 208
        public float Unk52; // Offset: 212
        public float Unk53; // Offset: 216
        public float Unk54; // Offset: 220
        public float Unk55; // Offset: 224
        public float Unk56; // Offset: 228
        public float Unk57; // Offset: 232
        public byte Unk58; // Offset: 236
        public ushort Unk59; // Offset: 237
        public ushort Unk60; // Offset: 239
        public float Unk61; // Offset: 241
        public byte Unk62; // Offset: 245
        public ushort Unk63; // Offset: 246
        public ushort Unk64; // Offset: 248
        public ushort Unk65; // Offset: 250
        public float Unk66; // Offset: 252
        public byte _Skipping_ahead_1_; // Offset: 256
        public float Health_Initial_Value; // Offset: 408
        public float Health_Max_Value; // Offset: 412
        public float Health_Damage_Recovery_Rate; // Offset: 416
        public float Health_Damage_Recovery_Wait_Time; // Offset: 420
        public float Health_Damage_Recovery_Interval; // Offset: 424
        public float Health_Damage_Recovery_Value; // Offset: 428
        public float Stamina_Initial_Value; // Offset: 432
        public float Stamina_Max_Value; // Offset: 436
        public float Stamina_Min_Value; // Offset: 440
        public float Stamina_Tired_Value; // Offset: 444
        public float Stamina_Auto_Recover; // Offset: 448
        public float Stamina_Auto_Max_Reduce; // Offset: 452
        public float Stamina_Auto_Max_Reduce_Time; // Offset: 456
        public float Stamina_IB_Unknown; // Offset: 460
        public float Stamina_Escape_Dash_Rate; // Offset: 464
        public float Stamina_Out_of_Battle_Rate; // Offset: 468
        public float Stamina_Reduce_Rate_Limit_Trigger; // Offset: 472
        public float Stamina_Reduce_Rate_Limit_Time; // Offset: 476
        public float Stamina_Mount_Endurance_Rate; // Offset: 480
        public float Stamina_Consumption_Dodge; // Offset: 484
        public float Stamina_Consumption_LS_Counter; // Offset: 488
        public float Stamina_Consumption_Unk1; // Offset: 492
        public float Stamina_Consumption_Unk2; // Offset: 496
        public float Stamina_Consumption_Unk3; // Offset: 500
        public float Stamina_Consumption_Unk4; // Offset: 504
        public float Stamina_Consumption_Bow_Shoot; // Offset: 508
        public float Stamina_Consumption_Unk5; // Offset: 512
        public float Stamina_Consumption_Unk6; // Offset: 516
        public float Stamina_Consumption_Unk7; // Offset: 520
        public float Stamina_Consumption_Bow_Charge_Step; // Offset: 524
        public float Stamina_Consumption_Unk8; // Offset: 528
        public float Stamina_Consumption_IB_Unk9; // Offset: 532
        public float Stamina_Consumption_IB_Unk10; // Offset: 536
        public float Stamina_Consumption_IB_Unk11; // Offset: 540
        public float Stamina_Consumption_IB_Unk12; // Offset: 544
        public float Stamina_Consumption_Unk13; // Offset: 548
        public float Stamina_Consumption_Unk14; // Offset: 552
        public float Stamina_Time_Reduce_mCore_Unk1; // Offset: 556
        public float Stamina_Time_Reduce_mCore_Unk2; // Offset: 560
        public float Stamina_Time_Reduce_mCore_Unk3; // Offset: 564
        public float Stamina_Time_Reduce_mCore_Unk4; // Offset: 568
        public float Stamina_Time_Reduce_mCore_Unk5; // Offset: 572
        public float Stamina_Time_Reduce_mCore_Unk6; // Offset: 576
        public float Stamina_Time_Reduce_mCore_Unk7; // Offset: 580
        public float Stamina_Time_Reduce_mCore_Unk8; // Offset: 584
        public float Stamina_Time_Reduce_mCore_Unk9; // Offset: 588
        public float Stamina_Time_Reduce_mCore_Unk10; // Offset: 592
        public float Stamina_Time_Reduce_mCore_Unk11; // Offset: 596
        public float Stamina_Time_Reduce_mCore_Unk12; // Offset: 600
        public float Stamina_Time_Reduce_mCore_Unk13; // Offset: 604
        public float Stamina_Time_Reduce_mCore_Unk14; // Offset: 608
        public float Stamina_Time_Reduce_mCore_Unk15; // Offset: 612
        public float Stamina_Time_Reduce_mCore_Unk16; // Offset: 616
        public float Stamina_Time_Reduce_mCore_Unk17; // Offset: 620
        public float Stamina_Time_Reduce_mCore_Unk18; // Offset: 624
        public float Mount_Reduce_Stamina_mCore_Unk1; // Offset: 628
        public float Mount_Reduce_Stamina_mCore_Unk2; // Offset: 632
        public float Mount_Life_Reduce_Stamina_mCore_Unk1; // Offset: 636
        public float Mount_Life_Reduce_Stamina_mCore_Unk2; // Offset: 640
        public float Mount_Life_Reduce_Stamina_mCore_Unk3; // Offset: 644
        public float Mount_Life_Reduce_Stamina_mCore_Unk4; // Offset: 648
        public float Unk67; // Offset: 652
        public float Unk68; // Offset: 656
        public float Unk69; // Offset: 660
        public float Quest_Level_HR_Fix_Attack_Rate; // Offset: 664
        public float Quest_Level_MR_Fix_Attack_Rate; // Offset: 668
        public float Critical_Attack_Rate; // Offset: 672
        public float Bad_Critical_Attack_Rate; // Offset: 676
        public byte Sharpness_Recoil_Reduction_; // Offset: 680
        public byte Sharpness_Recoil_Reduction_Value; // Offset: 681
        public float Unk70; // Offset: 682
        public float Unk71; // Offset: 686
        public float Unk72; // Offset: 690
        public float Unk73; // Offset: 694
        public uint Unk74; // Offset: 698
        public float Physical_Attack_Rate_Limit; // Offset: 702
        public float Elemental_Attack_Rate_Limit; // Offset: 706
        public float Condition_Attack_Flat_Limit; // Offset: 710
        public float Bowgun_Elemental_Attack_Rate_Limit; // Offset: 714
        public float Condition_Attack_Rate_Limit; // Offset: 718
        public float Stun_Attack_Rate_Limit; // Offset: 722
        public float Stamina_Attack_Rate_Limit; // Offset: 726
        public float Mount_Attack_Rate_Limit; // Offset: 730
        public float Super_Armor_Stun_Damage_Rate; // Offset: 734
        public float Hyper_Armor_Damage_Rate; // Offset: 738
        public float Hyper_Armor_Stun_Damage_Rate; // Offset: 742
        public float Gunner_Defense_Rate; // Offset: 746
        public byte Gunner_Elemental_Resistance_Bonus; // Offset: 750
        public float _Skipping_ahead_2_; // Offset: 751
    }
}