using MHW_Template;

namespace MHW_Editor.PlData {
    // Struct Size: "20640"
    // Initial Offset: "0"
    // Unique Id Formula: "0"
    public struct PlPlayerParam {
        public float Gravity; // Offset: 8
        public float Gravity_Speed_Rate; // Offset: 12
        public float Unk1; // Offset: 16
        public float Unk2; // Offset: 20
        public float Unk3; // Offset: 24
        public float Unk4; // Offset: 28
        public float Unk5; // Offset: 32
        public float Unk6; // Offset: 36
        public float Unk7; // Offset: 40
        public float Unk8; // Offset: 44
        public float Unk9; // Offset: 48
        public float Unk10; // Offset: 52
        public float Unk11; // Offset: 56
        public float Unk12; // Offset: 60
        public float Unk13; // Offset: 64
        public float Unk14; // Offset: 68
        public float Unk15; // Offset: 72
        public float Unk16; // Offset: 76
        public float Unk17; // Offset: 80
        public float Unk18; // Offset: 84
        public float Unk19; // Offset: 88
        public float Unk20; // Offset: 92
        public float Unk21; // Offset: 96
        public float Unk22; // Offset: 100
        public float Unk23; // Offset: 104
        public float Unk24; // Offset: 108
        public float Unk25; // Offset: 112
        public float Unk26; // Offset: 116
        public float Unk27; // Offset: 120
        public float Unk28; // Offset: 124
        public float Unk29; // Offset: 128
        public float Unk30; // Offset: 132
        public float Unk31; // Offset: 136
        public float Unk32; // Offset: 140
        public float Unk33; // Offset: 144
        public float Unk34; // Offset: 148
        public uint Unk35; // Offset: 152
        public uint Unk36; // Offset: 156
        public float Unk37; // Offset: 160
        public float Unk38; // Offset: 164
        public float Unk39; // Offset: 168
        public float Unk40; // Offset: 172
        public float Unk41; // Offset: 176
        public float Unk42; // Offset: 180
        public float Unk43; // Offset: 184
        public float Unk44; // Offset: 188
        public float Unk45; // Offset: 192
        public float Unk46; // Offset: 196
        public float Unk47; // Offset: 200
        public float Unk48; // Offset: 204
        public float Unk49; // Offset: 208
        public float Unk50; // Offset: 212
        public float Unk51; // Offset: 216
        public float Unk52; // Offset: 220
        public float Unk53; // Offset: 224
        public float Unk54; // Offset: 228
        public float Unk55; // Offset: 232
        public byte Unk56; // Offset: 236
        public ushort Unk57; // Offset: 237
        public ushort Unk58; // Offset: 239
        public float Unk59; // Offset: 241
        public byte Unk60; // Offset: 245
        public ushort Unk61; // Offset: 246
        public ushort Unk62; // Offset: 248
        public ushort Unk63; // Offset: 250
        public float Unk64; // Offset: 252
        public float Health_Initial_Value; // Offset: 408
        public float Health_Max_Value; // Offset: 412
        public float Health_Damage_Recovery_Rate; // Offset: 416
        public float Health_Damage_Recovery_Wait_Time; // Offset: 420
        public float Health_Damage_Recovery_Interval; // Offset: 424
        public float Health_Damage_Recovery_Value; // Offset: 428
        public float Stamina_Initial_Value; // Offset: 432
        public float Stamina_Max_Value; // Offset: 436
        public float Stamina_Min_Value; // Offset: 440
        public float Stamina_Tired_Value; // Offset: 444
        public float Stamina_Auto_Recover; // Offset: 448
        public float Stamina_Auto_Max_Reduce; // Offset: 452
        public float Stamina_Auto_Max_Reduce_Time; // Offset: 456
        public float Stamina_IB_Unknown; // Offset: 460
        public float Stamina_Escape_Dash_Rate; // Offset: 464
        public float Stamina_Out_of_Battle_Rate; // Offset: 468
        public float Stamina_Reduce_Rate_Limit_Trigger; // Offset: 472
        public float Stamina_Reduce_Rate_Limit_Time; // Offset: 476
        public float Stamina_Mount_Endurance_Rate; // Offset: 480
        public float Stamina_Consumption_Dodge; // Offset: 484
        public float Stamina_Consumption_LS_Counter; // Offset: 488
        public float Stamina_Consumption_Unk1; // Offset: 492
        public float Stamina_Consumption_Unk2; // Offset: 496
        public float Stamina_Consumption_Unk3; // Offset: 500
        public float Stamina_Consumption_Unk4; // Offset: 504
        public float Stamina_Consumption_Bow_Shoot; // Offset: 508
        public float Stamina_Consumption_Unk5; // Offset: 512
        public float Stamina_Consumption_Unk6; // Offset: 516
        public float Stamina_Consumption_Unk7; // Offset: 520
        public float Stamina_Consumption_Bow_Charge_Step; // Offset: 524
        public float Stamina_Consumption_Unk8; // Offset: 528
        public float Stamina_Consumption_IB_Unk9; // Offset: 532
        public float Stamina_Consumption_IB_Unk10; // Offset: 536
        public float Stamina_Consumption_IB_Unk11; // Offset: 540
        public float Stamina_Consumption_IB_Unk12; // Offset: 544
        public float Stamina_Consumption_Unk13; // Offset: 548
        public float Stamina_Consumption_Unk14; // Offset: 552
        public float Stamina_Time_Reduce_mCore_Unk1; // Offset: 556
        public float Stamina_Time_Reduce_mCore_Unk2; // Offset: 560
        public float Stamina_Time_Reduce_mCore_Unk3; // Offset: 564
        public float Stamina_Time_Reduce_mCore_Unk4; // Offset: 568
        public float Stamina_Time_Reduce_mCore_Unk5; // Offset: 572
        public float Stamina_Time_Reduce_mCore_Unk6; // Offset: 576
        public float Stamina_Time_Reduce_mCore_Unk7; // Offset: 580
        public float Stamina_Time_Reduce_mCore_Unk8; // Offset: 584
        public float Stamina_Time_Reduce_mCore_Lance_s_Power_Guard; // Offset: 588
        public float Stamina_Time_Reduce_mCore_Unk9; // Offset: 592
        public float Stamina_Time_Reduce_mCore_Unk10; // Offset: 596
        public float Stamina_Time_Reduce_mCore_Clutch_Counter; // Offset: 600
        public float Stamina_Time_Reduce_mCore_Unk11; // Offset: 604
        public float Stamina_Time_Reduce_mCore_Unk12; // Offset: 608
        public float Stamina_Time_Reduce_mCore_Unk13; // Offset: 612
        public float Stamina_Time_Reduce_mCore_Unk14; // Offset: 616
        public float Stamina_Time_Reduce_mCore_Unk15; // Offset: 620
        public float Stamina_Time_Reduce_mCore_Unk16; // Offset: 624
        public float Mount_Reduce_Stamina_mCore_Unk1; // Offset: 628
        public float Mount_Reduce_Stamina_mCore_Unk2; // Offset: 632
        public float Mount_Life_Reduce_Stamina_mCore_Unk1; // Offset: 636
        public float Mount_Life_Reduce_Stamina_mCore_Unk2; // Offset: 640
        public float Mount_Life_Reduce_Stamina_mCore_Unk3; // Offset: 644
        public float Mount_Life_Reduce_Stamina_mCore_Unk4; // Offset: 648
        public float Unk65; // Offset: 652
        public float Unk66; // Offset: 656
        public float Unk67; // Offset: 660
        public float Explosive_HR_Fixed_Attack_Rate; // Offset: 664
        public float Explosive_MR_Fixed_Attack_Rate; // Offset: 668
        public float Critical_Attack_Rate; // Offset: 672
        public float Bad_Critical_Attack_Rate; // Offset: 676
        public byte Sharpness_Recoil_Reduction_; // Offset: 680
        public byte Sharpness_Recoil_Reduction_Value; // Offset: 681
        public float Unk68; // Offset: 682
        public float Unk69; // Offset: 686
        public float Unk70; // Offset: 690
        public float Unk71; // Offset: 694
        public uint Unk72; // Offset: 698
        public float Physical_Attack_Rate_Limit; // Offset: 702
        public float Elemental_Attack_Rate_Limit; // Offset: 706
        public float Condition_Elemental_Attack_Flat_Limit; // Offset: 710
        public float Bowgun_Elemental_Attack_Rate_Limit; // Offset: 714
        public float Condition_Attack_Rate_Limit; // Offset: 718
        public float Stun_Attack_Rate_Limit; // Offset: 722
        public float Stamina_Attack_Rate_Limit; // Offset: 726
        public float Mount_Attack_Rate_Limit; // Offset: 730
        public float Super_Armor_Stun_Damage_Rate; // Offset: 734
        public float Hyper_Armor_Damage_Rate; // Offset: 738
        public float Hyper_Armor_Stun_Damage_Rate; // Offset: 742
        public float Gunner_Defense_Rate; // Offset: 746
        public byte Gunner_Elemental_Resistance_Bonus; // Offset: 750
        public float Lava_Damage_Interval_Time; // Offset: 751
        public float Lava_Damage_Damage; // Offset: 755
        public float Acid_Damage_Interval_Time; // Offset: 759
        public float Acid_Damage_Damage; // Offset: 763
        public float Dodge_IFrames_Normal_Evasion_0; // Offset: 1157
        public float Dodge_IFrames_Normal_Evasion_1; // Offset: 1161
        public float Dodge_IFrames_Normal_Evasion_2; // Offset: 1165
        public float Dodge_IFrames_Normal_Evasion_3; // Offset: 1169
        public float Dodge_IFrames_Normal_Evasion_4; // Offset: 1173
        public float Dodge_IFrames_Normal_Evasion_5; // Offset: 1177
        public float Dodge_IFrames_Normal_Evasion_Mantle; // Offset: 1181
        public float Dodge_IFrames_Step_Evasion_0; // Offset: 1185
        public float Dodge_IFrames_Step_Evasion_1; // Offset: 1189
        public float Dodge_IFrames_Step_Evasion_2; // Offset: 1193
        public float Dodge_IFrames_Step_Evasion_3; // Offset: 1197
        public float Dodge_IFrames_Step_Evasion_4; // Offset: 1201
        public float Dodge_IFrames_Step_Evasion_5; // Offset: 1205
        public float Dodge_IFrames_Step_Evasion_Mantle; // Offset: 1209
        public float Dodge_IFrames_Sword_Shield_Back_Step_Evasion_0; // Offset: 1213
        public float Dodge_IFrames_Sword_Shield_Back_Step_Evasion_1; // Offset: 1217
        public float Dodge_IFrames_Sword_Shield_Back_Step_Evasion_2; // Offset: 1221
        public float Dodge_IFrames_Sword_Shield_Back_Step_Evasion_3; // Offset: 1225
        public float Dodge_IFrames_Sword_Shield_Back_Step_Evasion_4; // Offset: 1229
        public float Dodge_IFrames_Sword_Shield_Back_Step_Evasion_5; // Offset: 1233
        public float Dodge_IFrames_Sword_Shield_Back_Step_Evasion_Mantle; // Offset: 1237
        public float Dodge_IFrames_Dual_Blades_Demon_Mode_Step_Evasion_0; // Offset: 1241
        public float Dodge_IFrames_Dual_Blades_Demon_Mode_Step_Evasion_1; // Offset: 1245
        public float Dodge_IFrames_Dual_Blades_Demon_Mode_Step_Evasion_2; // Offset: 1249
        public float Dodge_IFrames_Dual_Blades_Demon_Mode_Step_Evasion_3; // Offset: 1253
        public float Dodge_IFrames_Dual_Blades_Demon_Mode_Step_Evasion_4; // Offset: 1257
        public float Dodge_IFrames_Dual_Blades_Demon_Mode_Step_Evasion_5; // Offset: 1261
        public float Dodge_IFrames_Dual_Blades_Demon_Mode_Step_Evasion_Mantle; // Offset: 1265
        public float Dodge_IFrames_Long_Sword_Counter_Evasion_0; // Offset: 1269
        public float Dodge_IFrames_Long_Sword_Counter_Evasion_1; // Offset: 1273
        public float Dodge_IFrames_Long_Sword_Counter_Evasion_2; // Offset: 1277
        public float Dodge_IFrames_Long_Sword_Counter_Evasion_3; // Offset: 1281
        public float Dodge_IFrames_Long_Sword_Counter_Evasion_4; // Offset: 1285
        public float Dodge_IFrames_Long_Sword_Counter_Evasion_5; // Offset: 1289
        public float Dodge_IFrames_Long_Sword_Counter_Evasion_Mantle; // Offset: 1293
        public float Dodge_IFrames_Bow_Charge_Step_Evasion_0; // Offset: 1297
        public float Dodge_IFrames_Bow_Charge_Step_Evasion_1; // Offset: 1301
        public float Dodge_IFrames_Bow_Charge_Step_Evasion_2; // Offset: 1305
        public float Dodge_IFrames_Bow_Charge_Step_Evasion_3; // Offset: 1309
        public float Dodge_IFrames_Bow_Charge_Step_Evasion_4; // Offset: 1313
        public float Dodge_IFrames_Bow_Charge_Step_Evasion_5; // Offset: 1317
        public float Dodge_IFrames_Bow_Charge_Step_Evasion_Mantle; // Offset: 1321
        public float Dodge_IFrames_HBG_Roll_Dodge_Evasion_0; // Offset: 1325
        public float Dodge_IFrames_HBG_Roll_Dodge_Evasion_1; // Offset: 1329
        public float Dodge_IFrames_HBG_Roll_Dodge_Evasion_2; // Offset: 1333
        public float Dodge_IFrames_HBG_Roll_Dodge_Evasion_3; // Offset: 1337
        public float Dodge_IFrames_HBG_Roll_Dodge_Evasion_4; // Offset: 1341
        public float Dodge_IFrames_HBG_Roll_Dodge_Evasion_5; // Offset: 1345
        public float Dodge_IFrames_HBG_Roll_Dodge_Evasion_Mantle; // Offset: 1349
        public float Dodge_IFrames_LBG_Side_Dodge_Evasion_0; // Offset: 1353
        public float Dodge_IFrames_LBG_Side_Dodge_Evasion_1; // Offset: 1357
        public float Dodge_IFrames_LBG_Side_Dodge_Evasion_2; // Offset: 1361
        public float Dodge_IFrames_LBG_Side_Dodge_Evasion_3; // Offset: 1365
        public float Dodge_IFrames_LBG_Side_Dodge_Evasion_4; // Offset: 1369
        public float Dodge_IFrames_LBG_Side_Dodge_Evasion_5; // Offset: 1373
        public float Dodge_IFrames_LBG_Side_Dodge_Evasion_Mantle; // Offset: 1377
        public float Dodge_IFrames_Dual_Blades_Demon_Mode_Slinger_Evade_Evasion_0; // Offset: 1381
        public float Dodge_IFrames_Dual_Blades_Demon_Mode_Slinger_Evade_Evasion_1; // Offset: 1385
        public float Dodge_IFrames_Dual_Blades_Demon_Mode_Slinger_Evade_Evasion_2; // Offset: 1389
        public float Dodge_IFrames_Dual_Blades_Demon_Mode_Slinger_Evade_Evasion_3; // Offset: 1393
        public float Dodge_IFrames_Dual_Blades_Demon_Mode_Slinger_Evade_Evasion_4; // Offset: 1397
        public float Dodge_IFrames_Dual_Blades_Demon_Mode_Slinger_Evade_Evasion_5; // Offset: 1401
        public float Dodge_IFrames_Dual_Blades_Demon_Mode_Slinger_Evade_Evasion_Mantle; // Offset: 1405
        public float Dodge_IFrames_Dual_Blades_Slinger_Evade_Evasion_0; // Offset: 1409
        public float Dodge_IFrames_Dual_Blades_Slinger_Evade_Evasion_1; // Offset: 1413
        public float Dodge_IFrames_Dual_Blades_Slinger_Evade_Evasion_2; // Offset: 1417
        public float Dodge_IFrames_Dual_Blades_Slinger_Evade_Evasion_3; // Offset: 1421
        public float Dodge_IFrames_Dual_Blades_Slinger_Evade_Evasion_4; // Offset: 1425
        public float Dodge_IFrames_Dual_Blades_Slinger_Evade_Evasion_5; // Offset: 1429
        public float Dodge_IFrames_Dual_Blades_Slinger_Evade_Evasion_Mantle; // Offset: 1433
        public float Evade_Normal_Distance_1; // Offset: 1437
        public float Evade_Normal_Distance_2; // Offset: 1441
        public float Evade_Normal_Distance_3; // Offset: 1445
        public float Evade_Step_Distance_1; // Offset: 1449
        public float Evade_Step_Distance_2; // Offset: 1453
        public float Evade_Step_Distance_3; // Offset: 1457
        public float Evade_Sword_Shield_Back_Step_Distance_1; // Offset: 1461
        public float Evade_Sword_Shield_Back_Step_Distance_2; // Offset: 1465
        public float Evade_Sword_Shield_Back_Step_Distance_3; // Offset: 1469
        public float Evade_Dual_Blades_DemonMode_Step_Distance_1; // Offset: 1473
        public float Evade_Dual_Blades_DemonMode_Step_Distance_2; // Offset: 1477
        public float Evade_Dual_Blades_DemonMode_Step_Distance_3; // Offset: 1481
        public float Evade_Long_Sword_Counter_Distance_1; // Offset: 1485
        public float Evade_Long_Sword_Counter_Distance_2; // Offset: 1489
        public float Evade_Long_Sword_Counter_Distance_3; // Offset: 1493
        public float Evade_Insect_Glaive_Air_Dodge_Distance_1; // Offset: 1497
        public float Evade_Insect_Glaive_Air_Dodge_Distance_2; // Offset: 1501
        public float Evade_Insect_Glaive_Air_Dodge_Distance_3; // Offset: 1505
        public float Evade_Bow_Charge_Step_Distance_1; // Offset: 1509
        public float Evade_Bow_Charge_Step_Distance_2; // Offset: 1513
        public float Evade_Bow_Charge_Step_Distance_3; // Offset: 1517
        public float Evade_HBG_Roll_Dodge_Distance_1; // Offset: 1521
        public float Evade_HBG_Roll_Dodge_Distance_2; // Offset: 1525
        public float Evade_HBG_Roll_Dodge_Distance_3; // Offset: 1529
        public float Evade_LBG_Side_Dodge_Distance_1; // Offset: 1533
        public float Evade_LBG_Side_Dodge_Distance_2; // Offset: 1537
        public float Evade_LBG_Side_Dodge_Distance_3; // Offset: 1541
        public float Evade_Dual_Blades_Demon_Mode_Slinger_Evade_Distance_1; // Offset: 1545
        public float Evade_Dual_Blades_Demon_Mode_Slinger_Evade_Distance_2; // Offset: 1549
        public float Evade_Dual_Blades_Demon_Mode_Slinger_Evade_Distance_3; // Offset: 1553
        public float Evade_Dual_Blades_Slinger_Evade_Distance_1; // Offset: 1557
        public float Evade_Dual_Blades_Slinger_Evade_Distance_2; // Offset: 1561
        public float Evade_Dual_Blades_Slinger_Evade_Distance_3; // Offset: 1565
        public byte Wp_HR_Augment_Attack_Bonus_1_; // Offset: 8583
        public byte Wp_HR_Augment_Attack_Bonus_2_; // Offset: 8584
        public byte Wp_HR_Augment_Attack_Bonus_3_; // Offset: 8585
        public byte Wp_HR_Augment_Critical_Bonus_1_; // Offset: 8586
        public byte Wp_HR_Augment_Critical_Bonus_2_; // Offset: 8587
        public byte Wp_HR_Augment_Critical_Bonus_3_; // Offset: 8588
        public byte Wp_HR_Augment_Defense_Bonus_1_; // Offset: 8589
        public byte Wp_HR_Augment_Defense_Bonus_2_; // Offset: 8590
        public byte Wp_HR_Augment_Defense_Bonus_3_; // Offset: 8591
        public byte Wp_HR_Augment_Defense_Divine_Blessing_Chance_1_; // Offset: 8592
        public byte Wp_HR_Augment_Defense_Divine_Blessing_Chance_2_; // Offset: 8593
        public byte Wp_HR_Augment_Defense_Divine_Blessing_Chance_3_; // Offset: 8594
        public float Wp_HR_Augment_Defense_Divine_Blessing_Reduction_1_; // Offset: 8595
        public float Wp_HR_Augment_Defense_Divine_Blessing_Reduction_2_; // Offset: 8599
        public float Wp_HR_Augment_Defense_Divine_Blessing_Reduction_3_; // Offset: 8603
        public float Wp_HR_Augment_Defense_Heal_Damage_Rate_1_; // Offset: 8607
        public float Wp_HR_Augment_Defense_Heal_Damage_Rate_2_; // Offset: 8611
        public float Wp_HR_Augment_Defense_Heal_Damage_Rate_3_; // Offset: 8615
        public float Wp_HR_Augment_IB_Unk; // Offset: 8619
        public float Wp_HR_Augment_Lifesteal_Cooldown; // Offset: 8623
        public byte Wp_MR_Augment_Attack_Bonus_1_; // Offset: 8627
        public byte Wp_MR_Augment_Attack_Bonus_2_; // Offset: 8628
        public byte Wp_MR_Augment_Attack_Bonus_3_; // Offset: 8629
        public byte Wp_MR_Augment_Attack_Bonus_4_; // Offset: 8630
        public byte Wp_MR_Augment_Critical_Bonus_1_; // Offset: 8631
        public byte Wp_MR_Augment_Critical_Bonus_2_; // Offset: 8632
        public byte Wp_MR_Augment_Critical_Bonus_3_; // Offset: 8633
        public byte Wp_MR_Augment_Critical_Bonus_4_; // Offset: 8634
        public byte Wp_MR_Augment_Defense_Bonus_1_; // Offset: 8635
        public byte Wp_MR_Augment_Defense_Bonus_2_; // Offset: 8636
        public byte Wp_MR_Augment_Defense_Bonus_3_; // Offset: 8637
        public byte Wp_MR_Augment_Defense_Bonus_4_; // Offset: 8638
        public byte Wp_MR_Augment_Defense_Divine_Blessing_Chance_1_; // Offset: 8639
        public byte Wp_MR_Augment_Defense_Divine_Blessing_Chance_2_; // Offset: 8640
        public byte Wp_MR_Augment_Defense_Divine_Blessing_Chance_3_; // Offset: 8641
        public byte Wp_MR_Augment_Defense_Divine_Blessing_Chance_4_; // Offset: 8642
        public float Wp_MR_Augment_Defense_Divine_Blessing_Reduction_1_; // Offset: 8643
        public float Wp_MR_Augment_Defense_Divine_Blessing_Reduction_2_; // Offset: 8647
        public float Wp_MR_Augment_Defense_Divine_Blessing_Reduction_3_; // Offset: 8651
        public float Wp_MR_Augment_Defense_Divine_Blessing_Reduction_4_; // Offset: 8655
        public float Wp_MR_Augment_Health_Percent_1_; // Offset: 8659
        public float Wp_MR_Augment_Health_Percent_2_; // Offset: 8663
        public float Wp_MR_Augment_Health_Percent_3_; // Offset: 8667
        public float Wp_MR_Augment_Health_Percent_4_; // Offset: 8671
        public float IB_Unk1; // Offset: 8675
        public float Wp_MR_Augment_Lifesteal_Cooldown; // Offset: 8679
        public byte Wp_MR_Augment_Element_1_; // Offset: 8683
        public byte Wp_MR_Augment_Element_2_; // Offset: 8684
        public byte Wp_MR_Augment_Element_3_; // Offset: 8685
        public byte Wp_MR_Augment_Element_4_; // Offset: 8686
        public byte Wp_MR_Augment_Bowgun_Element_Status_Ammo_Element_Bonus_1_; // Offset: 8687
        public byte Wp_MR_Augment_Bowgun_Element_Status_Ammo_Element_Bonus_2_; // Offset: 8688
        public byte Wp_MR_Augment_Bowgun_Element_Status_Ammo_Element_Bonus_3_; // Offset: 8689
        public byte Wp_MR_Augment_Bowgun_Element_Status_Ammo_Element_Bonus_4_; // Offset: 8690
        public byte Wp_MR_Augment_Bowgun_Element_Status_Ammo_Status_Bonus_1_; // Offset: 8691
        public byte Wp_MR_Augment_Bowgun_Element_Status_Ammo_Status_Bonus_2_; // Offset: 8692
        public byte Wp_MR_Augment_Bowgun_Element_Status_Ammo_Status_Bonus_3_; // Offset: 8693
        public byte Wp_MR_Augment_Bowgun_Element_Status_Ammo_Status_Bonus_4_; // Offset: 8694
        public float Wp_MR_Augment_Great_Sword_Elemental_Multiplier; // Offset: 8695
        public float Wp_MR_Augment_Sword_Shield_Elemental_Multiplier; // Offset: 8699
        public float Wp_MR_Augment_Dual_Blades_Elemental_Multiplier; // Offset: 8703
        public float Wp_MR_Augment_Long_Sword_Elemental_Multiplier; // Offset: 8707
        public float Wp_MR_Augment_Hammer_Elemental_Multiplier; // Offset: 8711
        public float Wp_MR_Augment_Hunting_Horn_Elemental_Multiplier; // Offset: 8715
        public float Wp_MR_Augment_Lance_Elemental_Multiplier; // Offset: 8719
        public float Wp_MR_Augment_Gunlance_Elemental_Multiplier; // Offset: 8723
        public float Wp_MR_Augment_Switch_Axe_Elemental_Multiplier; // Offset: 8727
        public float Wp_MR_Augment_Charge_Blade_Elemental_Multiplier; // Offset: 8731
        public float Wp_MR_Augment_Insect_Glaive_Elemental_Multiplier; // Offset: 8735
        public float Wp_MR_Augment_Bow_Elemental_Multiplier; // Offset: 8739
        public float Wp_MR_Augment_HBG_Elemental_Multiplier; // Offset: 8743
        public float Wp_MR_Augment_LBG_Elemental_Multiplier; // Offset: 8747
        public float Wp_MR_Augment_Bow_Coating_Status_Multiplier_1_; // Offset: 8751
        public float Wp_MR_Augment_Bow_Coating_Status_Multiplier_2_; // Offset: 8755
        public float Wp_MR_Augment_Bow_Coating_Status_Multiplier_3_; // Offset: 8759
        public float Wp_MR_Augment_Bow_Coating_Status_Multiplier_4_; // Offset: 8763
        public byte Max_Slinger_Capacity_Stone; // Offset: 9357
        public byte Max_Slinger_Capacity_Redpit; // Offset: 9358
        public byte Max_Slinger_Capacity_Brightmoss; // Offset: 9359
        public byte Max_Slinger_Capacity_Scatternut; // Offset: 9360
        public byte Max_Slinger_Capacity_Unk_1; // Offset: 9361
        public byte Max_Slinger_Capacity_Unk_2; // Offset: 9362
        public byte Max_Slinger_Capacity_Unk_3; // Offset: 9363
        public byte Max_Slinger_Capacity_Unk_4; // Offset: 9364
        public byte Max_Slinger_Capacity_Unk_5; // Offset: 9365
        public byte Max_Slinger_Capacity_Torch_Pod; // Offset: 9366
        public byte Max_Slinger_Capacity_Unk_6; // Offset: 9367
        public byte Max_Slinger_Capacity_Unk_7; // Offset: 9368
        public byte Max_Slinger_Capacity_Unk_8; // Offset: 9369
        public byte Max_Slinger_Capacity_Unk_9; // Offset: 9370
        public byte Max_Slinger_Capacity_Bomb_Pod; // Offset: 9371
        public byte Max_Slinger_Capacity_Piercing_Pod; // Offset: 9372
        public byte Max_Slinger_Capacity_Slinger_Thorn; // Offset: 9373
        public byte Max_Slinger_Capacity_Dragon_Pod; // Offset: 9374
        public byte Max_Slinger_Capacity_Unk_10; // Offset: 9375
        public byte Max_Slinger_Capacity_Unk_11; // Offset: 9376
        public byte Max_Slinger_Capacity_Unk_12; // Offset: 9377
        public byte Max_Slinger_Capacity_Unk_13; // Offset: 9378
        public byte Max_Slinger_Capacity_Unk_14; // Offset: 9379
        public byte Max_Slinger_Capacity_Unk_15; // Offset: 9380
        public byte Max_Slinger_Capacity_Unk_16; // Offset: 9381
        public byte Max_Slinger_Capacity_Unk_17; // Offset: 9382
        public byte Max_Slinger_Capacity_Crystalburst; // Offset: 9383
        public byte Max_Slinger_Capacity_Puddle_Pod; // Offset: 9384
        public byte Max_Slinger_Capacity_Unk_18; // Offset: 9385
        public byte Max_Slinger_Capacity_Unk_19; // Offset: 9386
        public byte Max_Slinger_Capacity_Unk_20; // Offset: 9387
        public float Gesture_Dragoon_Jump_Loop_Time; // Offset: 17853
        public float Gesture_Dragoon_Jump_Meteor_Start; // Offset: 17857
        public float Gesture_Dragoon_Jump_Meteor_Duration; // Offset: 17861
    }
}