using MHW_Template;

namespace MHW_Editor.PlData {
    // Struct Size: "2256"
    // Initial Offset: "0"
    // Unique Id Formula: "0"
    public struct PlSkillParam {
        public float Speed_Eating_1_Drink_Motion_Speed; // Offset: 8
        public float Speed_Eating_2_Drink_Motion_Speed; // Offset: 12
        public float Speed_Eating_3_Drink_Motion_Speed; // Offset: 16
        public float Speed_Eating_1_Drink_End_Frame; // Offset: 20
        public float Speed_Eating_2_Drink_End_Frame; // Offset: 24
        public float Speed_Eating_3_Drink_End_Frame; // Offset: 28
        public float Speed_Eating_1_Heal_Speed_Rate; // Offset: 32
        public float Speed_Eating_2_Heal_Speed_Rate; // Offset: 36
        public float Speed_Eating_3_Heal_Speed_Rate; // Offset: 40
        public float Speed_Eating_1_Meat_Motion_Speed; // Offset: 44
        public float Speed_Eating_2_Meat_Motion_Speed; // Offset: 48
        public float Speed_Eating_3_Meat_Motion_Speed; // Offset: 52
        public byte Speed_Eating_1_Meat_Loop_Count; // Offset: 56
        public byte Speed_Eating_2_Meat_Loop_Count; // Offset: 57
        public byte Speed_Eating_3_Meat_Loop_Count; // Offset: 58
        public float Speed_Eating_1_2_3_Meat_End_Frame; // Offset: 59
        public float Speed_Eating_1_Tablet_Motion_Speed; // Offset: 63
        public float Speed_Eating_2_Tablet_Motion_Speed; // Offset: 67
        public float Speed_Eating_3_Tablet_Motion_Speed; // Offset: 71
        public float Mud_Motion_Speed; // Offset: 75
        public float Mud_Trans_Rate; // Offset: 79
        public byte Elemental_Damage_Defense_; // Offset: 83
        public byte Elemental_Damage_Resist_; // Offset: 84
        public byte Elemental_Damage_Resist; // Offset: 85
        public byte Weakness_Exploit_Hitzone_Threshold; // Offset: 86
        public ushort Latent_Power_Activation_Time; // Offset: 87
        public ushort Latent_Power_Total_Damage_to_Trigger; // Offset: 89
        public ushort Latent_Power_Secret_Total_Damage_to_Trigger; // Offset: 91
        public float Heroics_Activation_Health_; // Offset: 93
        public byte Guts_Health_Threshold; // Offset: 97
        public float Wide_Range_1_Efficiency; // Offset: 98
        public float Wide_Range_2_Efficiency; // Offset: 102
        public float Wide_Range_3_Efficiency; // Offset: 106
        public float Wide_Range_4_Efficiency; // Offset: 110
        public float Wide_Range_5_Efficiency; // Offset: 114
        public float Wide_Range_1_Range; // Offset: 118
        public float Wide_Range_2_Range; // Offset: 122
        public float Wide_Range_3_Range; // Offset: 126
        public float Wide_Range_4_Range; // Offset: 130
        public float Wide_Range_5_Range; // Offset: 134
        public float Unk1; // Offset: 138
        public float Unk2; // Offset: 142
        public float Unk3; // Offset: 146
        public float Unk4; // Offset: 150
        public float Unk5; // Offset: 154
        public float Unk6; // Offset: 158
        public float Unk7; // Offset: 162
        public float Unk8; // Offset: 166
        public float Unk9; // Offset: 170
        public float Unk10; // Offset: 174
        public float Unk11; // Offset: 178
        public float Unk12; // Offset: 182
        public float Unk13; // Offset: 186
        public float Unk14; // Offset: 190
        public float Unk15; // Offset: 194
        public float Unk16; // Offset: 198
        public float Unk17; // Offset: 202
        public float Unk18; // Offset: 202
        public float Unk19; // Offset: 206
        public float Focus_Gunlance_Charge_Shot_Time_Rate_1; // Offset: 210
        public float Focus_Gunlance_Charge_Shot_Time_Rate_2; // Offset: 214
        public float Focus_Gunlance_Charge_Shot_Time_Rate_3; // Offset: 218
        public float Focus_Charge_Blade_Slash_2_Time_Rate_1; // Offset: 222
        public float Focus_Charge_Blade_Slash_2_Time_Rate_2; // Offset: 226
        public float Focus_Charge_Blade_Slash_2_Time_Rate_3; // Offset: 230
        public float Focus_Charge_Blade_Phial_Charge_Slash_Time_Rate_1; // Offset: 234
        public float Focus_Charge_Blade_Phial_Charge_Slash_Time_Rate_2; // Offset: 238
        public float Focus_Charge_Blade_Phial_Charge_Slash_Time_Rate_3; // Offset: 242
        public ushort Punishing_Draw_Great_Sword_Attack_Power; // Offset: 246
        public ushort Punishing_Draw_Great_Sword_Stun; // Offset: 248
        public ushort Punishing_Draw_Great_Sword_Exhaust; // Offset: 250
        public ushort Punishing_Draw_Great_Sword_Param_4; // Offset: 252
        public ushort Punishing_Draw_Great_Sword_Param_5; // Offset: 254
        public ushort Punishing_Draw_Great_Sword_Param_6; // Offset: 256
        public ushort Punishing_Draw_Sword_Shield_Attack_Power; // Offset: 258
        public ushort Punishing_Draw_Sword_Shield_Stun; // Offset: 260
        public ushort Punishing_Draw_Sword_Shield_Exhaust; // Offset: 262
        public ushort Punishing_Draw_Sword_Shield_Param_4; // Offset: 264
        public ushort Punishing_Draw_Sword_Shield_Param_5; // Offset: 266
        public ushort Punishing_Draw_Sword_Shield_Param_6; // Offset: 268
        public ushort Punishing_Draw_Dual_Blades_Attack_Power; // Offset: 270
        public ushort Punishing_Draw_Dual_Blades_Stun; // Offset: 272
        public ushort Punishing_Draw_Dual_Blades_Exhaust; // Offset: 274
        public ushort Punishing_Draw_Dual_Blades_Param_4; // Offset: 276
        public ushort Punishing_Draw_Dual_Blades_Param_5; // Offset: 278
        public ushort Punishing_Draw_Dual_Blades_Param_6; // Offset: 280
        public ushort Punishing_Draw_Long_Sword_Attack_Power; // Offset: 282
        public ushort Punishing_Draw_Long_Sword_Stun; // Offset: 284
        public ushort Punishing_Draw_Long_Sword_Exhaust; // Offset: 286
        public ushort Punishing_Draw_Long_Sword_Param_4; // Offset: 288
        public ushort Punishing_Draw_Long_Sword_Param_5; // Offset: 290
        public ushort Punishing_Draw_Long_Sword_Param_6; // Offset: 292
        public ushort Punishing_Draw_Hammer_Attack_Power; // Offset: 294
        public ushort Punishing_Draw_Hammer_Stun; // Offset: 296
        public ushort Punishing_Draw_Hammer_Exhaust; // Offset: 298
        public ushort Punishing_Draw_Hammer_Param_4; // Offset: 300
        public ushort Punishing_Draw_Hammer_Param_5; // Offset: 302
        public ushort Punishing_Draw_Hammer_Param_6; // Offset: 304
        public ushort Punishing_Draw_Hunting_Horn_Attack_Power; // Offset: 306
        public ushort Punishing_Draw_Hunting_Horn_Stun; // Offset: 308
        public ushort Punishing_Draw_Hunting_Horn_Exhaust; // Offset: 310
        public ushort Punishing_Draw_Hunting_Horn_Param_4; // Offset: 312
        public ushort Punishing_Draw_Hunting_Horn_Param_5; // Offset: 314
        public ushort Punishing_Draw_Hunting_Horn_Param_6; // Offset: 316
        public ushort Punishing_Draw_Lance_Attack_Power; // Offset: 318
        public ushort Punishing_Draw_Lance_Stun; // Offset: 320
        public ushort Punishing_Draw_Lance_Exhaust; // Offset: 322
        public ushort Punishing_Draw_Lance_Param_4; // Offset: 324
        public ushort Punishing_Draw_Lance_Param_5; // Offset: 326
        public ushort Punishing_Draw_Lance_Param_6; // Offset: 328
        public ushort Punishing_Draw_Gunlance_Attack_Power; // Offset: 330
        public ushort Punishing_Draw_Gunlance_Stun; // Offset: 332
        public ushort Punishing_Draw_Gunlance_Exhaust; // Offset: 334
        public ushort Punishing_Draw_Gunlance_Param_4; // Offset: 336
        public ushort Punishing_Draw_Gunlance_Param_5; // Offset: 338
        public ushort Punishing_Draw_Gunlance_Param_6; // Offset: 340
        public ushort Punishing_Draw_Switch_Axe_Attack_Power; // Offset: 342
        public ushort Punishing_Draw_Switch_Axe_Stun; // Offset: 344
        public ushort Punishing_Draw_Switch_Axe_Exhaust; // Offset: 346
        public ushort Punishing_Draw_Switch_Axe_Param_4; // Offset: 348
        public ushort Punishing_Draw_Switch_Axe_Param_5; // Offset: 350
        public ushort Punishing_Draw_Switch_Axe_Param_6; // Offset: 352
        public ushort Punishing_Draw_Charge_Blade_Attack_Power; // Offset: 354
        public ushort Punishing_Draw_Charge_Blade_Stun; // Offset: 356
        public ushort Punishing_Draw_Charge_Blade_Exhaust; // Offset: 358
        public ushort Punishing_Draw_Charge_Blade_Param_4; // Offset: 360
        public ushort Punishing_Draw_Charge_Blade_Param_5; // Offset: 362
        public ushort Punishing_Draw_Charge_Blade_Param_6; // Offset: 364
        public ushort Punishing_Draw_Insect_Glaive_Attack_Power; // Offset: 366
        public ushort Punishing_Draw_Insect_Glaive_Stun; // Offset: 368
        public ushort Punishing_Draw_Insect_Glaive_Exhaust; // Offset: 370
        public ushort Punishing_Draw_Insect_Glaive_Param_4; // Offset: 372
        public ushort Punishing_Draw_Insect_Glaive_Param_5; // Offset: 374
        public ushort Punishing_Draw_Insect_Glaive_Param_6; // Offset: 376
        public ushort Punishing_Draw_Bow_Attack_Power; // Offset: 378
        public ushort Punishing_Draw_Bow_Stun; // Offset: 380
        public ushort Punishing_Draw_Bow_Exhaust; // Offset: 382
        public ushort Punishing_Draw_Bow_Param_4; // Offset: 384
        public ushort Punishing_Draw_Bow_Param_5; // Offset: 386
        public ushort Punishing_Draw_Bow_Param_6; // Offset: 388
        public ushort Punishing_Draw_HBG_Attack_Power; // Offset: 390
        public ushort Punishing_Draw_HBG_Stun; // Offset: 392
        public ushort Punishing_Draw_HBG_Exhaust; // Offset: 394
        public ushort Punishing_Draw_HBG_Param_4; // Offset: 396
        public ushort Punishing_Draw_HBG_Param_5; // Offset: 398
        public ushort Punishing_Draw_HBG_Param_6; // Offset: 400
        public ushort Punishing_Draw_LBG_Attack_Power; // Offset: 402
        public ushort Punishing_Draw_LBG_Stun; // Offset: 404
        public ushort Punishing_Draw_LBG_Exhaust; // Offset: 406
        public ushort Punishing_Draw_LBG_Param_4; // Offset: 408
        public ushort Punishing_Draw_LBG_Param_5; // Offset: 410
        public ushort Punishing_Draw_LBG_Param_6; // Offset: 412
    }
}