using MHW_Template;

namespace MHW_Editor.PlData {
    // Struct Size: "2256"
    // Initial Offset: "0"
    // Unique Id Formula: "0"
    public struct PlSkillParam {
        public float Speed_Eating_1_Drink_Motion_Speed; // Offset: 8
        public float Speed_Eating_2_Drink_Motion_Speed; // Offset: 12
        public float Speed_Eating_3_Drink_Motion_Speed; // Offset: 16
        public float Speed_Eating_1_Drink_End_Frame; // Offset: 20
        public float Speed_Eating_2_Drink_End_Frame; // Offset: 24
        public float Speed_Eating_3_Drink_End_Frame; // Offset: 28
        public float Speed_Eating_1_Heal_Speed_Rate; // Offset: 32
        public float Speed_Eating_2_Heal_Speed_Rate; // Offset: 36
        public float Speed_Eating_3_Heal_Speed_Rate; // Offset: 40
        public float Speed_Eating_1_Meat_Motion_Speed; // Offset: 44
        public float Speed_Eating_2_Meat_Motion_Speed; // Offset: 48
        public float Speed_Eating_3_Meat_Motion_Speed; // Offset: 52
        public byte Speed_Eating_1_Meat_Loop_Count; // Offset: 56
        public byte Speed_Eating_2_Meat_Loop_Count; // Offset: 57
        public byte Speed_Eating_3_Meat_Loop_Count; // Offset: 58
        public float Speed_Eating_1_2_3_Meat_End_Frame; // Offset: 59
        public float Speed_Eating_1_Tablet_Motion_Speed; // Offset: 63
        public float Speed_Eating_2_Tablet_Motion_Speed; // Offset: 67
        public float Speed_Eating_3_Tablet_Motion_Speed; // Offset: 71
        public float Mud_Motion_Speed; // Offset: 75
        public float Mud_Trans_Rate; // Offset: 79
        public byte Elemental_Damage_Defense_; // Offset: 83
        public byte Elemental_Damage_Resist_; // Offset: 84
        public byte Elemental_Damage_Resist; // Offset: 85
        public byte Weakness_Exploit_Hit_Zone_Threshold; // Offset: 86
        public ushort Latent_Power_Activation_Time; // Offset: 87
        public ushort Latent_Power_Total_Damage_to_Trigger; // Offset: 89
        public ushort Latent_Power_Secret_Total_Damage_to_Trigger; // Offset: 91
        public float Heroics_Activation_Health_; // Offset: 93
        public byte Guts_Health_Threshold; // Offset: 97
        public float Wide_Range_1_Efficiency; // Offset: 98
        public float Wide_Range_2_Efficiency; // Offset: 102
        public float Wide_Range_3_Efficiency; // Offset: 106
        public float Wide_Range_4_Efficiency; // Offset: 110
        public float Wide_Range_5_Efficiency; // Offset: 114
        public float Wide_Range_1_Range; // Offset: 118
        public float Wide_Range_2_Range; // Offset: 122
        public float Wide_Range_3_Range; // Offset: 126
        public float Wide_Range_4_Range; // Offset: 130
        public float Wide_Range_5_Range; // Offset: 134
        public float Unk1; // Offset: 138
        public float Unk2; // Offset: 142
        public float Unk3; // Offset: 146
        public float Unk4; // Offset: 150
        public float Unk5; // Offset: 154
        public float Unk6; // Offset: 158
        public float Unk7; // Offset: 162
        public float Unk8; // Offset: 166
        public float Unk9; // Offset: 170
        public float Unk10; // Offset: 174
        public float Unk11; // Offset: 178
        public float Unk12; // Offset: 182
        public float Unk13; // Offset: 186
        public float Unk14; // Offset: 190
        public float Unk15; // Offset: 194
        public float Unk16; // Offset: 198
        public float Unk17; // Offset: 202
        public float Unk18; // Offset: 206
        public float Focus_Gunlance_Charge_Shot_Time_Rate_1; // Offset: 210
        public float Focus_Gunlance_Charge_Shot_Time_Rate_2; // Offset: 214
        public float Focus_Gunlance_Charge_Shot_Time_Rate_3; // Offset: 218
        public float Focus_Charge_Blade_Slash_2_Time_Rate_1; // Offset: 222
        public float Focus_Charge_Blade_Slash_2_Time_Rate_2; // Offset: 226
        public float Focus_Charge_Blade_Slash_2_Time_Rate_3; // Offset: 230
        public float Focus_Charge_Blade_Phial_Charge_Slash_Time_Rate_1; // Offset: 234
        public float Focus_Charge_Blade_Phial_Charge_Slash_Time_Rate_2; // Offset: 238
        public float Focus_Charge_Blade_Phial_Charge_Slash_Time_Rate_3; // Offset: 242
        public ushort Punishing_Draw_Great_Sword_Attack_Power; // Offset: 246
        public ushort Punishing_Draw_Great_Sword_Stun; // Offset: 248
        public ushort Punishing_Draw_Great_Sword_Exhaust; // Offset: 250
        public ushort Punishing_Draw_Great_Sword_Param_4; // Offset: 252
        public ushort Punishing_Draw_Great_Sword_Param_5; // Offset: 254
        public ushort Punishing_Draw_Great_Sword_Param_6; // Offset: 256
        public ushort Punishing_Draw_Sword_Shield_Attack_Power; // Offset: 258
        public ushort Punishing_Draw_Sword_Shield_Stun; // Offset: 260
        public ushort Punishing_Draw_Sword_Shield_Exhaust; // Offset: 262
        public ushort Punishing_Draw_Sword_Shield_Param_4; // Offset: 264
        public ushort Punishing_Draw_Sword_Shield_Param_5; // Offset: 266
        public ushort Punishing_Draw_Sword_Shield_Param_6; // Offset: 268
        public ushort Punishing_Draw_Dual_Blades_Attack_Power; // Offset: 270
        public ushort Punishing_Draw_Dual_Blades_Stun; // Offset: 272
        public ushort Punishing_Draw_Dual_Blades_Exhaust; // Offset: 274
        public ushort Punishing_Draw_Dual_Blades_Param_4; // Offset: 276
        public ushort Punishing_Draw_Dual_Blades_Param_5; // Offset: 278
        public ushort Punishing_Draw_Dual_Blades_Param_6; // Offset: 280
        public ushort Punishing_Draw_Long_Sword_Attack_Power; // Offset: 282
        public ushort Punishing_Draw_Long_Sword_Stun; // Offset: 284
        public ushort Punishing_Draw_Long_Sword_Exhaust; // Offset: 286
        public ushort Punishing_Draw_Long_Sword_Param_4; // Offset: 288
        public ushort Punishing_Draw_Long_Sword_Param_5; // Offset: 290
        public ushort Punishing_Draw_Long_Sword_Param_6; // Offset: 292
        public ushort Punishing_Draw_Hammer_Attack_Power; // Offset: 294
        public ushort Punishing_Draw_Hammer_Stun; // Offset: 296
        public ushort Punishing_Draw_Hammer_Exhaust; // Offset: 298
        public ushort Punishing_Draw_Hammer_Param_4; // Offset: 300
        public ushort Punishing_Draw_Hammer_Param_5; // Offset: 302
        public ushort Punishing_Draw_Hammer_Param_6; // Offset: 304
        public ushort Punishing_Draw_Hunting_Horn_Attack_Power; // Offset: 306
        public ushort Punishing_Draw_Hunting_Horn_Stun; // Offset: 308
        public ushort Punishing_Draw_Hunting_Horn_Exhaust; // Offset: 310
        public ushort Punishing_Draw_Hunting_Horn_Param_4; // Offset: 312
        public ushort Punishing_Draw_Hunting_Horn_Param_5; // Offset: 314
        public ushort Punishing_Draw_Hunting_Horn_Param_6; // Offset: 316
        public ushort Punishing_Draw_Lance_Attack_Power; // Offset: 318
        public ushort Punishing_Draw_Lance_Stun; // Offset: 320
        public ushort Punishing_Draw_Lance_Exhaust; // Offset: 322
        public ushort Punishing_Draw_Lance_Param_4; // Offset: 324
        public ushort Punishing_Draw_Lance_Param_5; // Offset: 326
        public ushort Punishing_Draw_Lance_Param_6; // Offset: 328
        public ushort Punishing_Draw_Gunlance_Attack_Power; // Offset: 330
        public ushort Punishing_Draw_Gunlance_Stun; // Offset: 332
        public ushort Punishing_Draw_Gunlance_Exhaust; // Offset: 334
        public ushort Punishing_Draw_Gunlance_Param_4; // Offset: 336
        public ushort Punishing_Draw_Gunlance_Param_5; // Offset: 338
        public ushort Punishing_Draw_Gunlance_Param_6; // Offset: 340
        public ushort Punishing_Draw_Switch_Axe_Attack_Power; // Offset: 342
        public ushort Punishing_Draw_Switch_Axe_Stun; // Offset: 344
        public ushort Punishing_Draw_Switch_Axe_Exhaust; // Offset: 346
        public ushort Punishing_Draw_Switch_Axe_Param_4; // Offset: 348
        public ushort Punishing_Draw_Switch_Axe_Param_5; // Offset: 350
        public ushort Punishing_Draw_Switch_Axe_Param_6; // Offset: 352
        public ushort Punishing_Draw_Charge_Blade_Attack_Power; // Offset: 354
        public ushort Punishing_Draw_Charge_Blade_Stun; // Offset: 356
        public ushort Punishing_Draw_Charge_Blade_Exhaust; // Offset: 358
        public ushort Punishing_Draw_Charge_Blade_Param_4; // Offset: 360
        public ushort Punishing_Draw_Charge_Blade_Param_5; // Offset: 362
        public ushort Punishing_Draw_Charge_Blade_Param_6; // Offset: 364
        public ushort Punishing_Draw_Insect_Glaive_Attack_Power; // Offset: 366
        public ushort Punishing_Draw_Insect_Glaive_Stun; // Offset: 368
        public ushort Punishing_Draw_Insect_Glaive_Exhaust; // Offset: 370
        public ushort Punishing_Draw_Insect_Glaive_Param_4; // Offset: 372
        public ushort Punishing_Draw_Insect_Glaive_Param_5; // Offset: 374
        public ushort Punishing_Draw_Insect_Glaive_Param_6; // Offset: 376
        public ushort Punishing_Draw_Bow_Attack_Power; // Offset: 378
        public ushort Punishing_Draw_Bow_Stun; // Offset: 380
        public ushort Punishing_Draw_Bow_Exhaust; // Offset: 382
        public ushort Punishing_Draw_Bow_Param_4; // Offset: 384
        public ushort Punishing_Draw_Bow_Param_5; // Offset: 386
        public ushort Punishing_Draw_Bow_Param_6; // Offset: 388
        public ushort Punishing_Draw_HBG_Attack_Power; // Offset: 390
        public ushort Punishing_Draw_HBG_Stun; // Offset: 392
        public ushort Punishing_Draw_HBG_Exhaust; // Offset: 394
        public ushort Punishing_Draw_HBG_Param_4; // Offset: 396
        public ushort Punishing_Draw_HBG_Param_5; // Offset: 398
        public ushort Punishing_Draw_HBG_Param_6; // Offset: 400
        public ushort Punishing_Draw_LBG_Attack_Power; // Offset: 402
        public ushort Punishing_Draw_LBG_Stun; // Offset: 404
        public ushort Punishing_Draw_LBG_Exhaust; // Offset: 406
        public ushort Punishing_Draw_LBG_Param_4; // Offset: 408
        public ushort Punishing_Draw_LBG_Param_5; // Offset: 410
        public ushort Punishing_Draw_LBG_Param_6; // Offset: 412
        public byte Razor_Sharp_Sharpness_No_Reduce_; // Offset: 414
        public byte Razor_Sharp_Gunlance_Shot_Sub_Value; // Offset: 415
        public byte Razor_Sharp_Gunlance_Shot_No_Reduce_; // Offset: 416
        public byte Razor_Sharp_Gun_Ammo_No_Reduce_; // Offset: 417
        public byte Razor_Sharp_Bow_Coating_No_Reduce_; // Offset: 418
        public byte Razor_Sharp_IB_Unk; // Offset: 419
        public byte True_Razor_Sharp_Sharpness_No_Reduce_; // Offset: 420
        public byte True_Razor_Sharp_Gunlance_Shot_Sub_Value; // Offset: 421
        public byte True_Razor_Sharp_Gunlance_Shot_No_Reduce_; // Offset: 422
        public byte True_Razor_Sharp_Gun_Ammo_No_Reduce_; // Offset: 423
        public byte True_Razor_Sharp_Bow_Coating_No_Reduce_; // Offset: 424
        public byte True_Razor_Sharp_IB_Unk; // Offset: 425
        public float Minds_Eye_Ballistics_Gun_Critical_Begin_Wide_Rate; // Offset: 426
        public float Minds_Eye_Ballistics_Gun_Critical_End_Wide_Rate; // Offset: 430
        public float Minds_Eye_Ballistics_Bow_Critical_Begin_Wide_Rate; // Offset: 434
        public float Minds_Eye_Ballistics_Bow_Critical_End_Wide_Rate; // Offset: 438
        public float Critical_Element_Great_Sword_Rate; // Offset: 442
        public float Critical_Element_Sword_Shield_Rate; // Offset: 446
        public float Critical_Element_Dual_Blades_Rate; // Offset: 450
        public float Critical_Element_Long_Sword_Rate; // Offset: 454
        public float Critical_Element_Hammer_Rate; // Offset: 458
        public float Critical_Element_Hunting_Horn_Rate; // Offset: 462
        public float Critical_Element_Lance_Rate; // Offset: 466
        public float Critical_Element_Gunlance_Rate; // Offset: 470
        public float Critical_Element_Switch_Axe_Rate; // Offset: 474
        public float Critical_Element_Charge_Blade_Rate; // Offset: 478
        public float Critical_Element_Insect_Glaive_Rate; // Offset: 482
        public float Critical_Element_Bow_Rate; // Offset: 486
        public float Critical_Element_HBG_Rate; // Offset: 490
        public float Critical_Element_LBG_Rate; // Offset: 494
        public float Critical_Element_Dragon_Seal_Rate; // Offset: 498
        public float True_Critical_Element_Great_Sword_Rate; // Offset: 502
        public float True_Critical_Element_Sword_Shield_Rate; // Offset: 506
        public float True_Critical_Element_Dual_Blades_Rate; // Offset: 510
        public float True_Critical_Element_Long_Sword_Rate; // Offset: 514
        public float True_Critical_Element_Hammer_Rate; // Offset: 518
        public float True_Critical_Element_Hunting_Horn_Rate; // Offset: 522
        public float True_Critical_Element_Lance_Rate; // Offset: 526
        public float True_Critical_Element_Gunlance_Rate; // Offset: 530
        public float True_Critical_Element_Switch_Axe_Rate; // Offset: 534
        public float True_Critical_Element_Charge_Blade_Rate; // Offset: 538
        public float True_Critical_Element_Insect_Glaive_Rate; // Offset: 542
        public float True_Critical_Element_Bow_Rate; // Offset: 546
        public float True_Critical_Element_HBG_Rate; // Offset: 550
        public float True_Critical_Element_LBG_Rate; // Offset: 554
        public float True_Critical_Element_Dragon_Seal_Rate; // Offset: 558
        public float Critical_Condition_Great_Sword_Rate; // Offset: 562
        public float Critical_Condition_Sword_Shield_Rate; // Offset: 566
        public float Critical_Condition_Dual_Blades_Rate; // Offset: 570
        public float Critical_Condition_Long_Sword_Rate; // Offset: 574
        public float Critical_Condition_Hammer_Rate; // Offset: 578
        public float Critical_Condition_Hunting_Horn_Rate; // Offset: 582
        public float Critical_Condition_Lance_Rate; // Offset: 586
        public float Critical_Condition_Gunlance_Rate; // Offset: 590
        public float Critical_Condition_Switch_Axe_Rate; // Offset: 594
        public float Critical_Condition_Charge_Blade_Rate; // Offset: 598
        public float Critical_Condition_Insect_Glaive_Rate; // Offset: 602
        public float Critical_Condition_Bow_Rate; // Offset: 606
        public float Critical_Condition_HBG_Rate; // Offset: 610
        public float Critical_Condition_LBG_Rate; // Offset: 614
        public float True_Critical_Condition_Great_Sword_Rate; // Offset: 618
        public float True_Critical_Condition_Sword_Shield_Rate; // Offset: 622
        public float True_Critical_Condition_Dual_Blades_Rate; // Offset: 626
        public float True_Critical_Condition_Long_Sword_Rate; // Offset: 630
        public float True_Critical_Condition_Hammer_Rate; // Offset: 634
        public float True_Critical_Condition_Hunting_Horn_Rate; // Offset: 638
        public float True_Critical_Condition_Lance_Rate; // Offset: 642
        public float True_Critical_Condition_Gunlance_Rate; // Offset: 646
        public float True_Critical_Condition_Switch_Axe_Rate; // Offset: 650
        public float True_Critical_Condition_Charge_Blade_Rate; // Offset: 654
        public float True_Critical_Condition_Insect_Glaive_Rate; // Offset: 658
        public float True_Critical_Condition_Bow_Rate; // Offset: 662
        public float True_Critical_Condition_HBG_Rate; // Offset: 666
        public float True_Critical_Condition_LBG_Rate; // Offset: 670
        public ushort Bludgeoner_Red_Sharpness_Attack_Bonus; // Offset: 674
        public ushort Bludgeoner_Orange_Sharpness_Attack_Bonus; // Offset: 676
        public ushort Bludgeoner_Yellow_Sharpness_Attack_Bonus; // Offset: 678
        public ushort Bludgeoner_Green_Sharpness_Attack_Bonus; // Offset: 680
        public ushort Bludgeoner_Blue_Sharpness_Attack_Bonus; // Offset: 682
        public ushort Bludgeoner_White_Sharpness_Attack_Bonus; // Offset: 684
        public ushort Bludgeoner_Purple_Sharpness_Attack_Bonus; // Offset: 686
        public ushort Bludgeoner_Bowgun_Melee_Attack_Stun_Bonus; // Offset: 688
        public float Non_Elemental_Boost_Attack_Multiplier; // Offset: 690
        public float Affinity_Slider_Attack_Up_Activate_Time; // Offset: 694
        public float Affinity_Slider_Attack_Up_Duration; // Offset: 698
        public byte Affinity_Slider_Attack_Critical_Bonus; // Offset: 702
        public float Artillery_Gunlance_Shell_Attack_Rate_1; // Offset: 703
        public float Artillery_Gunlance_Shell_Attack_Rate_2; // Offset: 707
        public float Artillery_Gunlance_Shell_Attack_Rate_3; // Offset: 711
        public float Artillery_Gunlance_Shell_Attack_Rate_4; // Offset: 715
        public float Artillery_Gunlance_Shell_Attack_Rate_5; // Offset: 719
        public float Artillery_Gunlance_WyvernFire_Attack_Rate_1; // Offset: 723
        public float Artillery_Gunlance_WyvernFire_Attack_Rate_2; // Offset: 727
        public float Artillery_Gunlance_WyvernFire_Attack_Rate_3; // Offset: 731
        public float Artillery_Gunlance_WyvernFire_Attack_Rate_4; // Offset: 735
        public float Artillery_Gunlance_WyvernFire_Attack_Rate_5; // Offset: 739
        public float Artillery_Gunlance_Wyrmstake_Cannon_Attack_Rate_1; // Offset: 743
        public float Artillery_Gunlance_Wyrmstake_Cannon_Attack_Rate_2; // Offset: 747
        public float Artillery_Gunlance_Wyrmstake_Cannon_Attack_Rate_3; // Offset: 751
        public float Artillery_Gunlance_Wyrmstake_Cannon_Attack_Rate_4; // Offset: 755
        public float Artillery_Gunlance_Wyrmstake_Cannon_Attack_Rate_5; // Offset: 759
        public float Artillery_Gunlance_WyvernFire_Cooldown_Time_Rate_1; // Offset: 763
        public float Artillery_Gunlance_WyvernFire_Cooldown_Time_Rate_2; // Offset: 767
        public float Artillery_Gunlance_WyvernFire_Cooldown_Time_Rate_3; // Offset: 771
        public float Artillery_Gunlance_WyvernFire_Cooldown_Time_Rate_4; // Offset: 775
        public float Artillery_Gunlance_WyvernFire_Cooldown_Time_Rate_5; // Offset: 779
        public float Artillery_Charge_Blade_Impact_Phial_Attack_Rate_1; // Offset: 783
        public float Artillery_Charge_Blade_Impact_Phial_Attack_Rate_2; // Offset: 787
        public float Artillery_Charge_Blade_Impact_Phial_Attack_Rate_3; // Offset: 791
        public float Artillery_Charge_Blade_Impact_Phial_Attack_Rate_4; // Offset: 795
        public float Artillery_Charge_Blade_Impact_Phial_Attack_Rate_5; // Offset: 799
        public float Artillery_Bowgun_Sticky_Ammo_Attack_Rate_1; // Offset: 803
        public float Artillery_Bowgun_Sticky_Ammo_Attack_Rate_2; // Offset: 807
        public float Artillery_Bowgun_Sticky_Ammo_Attack_Rate_3; // Offset: 811
        public float Artillery_Bowgun_Sticky_Ammo_Attack_Rate_4; // Offset: 815
        public float Artillery_Bowgun_Sticky_Ammo_Attack_Rate_5; // Offset: 819
        public float Artillery_Bowgun_Kakusan_Attack_Rate_Appears_Unused_1; // Offset: 823
        public float Artillery_Bowgun_Kakusan_Attack_Rate_Appears_Unused_2; // Offset: 827
        public float Artillery_Bowgun_Kakusan_Attack_Rate_Appears_Unused_3; // Offset: 831
        public float Artillery_Bowgun_Kakusan_Attack_Rate_Appears_Unused_4; // Offset: 835
        public float Artillery_Bowgun_Kakusan_Attack_Rate_Appears_Unused_5; // Offset: 839
        public float Artillery_Bowgun_Wyvern_Ammo_Attack_Rate_1; // Offset: 843
        public float Artillery_Bowgun_Wyvern_Ammo_Attack_Rate_2; // Offset: 847
        public float Artillery_Bowgun_Wyvern_Ammo_Attack_Rate_3; // Offset: 851
        public float Artillery_Bowgun_Wyvern_Ammo_Attack_Rate_4; // Offset: 855
        public float Artillery_Bowgun_Wyvern_Ammo_Attack_Rate_5; // Offset: 859
        public float Artillery_LBG_Wyvernblast_Attack_Rate_Appears_Unused_1; // Offset: 863
        public float Artillery_LBG_Wyvernblast_Attack_Rate_Appears_Unused_2; // Offset: 867
        public float Artillery_LBG_Wyvernblast_Attack_Rate_Appears_Unused_3; // Offset: 871
        public float Artillery_LBG_Wyvernblast_Attack_Rate_Appears_Unused_4; // Offset: 875
        public float Artillery_LBG_Wyvernblast_Attack_Rate_Appears_Unused_5; // Offset: 879
        public float Heavy_Artillery_Ballista_Attack_Rate_1; // Offset: 883
        public float Heavy_Artillery_Ballista_Attack_Rate_2; // Offset: 887
        public float Heavy_Artillery_Cannon_Attack_Rate_1; // Offset: 891
        public float Heavy_Artillery_Cannon_Attack_Rate_2; // Offset: 895
        public float Bombardier_Attack_Rate_1; // Offset: 899
        public float Bombardier_Attack_Rate_2; // Offset: 903
        public float Bombardier_Attack_Rate_3; // Offset: 907
        public float Bombardier_Attack_Rate_4; // Offset: 911
        public float Bombardier_Attack_Rate_5; // Offset: 915
        public byte Capacity_Boost_Gunlance_Normal_Bonus; // Offset: 919
        public byte Capacity_Boost_Gunlance_Radiation_Bonus; // Offset: 920
        public byte Capacity_Boost_Gunlance_Scatter_Bonus; // Offset: 921
        public byte Capacity_Boost_Charge_Blade_Shield_Duration_Bonus; // Offset: 922
        public sbyte Ammo_Up_1_Capacity_1_Limit; // Offset: 923
        public byte Ammo_Up_1_Capacity_1_Bonus; // Offset: 924
        public sbyte Ammo_Up_1_Capacity_2_Limit; // Offset: 925
        public byte Ammo_Up_1_Capacity_2_Bonus; // Offset: 926
        public sbyte Ammo_Up_1_Capacity_3_Limit; // Offset: 927
        public byte Ammo_Up_1_Capacity_3_Bonus; // Offset: 928
        public sbyte Ammo_Up_1_Capacity_4_Limit; // Offset: 929
        public byte Ammo_Up_1_Capacity_4_Bonus; // Offset: 930
        public sbyte Ammo_Up_2_Capacity_1_Limit; // Offset: 931
        public byte Ammo_Up_2_Capacity_1_Bonus; // Offset: 932
        public sbyte Ammo_Up_2_Capacity_2_Limit; // Offset: 933
        public byte Ammo_Up_2_Capacity_2_Bonus; // Offset: 934
        public sbyte Ammo_Up_2_Capacity_3_Limit; // Offset: 935
        public byte Ammo_Up_2_Capacity_3_Bonus; // Offset: 936
        public sbyte Ammo_Up_2_Capacity_4_Limit; // Offset: 937
        public byte Ammo_Up_2_Capacity_4_Bonus; // Offset: 938
        public sbyte Ammo_Up_3_Capacity_1_Limit; // Offset: 939
        public byte Ammo_Up_3_Capacity_1_Bonus; // Offset: 940
        public sbyte Ammo_Up_3_Capacity_2_Limit; // Offset: 941
        public byte Ammo_Up_3_Capacity_2_Bonus; // Offset: 942
        public sbyte Ammo_Up_3_Capacity_3_Limit; // Offset: 943
        public byte Ammo_Up_3_Capacity_3_Bonus; // Offset: 944
        public sbyte Ammo_Up_3_Capacity_4_Limit; // Offset: 945
        public byte Ammo_Up_3_Capacity_4_Bonus; // Offset: 946
        public float Power_Prolonger_Dual_Blades_1; // Offset: 947
        public float Power_Prolonger_Dual_Blades_2; // Offset: 951
        public float Power_Prolonger_Dual_Blades_3; // Offset: 955
        public float Power_Prolonger_Long_Sword_1; // Offset: 959
        public float Power_Prolonger_Long_Sword_2; // Offset: 963
        public float Power_Prolonger_Long_Sword_3; // Offset: 967
        public float Power_Prolonger_Switch_Axe_1; // Offset: 971
        public float Power_Prolonger_Switch_Axe_2; // Offset: 975
        public float Power_Prolonger_Switch_Axe_3; // Offset: 979
        public float Power_Prolonger_Charge_Blade_1; // Offset: 983
        public float Power_Prolonger_Charge_Blade_2; // Offset: 987
        public float Power_Prolonger_Charge_Blade_3; // Offset: 991
        public float Power_Prolonger_Insect_Glaive_1; // Offset: 995
        public float Power_Prolonger_Insect_Glaive_2; // Offset: 999
        public float Power_Prolonger_Insect_Glaive_3; // Offset: 1003
        public float Health_Auto_Recover_Interval; // Offset: 1007
        public byte Health_Auto_Recover_Value; // Offset: 1011
        public byte Hasten_Recovery_Great_Sword_Recovery_Health; // Offset: 1012
        public byte Hasten_Recovery_Sword_Shield_Recovery_Health; // Offset: 1013
        public byte Hasten_Recovery_Dual_Blades_Recovery_Health; // Offset: 1014
        public byte Hasten_Recovery_Long_Sword_Recovery_Health; // Offset: 1015
        public byte Hasten_Recovery_Hammer_Recovery_Health; // Offset: 1016
        public byte Hasten_Recovery_Hunting_Horn_Recovery_Health; // Offset: 1017
        public byte Hasten_Recovery_Lance_Recovery_Health; // Offset: 1018
        public byte Hasten_Recovery_Gunlance_Recovery_Health; // Offset: 1019
        public byte Hasten_Recovery_Switch_Axe_Recovery_Health; // Offset: 1020
        public byte Hasten_Recovery_Charge_Blade_Recovery_Health; // Offset: 1021
        public byte Hasten_Recovery_Insect_Glaive_Recovery_Health; // Offset: 1022
        public byte Hasten_Recovery_Bow_Recovery_Health; // Offset: 1023
        public byte Hasten_Recovery_HBG_Recovery_Health; // Offset: 1024
        public byte Hasten_Recovery_LBG_Recovery_Health; // Offset: 1025
        public byte Hasten_Recovery_Success_Combo_; // Offset: 1026
        public float Hasten_Recovery_Combo_Duration; // Offset: 1027
        public float Hasten_Recovery_Combo_Ignore_Time; // Offset: 1031
        public byte Unk19; // Offset: 1035
        public float Unk20; // Offset: 1036
        public float Unk21; // Offset: 1040
        public byte Slinger_Up_1_Stone; // Offset: 1044
        public byte Slinger_Up_2_Stone; // Offset: 1045
        public byte Slinger_Up_3_Stone; // Offset: 1046
        public byte Slinger_Up_4_Stone; // Offset: 1047
        public byte Slinger_Up_5_Stone; // Offset: 1048
        public byte Slinger_Up_1_Redpit; // Offset: 1049
        public byte Slinger_Up_2_Redpit; // Offset: 1050
        public byte Slinger_Up_3_Redpit; // Offset: 1051
        public byte Slinger_Up_4_Redpit; // Offset: 1052
        public byte Slinger_Up_5_Redpit; // Offset: 1053
        public byte Slinger_Up_1_Brightmoss; // Offset: 1054
        public byte Slinger_Up_2_Brightmoss; // Offset: 1055
        public byte Slinger_Up_3_Brightmoss; // Offset: 1056
        public byte Slinger_Up_4_Brightmoss; // Offset: 1057
        public byte Slinger_Up_5_Brightmoss; // Offset: 1058
        public byte Slinger_Up_1_Scatternut; // Offset: 1059
        public byte Slinger_Up_2_Scatternut; // Offset: 1060
        public byte Slinger_Up_3_Scatternut; // Offset: 1061
        public byte Slinger_Up_4_Scatternut; // Offset: 1062
        public byte Slinger_Up_5_Scatternut; // Offset: 1063
        public byte Slinger_Up_1_Unk_1; // Offset: 1064
        public byte Slinger_Up_2_Unk_1; // Offset: 1065
        public byte Slinger_Up_3_Unk_1; // Offset: 1066
        public byte Slinger_Up_4_Unk_1; // Offset: 1067
        public byte Slinger_Up_5_Unk_1; // Offset: 1068
        public byte Slinger_Up_1_Unk_2; // Offset: 1069
        public byte Slinger_Up_2_Unk_2; // Offset: 1070
        public byte Slinger_Up_3_Unk_2; // Offset: 1071
        public byte Slinger_Up_4_Unk_2; // Offset: 1072
        public byte Slinger_Up_5_Unk_2; // Offset: 1073
        public byte Slinger_Up_1_Unk_3; // Offset: 1074
        public byte Slinger_Up_2_Unk_3; // Offset: 1075
        public byte Slinger_Up_3_Unk_3; // Offset: 1076
        public byte Slinger_Up_4_Unk_3; // Offset: 1077
        public byte Slinger_Up_5_Unk_3; // Offset: 1078
        public byte Slinger_Up_1_Unk_4; // Offset: 1079
        public byte Slinger_Up_2_Unk_4; // Offset: 1080
        public byte Slinger_Up_3_Unk_4; // Offset: 1081
        public byte Slinger_Up_4_Unk_4; // Offset: 1082
        public byte Slinger_Up_5_Unk_4; // Offset: 1083
        public byte Slinger_Up_1_Unk_5; // Offset: 1084
        public byte Slinger_Up_2_Unk_5; // Offset: 1085
        public byte Slinger_Up_3_Unk_5; // Offset: 1086
        public byte Slinger_Up_4_Unk_5; // Offset: 1087
        public byte Slinger_Up_5_Unk_5; // Offset: 1088
        public byte Slinger_Up_1_Torch_Pod; // Offset: 1089
        public byte Slinger_Up_2_Torch_Pod; // Offset: 1090
        public byte Slinger_Up_3_Torch_Pod; // Offset: 1091
        public byte Slinger_Up_4_Torch_Pod; // Offset: 1092
        public byte Slinger_Up_5_Torch_Pod; // Offset: 1093
        public byte Slinger_Up_1_Unk_6; // Offset: 1094
        public byte Slinger_Up_2_Unk_6; // Offset: 1095
        public byte Slinger_Up_3_Unk_6; // Offset: 1096
        public byte Slinger_Up_4_Unk_6; // Offset: 1097
        public byte Slinger_Up_5_Unk_6; // Offset: 1098
        public byte Slinger_Up_1_Unk_7; // Offset: 1099
        public byte Slinger_Up_2_Unk_7; // Offset: 1100
        public byte Slinger_Up_3_Unk_7; // Offset: 1101
        public byte Slinger_Up_4_Unk_7; // Offset: 1102
        public byte Slinger_Up_5_Unk_7; // Offset: 1103
        public byte Slinger_Up_1_Unk_8; // Offset: 1104
        public byte Slinger_Up_2_Unk_8; // Offset: 1105
        public byte Slinger_Up_3_Unk_8; // Offset: 1106
        public byte Slinger_Up_4_Unk_8; // Offset: 1107
        public byte Slinger_Up_5_Unk_8; // Offset: 1108
        public byte Slinger_Up_1_Unk_9; // Offset: 1109
        public byte Slinger_Up_2_Unk_9; // Offset: 1110
        public byte Slinger_Up_3_Unk_9; // Offset: 1111
        public byte Slinger_Up_4_Unk_9; // Offset: 1112
        public byte Slinger_Up_5_Unk_9; // Offset: 1113
        public byte Slinger_Up_1_Bomb_Pod; // Offset: 1114
        public byte Slinger_Up_2_Bomb_Pod; // Offset: 1115
        public byte Slinger_Up_3_Bomb_Pod; // Offset: 1116
        public byte Slinger_Up_4_Bomb_Pod; // Offset: 1117
        public byte Slinger_Up_5_Bomb_Pod; // Offset: 1118
        public byte Slinger_Up_1_Piercing_Pod; // Offset: 1119
        public byte Slinger_Up_2_Piercing_Pod; // Offset: 1120
        public byte Slinger_Up_3_Piercing_Pod; // Offset: 1121
        public byte Slinger_Up_4_Piercing_Pod; // Offset: 1122
        public byte Slinger_Up_5_Piercing_Pod; // Offset: 1123
        public byte Slinger_Up_1_Slinger_Thorn; // Offset: 1124
        public byte Slinger_Up_2_Slinger_Thorn; // Offset: 1125
        public byte Slinger_Up_3_Slinger_Thorn; // Offset: 1126
        public byte Slinger_Up_4_Slinger_Thorn; // Offset: 1127
        public byte Slinger_Up_5_Slinger_Thorn; // Offset: 1128
        public byte Slinger_Up_1_Dragon_Pod; // Offset: 1129
        public byte Slinger_Up_2_Dragon_Pod; // Offset: 1130
        public byte Slinger_Up_3_Dragon_Pod; // Offset: 1131
        public byte Slinger_Up_4_Dragon_Pod; // Offset: 1132
        public byte Slinger_Up_5_Dragon_Pod; // Offset: 1133
        public byte Slinger_Up_1_Unk_10; // Offset: 1134
        public byte Slinger_Up_2_Unk_10; // Offset: 1135
        public byte Slinger_Up_3_Unk_10; // Offset: 1136
        public byte Slinger_Up_4_Unk_10; // Offset: 1137
        public byte Slinger_Up_5_Unk_10; // Offset: 1138
        public byte Slinger_Up_1_Unk_11; // Offset: 1139
        public byte Slinger_Up_2_Unk_11; // Offset: 1140
        public byte Slinger_Up_3_Unk_11; // Offset: 1141
        public byte Slinger_Up_4_Unk_11; // Offset: 1142
        public byte Slinger_Up_5_Unk_11; // Offset: 1143
        public byte Slinger_Up_1_Unk_12; // Offset: 1144
        public byte Slinger_Up_2_Unk_12; // Offset: 1145
        public byte Slinger_Up_3_Unk_12; // Offset: 1146
        public byte Slinger_Up_4_Unk_12; // Offset: 1147
        public byte Slinger_Up_5_Unk_12; // Offset: 1148
        public byte Slinger_Up_1_Unk_13; // Offset: 1149
        public byte Slinger_Up_2_Unk_13; // Offset: 1150
        public byte Slinger_Up_3_Unk_13; // Offset: 1151
        public byte Slinger_Up_4_Unk_13; // Offset: 1152
        public byte Slinger_Up_5_Unk_13; // Offset: 1153
        public byte Slinger_Up_1_Unk_14; // Offset: 1154
        public byte Slinger_Up_2_Unk_14; // Offset: 1155
        public byte Slinger_Up_3_Unk_14; // Offset: 1156
        public byte Slinger_Up_4_Unk_14; // Offset: 1157
        public byte Slinger_Up_5_Unk_14; // Offset: 1158
        public byte Slinger_Up_1_Unk_15; // Offset: 1159
        public byte Slinger_Up_2_Unk_15; // Offset: 1160
        public byte Slinger_Up_3_Unk_15; // Offset: 1161
        public byte Slinger_Up_4_Unk_15; // Offset: 1162
        public byte Slinger_Up_5_Unk_15; // Offset: 1163
        public byte Slinger_Up_1_Unk_16; // Offset: 1164
        public byte Slinger_Up_2_Unk_16; // Offset: 1165
        public byte Slinger_Up_3_Unk_16; // Offset: 1166
        public byte Slinger_Up_4_Unk_16; // Offset: 1167
        public byte Slinger_Up_5_Unk_16; // Offset: 1168
        public byte Slinger_Up_1_Unk_17; // Offset: 1169
        public byte Slinger_Up_2_Unk_17; // Offset: 1170
        public byte Slinger_Up_3_Unk_17; // Offset: 1171
        public byte Slinger_Up_4_Unk_17; // Offset: 1172
        public byte Slinger_Up_5_Unk_17; // Offset: 1173
        public byte Slinger_Up_1_Crystalburst; // Offset: 1174
        public byte Slinger_Up_2_Crystalburst; // Offset: 1175
        public byte Slinger_Up_3_Crystalburst; // Offset: 1176
        public byte Slinger_Up_4_Crystalburst; // Offset: 1177
        public byte Slinger_Up_5_Crystalburst; // Offset: 1178
        public byte Slinger_Up_1_Puddle_Pod; // Offset: 1179
        public byte Slinger_Up_2_Puddle_Pod; // Offset: 1180
        public byte Slinger_Up_3_Puddle_Pod; // Offset: 1181
        public byte Slinger_Up_4_Puddle_Pod; // Offset: 1182
        public byte Slinger_Up_5_Puddle_Pod; // Offset: 1183
        public byte Slinger_Up_1_Unk_18; // Offset: 1184
        public byte Slinger_Up_2_Unk_18; // Offset: 1185
        public byte Slinger_Up_3_Unk_18; // Offset: 1186
        public byte Slinger_Up_4_Unk_18; // Offset: 1187
        public byte Slinger_Up_5_Unk_18; // Offset: 1188
        public byte Slinger_Up_1_Unk_19; // Offset: 1189
        public byte Slinger_Up_2_Unk_19; // Offset: 1190
        public byte Slinger_Up_3_Unk_19; // Offset: 1191
        public byte Slinger_Up_4_Unk_19; // Offset: 1192
        public byte Slinger_Up_5_Unk_19; // Offset: 1193
        public byte Slinger_Up_1_Unk_20; // Offset: 1194
        public byte Slinger_Up_2_Unk_20; // Offset: 1195
        public byte Slinger_Up_3_Unk_20; // Offset: 1196
        public byte Slinger_Up_4_Unk_20; // Offset: 1197
        public byte Slinger_Up_5_Unk_20; // Offset: 1198
        public float Master_Fisher_Add_Hook_Time; // Offset: 1199
        public float Master_Fisher_Big_Fish_Catch_Rate; // Offset: 1203
        public float Adrenaline_Stamina_Rate; // Offset: 1207
        public float Elemental_Airborne_Great_Sword_Rate; // Offset: 1211
        public float Elemental_Airborne_Sword_Shield_Rate; // Offset: 1215
        public float Elemental_Airborne_Dual_Blades_Rate; // Offset: 1219
        public float Elemental_Airborne_Long_Sword_Rate; // Offset: 1223
        public float Elemental_Airborne_Hammer_Rate; // Offset: 1227
        public float Elemental_Airborne_Hunting_Horn_Rate; // Offset: 1231
        public float Elemental_Airborne_Lance_Rate; // Offset: 1235
        public float Elemental_Airborne_Gunlance_Rate; // Offset: 1239
        public float Elemental_Airborne_Switch_Axe_Rate; // Offset: 1243
        public float Elemental_Airborne_Charge_Blade_Rate; // Offset: 1247
        public float Elemental_Airborne_Insect_Glaive_Rate; // Offset: 1251
        public float Elemental_Airborne_Bow_Rate; // Offset: 1255
        public float Elemental_Airborne_HBG_Rate; // Offset: 1259
        public float Elemental_Airborne_LBG_Rate; // Offset: 1263
        public byte Unk22; // Offset: 1267
        public byte Unk23; // Offset: 1268
        public byte Unk24; // Offset: 1269
        public byte Unk25; // Offset: 1270
        public byte Unk26; // Offset: 1271
        public byte Unk27; // Offset: 1272
        public byte Unk28; // Offset: 1273
        public byte Unk29; // Offset: 1274
        public byte Unk30; // Offset: 1275
        public byte Unk31; // Offset: 1276
        public float Unk32; // Offset: 1277
        public float Frostcraft_Great_Sword_Level_Multiplier_0_15_; // Offset: 1281
        public float Frostcraft_Great_Sword_Level_Multiplier_16_45_; // Offset: 1285
        public float Frostcraft_Great_Sword_Level_Multiplier_46_80_; // Offset: 1289
        public float Frostcraft_Great_Sword_Level_Multiplier_81_100_; // Offset: 1293
        public float Frostcraft_Great_Sword_Recovery_Speed_Unsheathed; // Offset: 1297
        public float Frostcraft_Great_Sword_Recovery_Speed_Sheathed; // Offset: 1301
        public float Frostcraft_Great_Sword_Consumption_per_Hit; // Offset: 1305
        public float Frostcraft_Sword_Shield_Level_Multiplier_0_15_; // Offset: 1309
        public float Frostcraft_Sword_Shield_Level_Multiplier_16_45_; // Offset: 1313
        public float Frostcraft_Sword_Shield_Level_Multiplier_46_80_; // Offset: 1317
        public float Frostcraft_Sword_Shield_Level_Multiplier_81_100_; // Offset: 1321
        public float Frostcraft_Sword_Shield_Recovery_Speed_Unsheathed; // Offset: 1325
        public float Frostcraft_Sword_Shield_Recovery_Speed_Sheathed; // Offset: 1329
        public float Frostcraft_Sword_Shield_Consumption_per_Hit; // Offset: 1333
        public float Frostcraft_Dual_Blades_Level_Multiplier_0_15_; // Offset: 1337
        public float Frostcraft_Dual_Blades_Level_Multiplier_16_45_; // Offset: 1341
        public float Frostcraft_Dual_Blades_Level_Multiplier_46_80_; // Offset: 1345
        public float Frostcraft_Dual_Blades_Level_Multiplier_81_100_; // Offset: 1349
        public float Frostcraft_Dual_Blades_Recovery_Speed_Unsheathed; // Offset: 1353
        public float Frostcraft_Dual_Blades_Recovery_Speed_Sheathed; // Offset: 1357
        public float Frostcraft_Dual_Blades_Consumption_per_Hit; // Offset: 1361
        public float Frostcraft_Long_Sword_Level_Multiplier_0_15_; // Offset: 1365
        public float Frostcraft_Long_Sword_Level_Multiplier_16_45_; // Offset: 1369
        public float Frostcraft_Long_Sword_Level_Multiplier_46_80_; // Offset: 1373
        public float Frostcraft_Long_Sword_Level_Multiplier_81_100_; // Offset: 1377
        public float Frostcraft_Long_Sword_Recovery_Speed_Unsheathed; // Offset: 1381
        public float Frostcraft_Long_Sword_Recovery_Speed_Sheathed; // Offset: 1385
        public float Frostcraft_Long_Sword_Consumption_per_Hit; // Offset: 1389
        public float Frostcraft_Hammer_Level_Multiplier_0_15_; // Offset: 1393
        public float Frostcraft_Hammer_Level_Multiplier_16_45_; // Offset: 1397
        public float Frostcraft_Hammer_Level_Multiplier_46_80_; // Offset: 1401
        public float Frostcraft_Hammer_Level_Multiplier_81_100_; // Offset: 1405
        public float Frostcraft_Hammer_Recovery_Speed_Unsheathed; // Offset: 1409
        public float Frostcraft_Hammer_Recovery_Speed_Sheathed; // Offset: 1413
        public float Frostcraft_Hammer_Consumption_per_Hit; // Offset: 1417
        public float Frostcraft_Hunting_Horn_Level_Multiplier_0_15_; // Offset: 1421
        public float Frostcraft_Hunting_Horn_Level_Multiplier_16_45_; // Offset: 1425
        public float Frostcraft_Hunting_Horn_Level_Multiplier_46_80_; // Offset: 1429
        public float Frostcraft_Hunting_Horn_Level_Multiplier_81_100_; // Offset: 1433
        public float Frostcraft_Hunting_Horn_Recovery_Speed_Unsheathed; // Offset: 1437
        public float Frostcraft_Hunting_Horn_Recovery_Speed_Sheathed; // Offset: 1441
        public float Frostcraft_Hunting_Horn_Consumption_per_Hit; // Offset: 1445
        public float Frostcraft_Lance_Level_Multiplier_0_15_; // Offset: 1449
        public float Frostcraft_Lance_Level_Multiplier_16_45_; // Offset: 1453
        public float Frostcraft_Lance_Level_Multiplier_46_80_; // Offset: 1457
        public float Frostcraft_Lance_Level_Multiplier_81_100_; // Offset: 1461
        public float Frostcraft_Lance_Recovery_Speed_Unsheathed; // Offset: 1465
        public float Frostcraft_Lance_Recovery_Speed_Sheathed; // Offset: 1469
        public float Frostcraft_Lance_Consumption_per_Hit; // Offset: 1473
        public float Frostcraft_Gunlance_Level_Multiplier_0_15_; // Offset: 1477
        public float Frostcraft_Gunlance_Level_Multiplier_16_45_; // Offset: 1481
        public float Frostcraft_Gunlance_Level_Multiplier_46_80_; // Offset: 1485
        public float Frostcraft_Gunlance_Level_Multiplier_81_100_; // Offset: 1489
        public float Frostcraft_Gunlance_Recovery_Speed_Unsheathed; // Offset: 1493
        public float Frostcraft_Gunlance_Recovery_Speed_Sheathed; // Offset: 1497
        public float Frostcraft_Gunlance_Consumption_per_Hit; // Offset: 1501
        public float Frostcraft_Switch_Axe_Level_Multiplier_0_15_; // Offset: 1505
        public float Frostcraft_Switch_Axe_Level_Multiplier_16_45_; // Offset: 1509
        public float Frostcraft_Switch_Axe_Level_Multiplier_46_80_; // Offset: 1513
        public float Frostcraft_Switch_Axe_Level_Multiplier_81_100_; // Offset: 1517
        public float Frostcraft_Switch_Axe_Recovery_Speed_Unsheathed; // Offset: 1521
        public float Frostcraft_Switch_Axe_Recovery_Speed_Sheathed; // Offset: 1525
        public float Frostcraft_Switch_Axe_Consumption_per_Hit; // Offset: 1529
        public float Frostcraft_Charge_Blade_Level_Multiplier_0_15_; // Offset: 1533
        public float Frostcraft_Charge_Blade_Level_Multiplier_16_45_; // Offset: 1537
        public float Frostcraft_Charge_Blade_Level_Multiplier_46_80_; // Offset: 1541
        public float Frostcraft_Charge_Blade_Level_Multiplier_81_100_; // Offset: 1545
        public float Frostcraft_Charge_Blade_Recovery_Speed_Unsheathed; // Offset: 1549
        public float Frostcraft_Charge_Blade_Recovery_Speed_Sheathed; // Offset: 1553
        public float Frostcraft_Charge_Blade_Consumption_per_Hit; // Offset: 1557
        public float Frostcraft_Insect_Glaive_Level_Multiplier_0_15_; // Offset: 1561
        public float Frostcraft_Insect_Glaive_Level_Multiplier_16_45_; // Offset: 1565
        public float Frostcraft_Insect_Glaive_Level_Multiplier_46_80_; // Offset: 1569
        public float Frostcraft_Insect_Glaive_Level_Multiplier_81_100_; // Offset: 1573
        public float Frostcraft_Insect_Glaive_Recovery_Speed_Unsheathed; // Offset: 1577
        public float Frostcraft_Insect_Glaive_Recovery_Speed_Sheathed; // Offset: 1581
        public float Frostcraft_Insect_Glaive_Consumption_per_Hit; // Offset: 1585
        public float Frostcraft_Bow_Level_Multiplier_0_15_; // Offset: 1589
        public float Frostcraft_Bow_Level_Multiplier_16_45_; // Offset: 1593
        public float Frostcraft_Bow_Level_Multiplier_46_80_; // Offset: 1597
        public float Frostcraft_Bow_Level_Multiplier_81_100_; // Offset: 1601
        public float Frostcraft_Bow_Recovery_Speed_Unsheathed; // Offset: 1605
        public float Frostcraft_Bow_Recovery_Speed_Sheathed; // Offset: 1609
        public float Frostcraft_Bow_Consumption_per_Hit; // Offset: 1613
        public float Frostcraft_HBG_Level_Multiplier_0_15_; // Offset: 1617
        public float Frostcraft_HBG_Level_Multiplier_16_45_; // Offset: 1621
        public float Frostcraft_HBG_Level_Multiplier_46_80_; // Offset: 1625
        public float Frostcraft_HBG_Level_Multiplier_81_100_; // Offset: 1629
        public float Frostcraft_HBG_Recovery_Speed_Unsheathed; // Offset: 1633
        public float Frostcraft_HBG_Recovery_Speed_Sheathed; // Offset: 1637
        public float Frostcraft_HBG_Consumption_per_Hit; // Offset: 1641
        public float Frostcraft_LBG_Level_Multiplier_0_15_; // Offset: 1645
        public float Frostcraft_LBG_Level_Multiplier_16_45_; // Offset: 1649
        public float Frostcraft_LBG_Level_Multiplier_46_80_; // Offset: 1653
        public float Frostcraft_LBG_Level_Multiplier_81_100_; // Offset: 1657
        public float Frostcraft_LBG_Recovery_Speed_Unsheathed; // Offset: 1661
        public float Frostcraft_LBG_Recovery_Speed_Sheathed; // Offset: 1665
        public float Frostcraft_LBG_Consumption_per_Hit; // Offset: 1669
        public byte Unk33; // Offset: 1673
        public byte Unk34; // Offset: 1674
        public byte Unk35; // Offset: 1675
        public byte Frostcraft_Bow_Rapid_Shot_Clutch_Claw_Arrow_Consumption_per_Hit; // Offset: 1676
        public byte Frostcraft_Bow_Power_Shot_Consumption_per_Hit; // Offset: 1677
        public byte Frostcraft_Bow_Arc_Shot_Consumption_per_Hit; // Offset: 1678
        public byte Frostcraft_Bow_Dragonpiercer_Consumption_per_Hit; // Offset: 1679
        public byte Frostcraft_Bow_Thousand_Dragons_Consumption_per_Hit; // Offset: 1680
        public byte Frostcraft_Bowgun_Normal_Ammo_Consumption_per_Hit; // Offset: 1681
        public byte Frostcraft_Bowgun_Pierce_Ammo_Consumption_per_Hit; // Offset: 1682
        public byte Frostcraft_Bowgun_Spread_Ammo_Consumption_per_Hit; // Offset: 1683
        public byte Frostcraft_Bowgun_Sticky_Ammo_Consumption_per_Hit; // Offset: 1684
        public byte Frostcraft_Bowgun_Cluster_Ammo_Consumption_per_Hit; // Offset: 1685
        public byte Frostcraft_Bowgun_Elemental_Ammo_Consumption_per_Hit; // Offset: 1686
        public byte Frostcraft_Bowgun_Status_Ammo_Consumption_per_Hit; // Offset: 1687
        public byte Frostcraft_Bowgun_Wyvern_Ammo_Consumption_per_Hit; // Offset: 1688
        public byte Frostcraft_Bowgun_Slicing_Ammo_Consumption_per_Hit; // Offset: 1689
        public byte Frostcraft_HBG_Wyvernheart_Consumption_per_Hit; // Offset: 1690
        public byte Frostcraft_HBG_Wyvernsnipe_Consumption_per_Hit; // Offset: 1691
        public byte Frostcraft_HBG_Wyvernsnipe_Type_2_Consumption_per_Hit; // Offset: 1692
        public byte Frostcraft_LBG_Wyvernblast_Consumption_per_Hit; // Offset: 1693
        public byte Frostcraft_HBG_Claw_Wyvernheart_Gatling_Consumption_per_Hit; // Offset: 1694
        public byte Frostcraft_HBG_Claw_Wyvernheart_Finish_Consumption_per_Hit; // Offset: 1695
        public byte Frostcraft_HBG_Wyvernsnipe_Claw_Consumption_per_Hit; // Offset: 1696
        public byte Frostcraft_LBG_Wyvernblast_Claw_Consumption_per_Hit; // Offset: 1697
        public float Unk36; // Offset: 1698
        public float Unk37; // Offset: 1702
        public float Unk38; // Offset: 1706
        public float Unk39; // Offset: 1710
        public float Unk40; // Offset: 1714
        public float Unk41; // Offset: 1718
        public float Unk42; // Offset: 1722
        public float Unk43; // Offset: 1726
        public float Unk44; // Offset: 1730
        public float Unk45; // Offset: 1734
        public float Unk46; // Offset: 1738
        public float Unk47; // Offset: 1742
        public float Unk48; // Offset: 1746
        public float Unk49; // Offset: 1750
        public float Unk50; // Offset: 1754
        public float Unk51; // Offset: 1758
        public float Unk52; // Offset: 1762
        public float Unk53; // Offset: 1766
        public float Unk54; // Offset: 1770
        public float Unk55; // Offset: 1774
        public float Unk56; // Offset: 1778
        public float Unk57; // Offset: 1782
        public float Unk58; // Offset: 1786
        public float Unk59; // Offset: 1790
        public float Unk60; // Offset: 1794
        public float Unk61; // Offset: 1798
        public float Unk62; // Offset: 1802
        public float Unk63; // Offset: 1806
        public float Unk64; // Offset: 1810
        public float Unk65; // Offset: 1814
        public float Unk66; // Offset: 1818
        public float Unk67; // Offset: 1822
        public float Unk68; // Offset: 1826
        public float Unk69; // Offset: 1830
        public float Unk70; // Offset: 1834
        public float Unk71; // Offset: 1838
        public float Unk72; // Offset: 1842
        public float Unk73; // Offset: 1846
        public float Unk74; // Offset: 1850
        public float Unk75; // Offset: 1854
        public float Unk76; // Offset: 1858
        public float Unk77; // Offset: 1862
        public float Unk78; // Offset: 1866
        public float Unk79; // Offset: 1870
        public float Unk80; // Offset: 1874
        public float Unk81; // Offset: 1878
        public float Unk82; // Offset: 1882
        public float Unk83; // Offset: 1886
        public ushort Food_Effect_Life_Up_1; // Offset: 1890
        public ushort Food_Effect_Life_Up_2; // Offset: 1892
        public ushort Food_Effect_Life_Up_3; // Offset: 1894
        public ushort Food_Effect_Life_Up_4; // Offset: 1896
        public ushort Food_Effect_Life_Up_5; // Offset: 1898
        public ushort Food_Effect_Life_Up_6; // Offset: 1900
        public ushort Food_Effect_Stamina_Up_1; // Offset: 1902
        public ushort Food_Effect_Stamina_Up_2; // Offset: 1904
        public ushort Food_Effect_Stamina_Up_3; // Offset: 1906
        public ushort Food_Effect_Attack_Up_1; // Offset: 1908
        public ushort Food_Effect_Attack_Up_2; // Offset: 1910
        public ushort Food_Effect_Attack_Up_3; // Offset: 1912
        public ushort Food_Effect_Attack_Up_4; // Offset: 1914
        public ushort Food_Effect_Defense_Up_1; // Offset: 1916
        public ushort Food_Effect_Defense_Up_2; // Offset: 1918
        public ushort Food_Effect_Defense_Up_3; // Offset: 1920
        public ushort Food_Effect_Defense_Up_4; // Offset: 1922
        public ushort Food_Effect_All_Resistances_Up_1; // Offset: 1924
        public ushort Food_Effect_All_Resistances_Up_2; // Offset: 1926
        public ushort Food_Effect_All_Resistances_Up_3; // Offset: 1928
        public ushort Food_Effect_All_Resistances_Up_4; // Offset: 1930
        public byte Feline_Polisher_1; // Offset: 1932
        public byte Feline_Polisher_2; // Offset: 1933
        public byte Feline_Polisher_3; // Offset: 1934
        public byte Feline_Polisher_Loop_1; // Offset: 1935
        public byte Feline_Polisher_Loop_2; // Offset: 1936
        public byte Feline_Polisher_Loop_3; // Offset: 1937
        public float Feline_Rider_Attack_Rate; // Offset: 1938
        public float Feline_Heroics_Attack_Rate; // Offset: 1942
        public float Feline_Heroics_Defense_Rate; // Offset: 1946
        public byte Feline_Heroics_Life_Activation_Threshold; // Offset: 1950
        public byte Feline_Carving_L_Lottery_1; // Offset: 1951
        public byte Feline_Carving_L_Lottery_2; // Offset: 1952
        public byte Feline_Carving_L_Lottery_3; // Offset: 1953
        public byte Feline_Carving_L_Up_1; // Offset: 1954
        public byte Feline_Carving_L_Up_2; // Offset: 1955
        public byte Feline_Carving_L_Up_3; // Offset: 1956
        public byte Feline_Carving_L_Up_4; // Offset: 1957
        public byte Feline_Carving_S_Lottery_; // Offset: 1958
        public byte Feline_Carving_S_Up_; // Offset: 1959
        public float Feline_Medic_Heal_Rate; // Offset: 1960
        public float Feline_Black_Belt_Stamina_Rate; // Offset: 1964
        public ushort Feline_Special_Attack_Condition_Attack_Bonus; // Offset: 1968
        public float Feline_Special_Attack_Capture_Attack_Rate; // Offset: 1970
        public byte Feline_Defense_S_; // Offset: 1974
        public byte Feline_Defense_L_; // Offset: 1975
        public float Feline_Defense_S_Damage_Rate; // Offset: 1976
        public float Feline_Defense_L_Damage_Rate; // Offset: 1980
        public float Feline_Harvest_Cooldown_Multiplier; // Offset: 1984
        public float Feline_Sharpshooter_Shell_Attack_Rate; // Offset: 1988
        public float Feline_Escape_Artist_Dash_Stamina_Rate; // Offset: 1992
        public float Feline_Delivery_Dash_Stamina_Rate; // Offset: 1996
        public float Feline_Riser_S_IFrames; // Offset: 2000
        public float Feline_Riser_L_IFrames; // Offset: 2004
        public float Feline_Temper_Shell_Attack_Rate; // Offset: 2008
        public byte Feline_Temper_Blur_Level_Bonus; // Offset: 2012
        public float Feline_Cliffhanger_Stamina_Rate; // Offset: 2013
        public float Feline_Slugger_Stun_Attack_Rate; // Offset: 2017
        public float Feline_Bombardier_Ballista_Attack_Rate; // Offset: 2021
        public float Feline_Bombardier_Cannon_Attack_Rate; // Offset: 2025
        public float Feline_Bombardier_Gunlance_Shell_Attack_Rate; // Offset: 2029
        public float Feline_Bombardier_Gunlance_WyvernFire_Attack_Rate; // Offset: 2033
        public float Feline_Bombardier_Gunlance_Wyrmstake_Cannon_Attack_Rate; // Offset: 2037
        public float Feline_Bombardier_Charge_Blade_Impact_Phial_Attack_Rate; // Offset: 2041
        public float Feline_Bombardier_Bowgun_Sticky_Ammo_Attack_Rate; // Offset: 2045
        public float Feline_Bombardier_Bowgun_Wyvern_Ammo_Attack_Rate; // Offset: 2049
        public byte Feline_Moxie_Health_Threshold; // Offset: 2053
        public byte Feline_Dungmaster_Escape_Bonus; // Offset: 2054
        public float Feline_Provoker_Rate; // Offset: 2055
        public float Feline_Cool_Cat_Power_UP_Time_Needed; // Offset: 2059
        public float Feline_Cool_Cat_Power_UP_Duration; // Offset: 2063
        public float Feline_Cool_Cat_Attack_Bonus; // Offset: 2067
        public float Feline_Booster_Attack_Bonus; // Offset: 2071
        public float Feline_Booster_Defense_Bonus; // Offset: 2075
        public float Feline_Booster_Duration; // Offset: 2079
        public float Feline_Groomer_Defense_Down_Duration_Multiplier; // Offset: 2083
        public float Feline_Groomer_Element_Blight_Recovery_Multiplier; // Offset: 2087
        public float Feline_Parting_Gift_Radius; // Offset: 2091
        public ushort Feline_Parting_Gift_Recovery_Value; // Offset: 2095
        public float Feline_Recoil_Attack_Multiplier_1; // Offset: 2097
        public float Feline_Recoil_Attack_Multiplier_2; // Offset: 2101
        public float Feline_Recoil_Attack_Multiplier_3; // Offset: 2105
        public float Feline_Recoil_Attack_Multiplier_4; // Offset: 2109
        public float Feline_Recoil_Attack_Multiplier_5; // Offset: 2113
        public float Unk84; // Offset: 2117
        public float Music_Skill_Bless_Random_Rate; // Offset: 2121
        public float Music_Skill_Bless_Damage_Cut_Rate; // Offset: 2125
        public float Music_Skill_Extend_Time; // Offset: 2129
        public float Music_Skill_Extend_Time_Master; // Offset: 2133
        public float Music_Skill_Extend_Time_MR_Master; // Offset: 2137
        public float Music_Skill_Major_Heal_Rand_Rate; // Offset: 2141
        public float Music_Skill_Major_Heal_Rand_Master_Rate; // Offset: 2145
        public float Music_Skill_Major_Heal_Rand_MR_Master_Rate; // Offset: 2149
        public float Music_Skill_Heal_0_Minor; // Offset: 2153
        public float Music_Skill_Heal_0_Major; // Offset: 2157
        public float Music_Skill_Heal_1_Minor; // Offset: 2161
        public float Music_Skill_Heal_1_Major; // Offset: 2165
        public float Music_Skill_Heal_2_Minor; // Offset: 2169
        public float Music_Skill_Heal_2_Major; // Offset: 2173
        public uint Music_Skill_Hp_Up_0; // Offset: 2177
        public uint Music_Skill_Hp_Up_1; // Offset: 2181
        public float Music_Skill_Mantle_Duration; // Offset: 2185
        public float Music_Skill_Mantle_Duration_Put; // Offset: 2189
        public float Music_Skill_Stamina_Up_Rate; // Offset: 2193
        public float Unk85; // Offset: 2197
        public float Unk86; // Offset: 2201
        public uint Unk87; // Offset: 2205
        public uint Unk88; // Offset: 2209
        public float Unk89; // Offset: 2213
        public float Unk90; // Offset: 2217
        public float Unk91; // Offset: 2221
        public uint Unk92; // Offset: 2225
        public uint Unk93; // Offset: 2229
        public float Unk94; // Offset: 2233
        public float Unk95; // Offset: 2237
    }
}